canonical/juju-dashboard

.env
package.json
src/components/SecondaryNav/_secondary-nav.scss
src/scss/_layout.scss
yarn.lock

Fix vanilla imports by adding env variable to `node_modules` folder and adding `@import "vanilla-framework/scss/colors_settings";` to each SCSS partial.
- Pull code
- Verify no errors in console
- Verify page loads correctly
Fixes #13

Fix vanilla imports

---

src/components/TableList/TableList.js
src/index.js
src/juju/actions.js
src/juju/index.js
src/juju/reducers.js
src/reducers/root.js

Request additional model information from the controller and display the credential name in the model table.
- Pull code
- You know how this goes already....It should now show the credential name and the controller uuid in the model table.
The content will likely wrap and overlay other columns, this needs to be addressed in a follow-up

Add the credential name to the model details table.

---

package.json
src/app/selectors.js
src/components/Terminal/Terminal.js
src/components/Terminal/_terminal.scss
src/components/Terminal/cleanup-terminal.js
src/components/Terminal/setup-terminal.js
src/components/Terminal/xterm-addon-terminado.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Details/_model-details.scss
yarn.lock

Create a Terminal component on the ModelDetails page that will connect to the limited shell on JAAS using the currently active users credentials.
- Pull code
- Open http://0.0.0.0:8036/models/foo
- The Terminal should be open and will try and switch to a model called `test3`. You should now be able to execute limited terminal commands here like `ls -al` and `juju` commands.
Fixes #889

Create Terminal component on ModelDetails page

---

src/app/selectors.js
src/components/App/App.js
src/components/App/__snapshots__/App.test.js.snap
src/components/IsLoggedIn/IsLoggedIn.js
src/components/IsLoggedIn/__snapshots__/isLoggedIn.test.js.snap
src/components/IsLoggedIn/isLoggedIn.test.js
src/components/Terminal/Terminal.js
src/juju/actions.js
src/juju/index.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

- When trying to view an authenticated page, if you've not already authenticated it'll now render a very basic text link for you to authenticate with usso.
- Get the model UUID and pass it to the Terminal component for use later.
- Pull code
- Open / it should request that you log in.
- After logging in, click one of the models in your model list to show the details page.
- The page with dummy data should load as expected.

Add auth wrapper components & Fetch model UUID on details page

---

src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/components/TableList/_table-list.scss

Naively sort the models by status and then display them in separate tables. 
- Pull code
- If you have models with units who's agents are `lost` then you'll see them in the topmost table.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/929
We don't have a spec for this so at the moment it's only splitting the models by applications that have units who's agents are `lost`. This will need a follow-up to enhance this sorting functionality but it's good to get the component output landed so we can style things.
I'll leave https://github.com/canonical-web-and-design/juju-squad/issues/930 open to track for the follow-up
For those who may not have models in this state:

Sort models by status and display them in separate tables

---

Dockerfile

Change nginx port for prod
- Pull code
- Run `./run build`
- ` docker build --build-arg REVISION_ID=test --tag prod-comms.docker-registry.canonical.com/dashboard.jaas.ai:latest .`
- `docker run -d -p 8080:80  prod-comms.docker-registry.canonical.com/dashboard.jaas.ai:latest`
- http://localhost:8080
- should work

Change port to 80 for prod

---

src/components/FilterTags/_filter-tags.scss
src/components/Header/_header.scss
src/components/Layout/_layout.scss
src/components/PrimaryNav/_primary-nav.scss

- Make sidebar and header sticky
- Sidebar styling tweaks
- Pull code
- Cross-ref with design
https://zpl.io/a3dqpAy
- Sidebar still does not have icons as I can't export them from Zeplin. Issue: https://github.com/canonical-web-and-design/jaas-dashboard/issues/95
- Discussion on-going on whether to add external icon

Sidebar styling tweaks

---

src/app/selectors.js
src/components/TableList/TableList.js
src/components/TableList/TableList.test.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/juju/index.js
src/juju/reducers.js
src/pages/Models/Models.test.js

The model list is now grouped using the same selector as the model summary in the header.
- Pull code
- Your models should be grouped between the three sections and those should match the values in the header summary.
A new section of model data is created in the Redux store, `modelData` this is a collection of all the data we get from all the different API calls. This is done because the multiple locations for data was becoming unwieldy to work with. This will also mirror more closely how the data will be structured when we have a single API for all of the model data.
Unfortunately by making this change the test scaffolds no longer work properly as they do not support the `modelData` top level key. A follow-up …

Group model list models using new selectors

---

src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Details/_model-details.scss

Add entity icons to models details page
- Pull code
- Go to model detail page and verify that charm icons appear in the first table

Add entity icons to models details page

---

src/app/actions.js
src/app/root.js
src/app/selectors.js
src/components/Layout/Layout.js
src/components/Layout/Layout.test.js
src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/Layout/_layout.scss
src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/PrimaryNav/_primary-nav.scss
src/hooks/useHover.js
src/pages/Models/Details/ModelDetails.js
src/scss/_settings.scss

Make the models details sidebar collapsible
- Pull code
- Go to models details page and see the sidebar is collapsed. 
- Hover over to expand and interact with it.
- Hover off to see it collapse again.
- No other page should have this behavior.
#129 
- I tried to test for the existence of the `has-collapsible-sidebar` on the `<ModelDetails>` component but it's not there when Jest loads it - is this before useEffect onDomReady?
- When you expand the sidenav, open the external nav and hover off - the external nav does not close. Will follow up later.
- The icons in the collapsed sidebar will need proper aligning and pixel pushing. I will follow up with @spencerbygraves on this.

Models details collapsible sidebar

---

src/components/Terminal/Terminal.js
src/components/Terminal/setup-terminal.js

When running `juju switch` from within the terminal it now changes the UI to the model you've switched to.
- Pull code
- View a model
- After the terminal has loaded then juju switch to a different model. The UI should update to that model and the terminal should not re-render or output any 'logging-in' messages.
- Do this a few times between your own models and your shared models.
- Try and break it!
It's probably best if #156 lands first else you'll have to do this QA before it times out, then refresh, etc.
Fixes #123 
- When switching to a model you own the URL will contain the full path to your model ie) `foo@external/mymodel` instead of just `mymodel` this has no negative side effects but a longer url.

Switch UI to a different model on juju switch

---

src/juju/index.js
src/juju/reducers.js

- When connecting to a controller, start the pinger on 20s increments to keep the controller connection alive. This is required because the controller interactions can be spaced out longer than the 1m timeout in the event the user has a large number of models we're polling against.
- If a model connection takes longer than 5s then abandon the connection. This was necessary because sometimes model connections hang, which prevents the poller from starting over again as something is always stuck in the queue.
- Pull code
- The model list should work as expected
- To test the failure case, change the timeout to 50ms from 5000ms and reload. The console should have a number of console errors that an item has timed out.
Fixes #105

Controller connection reliability improvements

---

src/components/ButtonToggle/_button-toggle.scss
src/components/Filter/_filter.scss
src/components/FilterTags/_filter-tags.scss
src/components/Header/_header.scss
src/components/InfoPanel/_info-panel.scss
src/components/Layout/_layout.scss
src/components/PrimaryNav/_primary-nav.scss
src/components/TableList/_table-list.scss
src/components/Terminal/_terminal.scss
src/components/UserIcon/_user-icon.scss
src/pages/Models/Details/_model-details.scss

Use generic Vanilla import instead of specific color settings. This should mean all of Vanilla can be accessed if needs be, not just colors. 
- Pull code
- Ensure no errors.

Use generic Vanilla import instead of specific color settings

---

src/components/InfoPanel/_info-panel.scss
src/pages/Models/Details/_model-details.scss

Reduce info panel width on smaller screens
- Pull code
- Go to model details
- Start with screen width less than 1681px then increase screen width and view changes with info panel and topology
Fixes #166

Reduce info panel width on smaller screens

---

src/components/InfoPanel/InfoPanel.js
src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

The cloud provider name was being incorrectly displayed. This shows the cloud provider name correctly on the model details page.
- Pull code
- View a model details page and the cloud provider name should be shown correctly.
Fixes #178

Show cloud provider name in model details

---

src/components/InfoPanel/_info-panel.scss
src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Details/_model-details.scss
src/pages/Models/Models.js
src/pages/Models/_models.scss
src/scss/_settings.scss
src/scss/_utils.scss
src/scss/custom/_status_icons.scss
src/scss/custom/_tables.scss
src/scss/index.scss

- Align table columns
- Switch machine and unit icons in config column
- Capitalise td strings to match designs
- Turn off Vanilla text increases at larger breakpoints
- Tweak breakpoint for topology panel to 1580px
- Pull code
- View models and model details tables and verify that columns align as per the design
If you add this snippet to `index.scss`, you can see the column alignment visually.
```css
td {border-right: 1px solid orangered}
```
Fixes #119, 
Fixes #140, 
Fixes #142, 
Fixes #180, 
Fixes #146,
Fixes #179

Align table columns

---

.circleci/config.yml
run
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Details/_model-details.scss

Truncate long machine error messages.
- Pull code
- View a model with long machine error messages. Contact me if you need one shared with you.
Fixes #173

Truncate machine error messages

---

src/pages/Models/Details/_model-details.scss

Fixes #185
Remove double border on table rows
- Pull code
- Verify that double borders on table rows ahve been removed.

Remove double border on table rows

---

src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/scss/_utils.scss
src/scss/custom/_status_icons.scss

Fixes #187
Correct status label capitalisation
- Pull code
- Status in table headers should be uppercase, all others should be capitalised.

Correct status label capitalisation

---

src/components/FilterTags/_filter-tags.scss
src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap

- Add dummy link to models listing
- Ensure filter panel doesn't obscure links in models table
- Pull code
- Cross-ref designs with links on model listings
Fixes #141
https://zpl.io/beOAPkq

Add dummy link to models listing

---

src/pages/Models/Details/_model-details.scss

Remove bottom-border on last table rows
- Pull code
- Verify no tables have a bottom border
See: https://github.com/canonical-web-and-design/vanilla-framework/issues/2628#issuecomment-551113219

Remove bottom-border on last table rows

---

src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/pages/Models/_models.scss
src/scss/index.scss

Add tooltips to config icons in Models list
- Pull code
- Roll over config icons on Models listing table
Fixes #145

Add tooltips to config icons in Models list

---

src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap

Use soft links on Models listing page
- Pull code
- Check that only model name is a blue link, the rest are black but blue on hover
Fixes #193

Use soft links on Models listing page

---

src/components/InfoPanel/_info-panel.scss

Add some padding around the ghost bundle image.
- Pull code
- View the model details page, there should be some padding around the bundle ghost image.
Requested from https://github.com/canonical-web-and-design/jaas-dashboard/pull/196#issuecomment-551445301

Add some padding around the ghost bundle image.

---

src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/scss/_utils.scss

The work to restrict error message from overflowing table cells meant that the tooltips were chopped also.
- Pull code
- Verify tooltips now appear correctly
Fixes #205

Fix tooltips overflow

---

src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap

Add title attribute to truncated error message on models details page
- Pull code
- Go to models details and hover over truncated red error message and verify browser tooltip appears
Fixes #212

Add title attribute to truncated error message on models details page

---

src/app/actions.js
src/app/root.js
src/app/selectors.js
src/components/LogIn/LogIn.test.js
src/components/UserIcon/UserIcon.js
src/juju/index.js

When logging out clear the identity item out of the bakery instead of removing the bakery. This allows the user to re-log in after logging out.
- Pull code
- Log in, log out, navigate around, log in, log out, etc. Try and break it.
Fixes #121

Update logout mechanism to allow re-log-in

---

src/components/PrimaryNav/_primary-nav.scss

Collapse external nav if the user hovers off and sidebar collapses
- Pull code
- Open model details
- Hover over sidebar
- Open external nav
- Hover off sidebar
- Verify external nav collapses
Fixes #231

Collapse external nav if user hovers off and sidebar collapses

---

src/components/PrimaryNav/_primary-nav.scss

Refactor to use negation :not() and fix padding
- Pull code
- Go to model details
- Hover over sidenav
- Open external nav
- Hover off sidenav
- Verify collapsing external nav
Fixes #231

Refactor to use negation :not()

---

package.json
src/components/FilterTags/_filter-tags.scss
yarn.lock

- Upgrade Vanilla to 2.5.0
- Fixes bug where external link icon in the external menu was cut off
- Removes bottom margin from the input element in the header
- Pull code
- Verify the above
Fixes #230

Upgrade Vanilla to 2.5.0

---

README.md
craco.config.js
package.json
src/app/check-auth.js
src/juju/index.js
yarn.lock

The mangling being done by Terser in the default CRA Webpack config was causing issues in a few files. To resolve this we use `craco` to patch the webpack config to include the `reserved` configuration value to skip mangling on a few property names. 
Disabling mangling here increases the finished bundle by only 62B.
- Pull code
It should work as before
- Pull code
- Run `./run exec yarn run build`
- use your webserver of choice to serve the build files. I use `http-server`
- `yarn global add http-server`
- `cd build && http-server`
It should work as expected. Try logging out, refreshing, logging back in, etc.
Fixes #225

Patch the optimization key of Webpack in CRA

---

.env
src/app/model-poller.js
src/juju/actions.js
src/juju/index.js
src/juju/reducers.js

Create API endpoint for fetching the controller list.
This does not work in Firefox, you'll have to use Chrome/Safari to QA. It appears to be around the `OPTIONS` request not having the correct `CORS` headers for redirects. I'll still need to investigate this further.
In Firefox it'll just fail silently with a `CORS` warning message in the console.
- Pull code
- After logging in, watch the redux store. `juju/controllers` should contain the controller list (if you have permissions to do so).
Fixes #237

Create API endpoint for fetching the controller list

---

package.json
src/components/ModelGroupToggle/ModelGroupToggle.js
src/components/ModelGroupToggle/ModelGroupToggle.test.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
src/pages/Models/Models.js
src/pages/Models/Models.test.js
yarn.lock

Persist model grouping via URL
- Pull code
- Click different grouping toggles and observe URL changes
- Refresh the page and filter should persist
Fixes #260

Persist model grouping via URL

---

src/components/Topology/Topology.js

Position unplaced applications in a grid below any placed applications on the topology.
- Pull code
- Contact me to get access to my models that contain models with partial and all unplaced applications.
- Do they position the applications in a grid below any placed applications?
Fixes #242

Position unplaced applications on the topology

---

src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/__snapshots__/CloudGroup.test.js.snap
src/components/ModelTableList/__snapshots__/OwnerGroup.test.js.snap
src/components/ModelTableList/__snapshots__/StatusGroup.test.js.snap
src/components/ModelTableList/shared.js

For the JAAS controller, render "JAAS" instead of its UUID.
- Pull code
- View your models on all three groupings. The controller column should say "JAAS"
Fixes #313

Render JAAS instead of the controller UUID

---

craco.config.js

The Annotations facade was being munged by the CRA config. This stops it so that the production builds can use the Annotations facade.
- Pull code
- The topology should be shown on the model details page
Fixes #321

Stop munging of the Annotations facade.

---

src/components/InfoPanel/InfoPanel.js
src/components/InfoPanel/InfoPanel.test.js
src/components/InfoPanel/_info-panel.scss
src/scss/index.scss

When clicking the expand icon, render the topology in a Modal
- Pull code
Fixes #243 
There is an error in the console now from no title being provided in the modal. This issue has been raised in the component repository so it will be resolved once that change has been made and the package updated. #328

Click to expand topology

---

src/pages/Models/Models.js

When using the back button after toggling the model grouping it now correctly updates the UI.
- Pull code
- Play with the model grouping buttons, they should update the UI as expected
- Hit the back button, it should navigate back through the groupings.
- Refresh with a grouping query string in the URL, it should render that grouping.
Fixes #330

Fix back button navigation with model grouping

---

src/components/InfoPanel/_info-panel.scss
src/pages/Models/_models.scss

- Move the topology modal to be on top of the whole application.
- Increase the widths on the 'configuration' column on the model list owners grouping
- Pull code
- Check that the owners grouping model list table doesn't wrap on any columns.
- Check that the topology modal covers the sidebar and header.
Fixes #343 
Fixes #332

Adjust modal z-index and owners grouping widths

---

src/components/Topology/Topology.js

Increase the size of the icons and darken the relations and application icon outlines.
- Pull code
- View a model visualization and it should look as the screenshots show.
Fixes #324

Increase the size of the icons and darken the relations and application icon outlines

---

src/app/send-analytics-hook.js
src/components/App/App.js
src/components/App/__snapshots__/App.test.js.snap
src/components/FilterTags/FilterTags.js
src/components/InfoPanel/InfoPanel.js
src/components/Routes/Routes.js
src/components/UserIcon/UserIcon.js
src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
src/pages/Settings/Settings.js
src/pages/Settings/settings.scss
src/scss/index.scss

- Add Settings page.
- Add option to disable analytics.
- Pull code
- Run `./run clean && ./run exec yarn run build`
- Run `cd build && serve` (You may have to install this `npm i serve`.
- Open the path serve returns.
- Navigate around a bit.
- You notice analytics events being sent in the devtools. You can filter the requests by 'analytic'
- Click the "Settings" link in the user drop down and it should take you to the settings page.
- Toggle the option to disable analytics
- `window.localStorage.getItem('disableAnalytics')` should be `"true"`
- Refresh
- The analytics should no longer be sent
- Go to settings and re-enable
- `window.localStorage.getItem('disableAnalytics')` should be `"false"`
- Refresh
- You should see analytics again.
- Click the demo link below and view devtools …

Add Settings component

---

src/app/selectors.js
src/components/FilterTags/FilterTags.js
src/components/FilterTags/FilterTags.test.js
src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/CloudGroup.test.js
src/components/ModelTableList/ModelTableList.js
src/components/ModelTableList/ModelTableList.test.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/OwnerGroup.test.js
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/StatusGroup.test.js
src/pages/Models/Models.js

When selecting filter options from the drop down filter the table list.
- Pull code
- View the model list and select some items from the filter dropdown, it should filter the resulting mode list.
- Switch between the groupings (status, cloud, owner) the filters should persist.
- Refresh, the filters should persist.
Fixes #125

Filter by dropdown selections

---

src/scss/custom/_status_icons.scss

Make is-provisioning error red
- Pull code
- Go to model details page 
- Scroll down to 'machine' table
- Verify any provisioning errors are red
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/308

Make is-provisioning error red

---

craco.config.js

Stop munging function names to allow us to continue to gate thunks based on whether the user is authenticated or not. This is to get around a bug in terser.
- Pull code
- Run `./run exec yarn run build`
- Run `cd build && serve .` 
- The app should then work as expected.
Fixes #392

Do not munge function names to allow for gating thunks by authentication

---

src/components/App/App.js
src/components/App/App.test.js
src/components/Routes/Routes.js

- Replace the low level Router with BrowserRouter to support basename.
- Build and run using Juju, the app should load and the URL should be prefixed by the basename.
- To test this locally: 
- - Open App.js and change line 40 from `<Router basename={baseAppURL} ...` to `<Router basename="/dashboard" ..`.
- - Load the app, it should load and the URL should start with /dashboard/...

Support URL basename

---

src/components/InfoPanel/InfoPanel.js
src/components/InfoPanel/_info-panel.scss

- Fix topology modal window in Chrome and FF
- Fix the initial render of the infoPanel topology on smaller screen size
- Pull code
- Go int oa model
- See the mini topology renders correctly
- Now shrink the screen size down until the infoPanel resizes
- Refresh and see the mini topology renders correctly
- Check the model topology renders correctly
- Check the model in both Chrome and FF
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/403

Fix topology modal window

---

src/components/InfoPanel/InfoPanel.js

- Close topology on Escape key click
- Add error text to title of topology as I had instances when refreshing where model would not load but topology modal was still onscreen
- Add conditional so that expand button would not appear unless modelName exists
- Pull code
- Go to models details page 
- Open topology
- Hit Escape key
- Verify topology closes

Close topology on Escape key click

---

src/components/Terminal/Terminal.js
src/components/Terminal/_terminal.scss

Set maximum terminal height on drag
- Pull code
- Go to model details page
- Drag terminal up
- See that it doesn't obscure page header
Fix #415

Set maximum terminal height on drag

---

src/app/utils.js
src/components/InfoPanel/InfoPanel.js
src/components/Layout/Layout.js

Collapse sidebar on all screens less than 1400px
- Pull code
- Change your screen resolution up and down over the 1400px breakpoint and observe navigation collapse accordingly
#404

Collapse sidebar on all screens less than 1400px

---

src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/PrimaryNav.test.js
src/index.js
src/testing/complete-redux-store-dump.js
src/ui/actions.js
src/ui/index.js
src/ui/selectors.js

Persist external nav using redux store
- Pull code
- Open external nav and navigate between controller, model and model detail views
- External nav should remain open until user makes the decision to close it
Fixes #411

Persist external nav using redux store

---

src/components/Layout/Layout.js

Fix memory leak on layout resize
- Pull code
- Resize window
- Verify no console error about memory leaks
Fixes #417

Fix memory leak on layout resize

---

src/components/App/App.js
src/hooks/useAnalytics.js

Remove the env conditional on GA
- Pull code
- Check your blocker is now blocking GA
- Check events are triggering
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/402

Remove the env conditional on GA

---

package.json
src/components/Terminal/Terminal.js
src/components/Terminal/_terminal.scss
src/scss/_utils.scss
yarn.lock

- Bump xterm
- Remove redundant code
- Prevent body scroll when scrolling in the terminal
- Pull code
- Go to model details page
- Hover over terminal
- Scroll terminal and verify that model details table does not scroll also
Fixes #419

Prevent body scroll

---

src/components/Terminal/Terminal.js

Modify height calculation to avoid the terminal jumping when dragging to resize.
- Pull code
- View a model details page and click to drag the header. It should not jump up a bit to align the cursor with the top of the terminal
- Try clicking a few places in the header and dragging.
- You may notice that the cursor can 'slide' on the header if you move fast, this appears to be a browser issue around keeping the coordinates in sync.
- Try this resize in multiple browsers.
Fixes #427

Modify height calculation to avoid the terminal jumping when resizing

---

src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/_primary-nav.scss

Added a link to the sidebar that opens a modal guiding users to the old GUI on JAAS. The link will only show up in JAAS unless we get confirmation that 2.8 will contain both UI's then we will expand this to handle that use case.
- Pull code
- You should see a link to switch back to the old GUI
- Click the link and a modal should pop up
- Click the link to the old GUI and it should work.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1167
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1172

Create a link to go back to the old GUI 

---

craco.config.js

Due to how jujulib works it requires the class and function names to not be munged. This stops the munging of the class names but unfortunately bloating the size of the application. We will be rewriting how jujulib works in the near future so this is only a temporary setback.
No QA it'll need to be QA'd on staging.

Do not munge class names to fix issues with jujulib names.

---

src/components/Layout/Layout.js
src/components/Layout/Layout.test.js
src/components/Layout/_layout.scss
src/scss/index.scss

- Add a notification to layout with dismissal persisting to cookie
Note: will add blog and discourse links when available
- Pull code
- Verify that release notification appears
- Dismiss notification
- Refresh page and notification should not appear again

Release banner and beta label

---

src/components/App/App.js
src/hooks/useAnalytics.js

Add `isProduction` check for analytics so that stats are not distorted by development
- Pull code

Add isProduction check for analytics

---

src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js

Temporarily remove the terminal component from rendering.
- Pull code
- View one of the model details pages, no terminal should render.

Temporarily remove the terminal component from rendering.

---

src/components/ErrorBoundary/ErrorBoundary.js

Send error to sentry if ErrorBoundary is triggered.
- Pull code
- comment out the production check https://github.com/canonical-web-and-design/jaas-dashboard/blob/master/src/index.js#L31
- Add some code to throw an error `throw "foo"` in a react component and see that an error is sent.

Send error to sentry if ErrorBoundary is triggered.

---

src/components/PrimaryNav/PrimaryNav.js

Show the version number and beta label when running in a Juju controller.
Hide the 'switch back to the GUI' when running in a Juju controller.
QA requires a build of Juju from a certain branch, best to wait until that gets merged into `develop` and an rc is cut.

Show the version number and beta label in Juju.

---

src/app/model-poller.js
src/app/selectors.js
src/app/utils.js
src/juju/index.js
src/pages/Controllers/Controllers.js
src/pages/Controllers/Controllers.test.js
src/pages/Controllers/__snapshots__/Controllers.test.js.snap
src/testing/complete-redux-store-dump.js

If a user is not an administrator on the controller then do not try and request the controller data. 
If a non-admin tries to view the controller page then show a warning.
- Pull code
JAAS
- View the controller page, you should see a warning like below as you're connected to public JAAS.
Self-Bootstrap
- `juju bootstrap localhost`.
- Access the existing GUI and accept the self-signed cert `juju gui`.
- Then modify `config.js` to point to your new controller `baseControllerURL: "10.123.321.1:17070",`
- Open the Dashboard and enter the credentials from the above `juju gui` command.
- View the controller page, it should show a controller view without data, but no warning. The data for this view on a self-bootstrap is coming next. …

Handle non-admins accessing the Controller view

---

.gitignore
package.json
scripts/generate-release-tarball
scripts/generate-version-file

Generate a tarball that can be used in Juju and JAAS.
- Pull code
- Run `./run exec yarn run generate-release-tarball`
- Run `tar -ff juju-dashboard-0.1.1.tar.bz2
It should look like the build directory tar'd up.

Generate release build tarball

---

src/components/ModelTableList/_model-table-list.scss

Override the styling set in the `react-components` package to fix the position of the models list tables `caption`
- Pull code
- Before your models load you should see the correct spacing as per the screenshot.
Fixes #475

Set correct spacing for 'no models' table caption.

---

src/components/InfoPanel/_info-panel.scss
src/pages/Models/Details/_model-details.scss

[Fix] Correct model detail double padding
- Pull code
- Go to details page - check the padding
#488

fix: Correct model detail double padding

---

src/pages/Models/Details/_model-details.scss

(fix) Prevent entity icons from expanding to the height of table row
- Pull code
- Go to the model details page
- Verify all icons are the same size and there are no squircles
Fixes #449

fix(model details): Prevent entity icons from expanding to height of table row

---

src/components/FilterTags/_filter-tags.scss

(fix) Align filter tags to filter menu
- Pull code
- Open filter menu and verify alignment
Fixes #484

(style) Align filter tags to filter menu

---

src/components/Layout/_layout.scss

(fix) Stop notification overlaying sidebar
- Pull code
- Do not dismiss release notification
- Browse /models and /model-details pages at small and wide resolutions
Fixes #492

fix: Stop notification overlaying sidebar

---

src/components/Layout/Layout.js

(fix) Hide release notification until user logged in
- Pull code
- Open http://0.0.0.0:8036/ in incognito mode
- Verify that you cannot see release notification behind the login modal
Fixes #498

fix: Hide release notification until user logged in

---

src/scss/custom/_tables.scss

- Reset content on thead after which resolved the extra space.
- Pull code
- Check that the space in the issue is not there anymore
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1166
On first load:

fix(style): remove small gap between thead and tbody

---

package.json
src/juju/actions.js
src/juju/index.js
src/pages/Controllers/Controllers.js
yarn.lock

When viewing the controller details page for a Juju bootstrapped environment show the controller information.
- Bootstrap a juju environment on a public cloud using the rc-2 snap.
- Run `juju dashboard` and accept the self-signed cert warnings.
- Close that tab.
- Pull code
- Edit `config.js` 
- `baseControllerURL` points to the ip:port value outputted in the above `juju dashboard` command.
- 'identityProviderAvailable' is `false`.
- `isJuju` is `true`.
- View the controller details page. You should see content similar to the screenshot below.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1272

feat(controllers): show controller data on controller page for single controller environments

---

src/components/InfoPanel/InfoPanel.js

(fix) Fall back to modelName if cannot split on slash -this prevents an erroneous "Model not loaded" message from appearing
- Pull code
- Go to model details pages, expand topologies and verify the title of the model appears correctly
Fixes #500

fix(model details): correctly display the modelName in the expanded model topology view

---

src/pages/Models/Details/generators.js
src/scss/_utils.scss

@hatched I removed this header as there is no content being generated for the column - correct?
(fix) Remove redundant table header
(fix) Correct first letter capitalisation util 
- Pull code
- View model details page for model with relations info
- View relations table and verify headers match columns
Fixes #486

fix(model details): remove redundant table header

---

src/app/actions.js
src/app/check-auth.js
src/app/model-poller.js
src/app/root.js
src/app/selectors.js
src/components/LogIn/LogIn.js
src/components/LogIn/LogIn.test.js
src/components/LogIn/_login.scss
src/juju/index.js

If there is an error message when logging in via the user/pass dialog then render that error.
- Pull code
- Install the juju 2.8-rc2 snap
- `juju bootstrap` into a public cloud
- `juju dashboard` and connect to that dashboard to accept the self-signed cert.
- take note of the ip address and u/p
- Open config.js and change: 
- `baseControllerURL` to the ip address and port (if any) from above.
- `isJuju` to `true`
- `identityProviderAvailable` to `false`
- Submit the form with an invalid username and password.
- Use the above u/p to log in successfully. 
Fixes #388

Render any login error messages.

---

src/components/Topology/Topology.js

The topology no longer tries to render applications that don't exist from a cross model relation. This is a temporary fix until cross model relations are fully supported in the dashboard.
- Install the juju 2.8-rc2 snap
- `juju bootstrap` into a public cloud
- `juju dashboard` and connect to that dashboard to accept the self-signed cert.
- take note of the ip address and u/p
- Follow the deployment steps in #526 
- Open config.js and change: 
- `baseControllerURL` to the ip address and port (if any) from above.
- `isJuju` to `true`
- `identityProviderAvailable` to `false`
- `./run`
- You should be able to view the details page for all your models.
Fixes #526

Topology no longer tries to render applications that don't exist.

---

src/app/actions.js
src/app/root.js

After clicking the log out button, you were successfully logged out but the UI wasn't indicating as such. This removes the controller connection data in addition to the user data which we check to see if the user is logged in.
Note #289 is still an issue.
- Pull code
- After logging in, log out, it should present the green login button again.
- Refresh, you can log back in again and the app works as expected.
Fixes #465

fix: Logging out now shows the log-in UI again.

---

src/pages/Models/Details/generators.js
src/scss/custom/_status_icons.scss

The machine table now uses the agent status instead of instance status to make it more Juju-centric and provide clearer error messaging. The upcoming machine view will have the instance status data to provide a full picture.
- Pull code
- View the model details of a few models in error, alert, running to see the different values for this table.
- Add a unit to an application and watch the statuses update(depending on the provider and update cycles you may miss some if they go fast).
Fixes #305

Use agent status instead of instance status in machine table

---

src/components/DonutChart/DonutChart.js
src/components/DonutChart/DonutChart.test.js
src/pages/Controllers/ControllerChart/ControllerChart.js
src/pages/Controllers/ControllerChart/_controller-chart.scss

Disable controller charts if no data provided
- Pull code
- Open ControllerOverview.js
- Change line 46 to `<ControllerChart chartData={{}} totalLabel="application" />`
- Refresh page
- Verify Application chart is now disabled
Fixes #555

Disable controller charts if no data provided

---

README.md

Expanded the documentation to include instructions on how to QA the Dashboard in both Juju and JAAS environments.
....seriously....read the docs! 😉

Expanded the readme documentation for QAs

---

package.json
src/app/model-poller.js
src/index.js
src/juju/index.js

- Stop the pinger if there is an error making the request.
- Add `jujuVersion`, `isJuju`, and `dashboardVersion` to Sentry error messages.
- Bumped version to 0.1.8 for release.
- Bootstrap a new Juju controller on your cloud provider of choice using the latest Juju snap.
- `juju bootstrap google` 
- Build a release tarball of the Dashboard.
- `./run exec yarn run generate-release-tarball`
- Upgrade the Dashboard on your new controller
- `juju upgrade-dashboard juju-dashboard-<version>.tar.bz2`
- Access the Dashboard
- `juju dashboard`
- `./run`
- Open the browser console
- Disconnect your browser from the internet to break the websocket connection
- You should see a couple error messages in the console indicating that it cannot send a couple requests but you shouldn't get any unhandled …

Stop pinger on error and enhance Sentry errors

---

src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.js

Remove the 'configuration' header in the model list tables and move the column next to the model name.
- Pull code
- See the new layout in the model list view in all 3 groupings (status, owner, cloud)

Remove the 'configuration' header in the model list tables and move the column next to the model name.

---

.eslintrc
package.json
public/config.js
public/config.js.go
public/index.html
public/manifest.json
scripts/generate-release-tarball
scripts/generate-version-file
src/components/Layout/Layout.js
src/index.js

Converted the appropriate instances of "JAAS Dashboard" to "Juju Dashboard'
The repo name has not yet been changed.
- Pull code
- The application should work as expected
- `./run exec yarn run generate-release-tarball` Should generate a tarball with the apprioriate version number in it.
Fixes #571

Convert JAAS Dashboard to Juju Dashboard.

---

src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/PrimaryNav.test.js

Match the link in the PrimaryNav logo to the logo.
- Pull code
- Does the JAAS link go to jaas.ai?
- Change `isJuju` to `true` in `config.js` and then reload.
- Does the Juju link go to juju.is?
Fixes #535

Match the logo link with the logo

---

src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/generators.js

If a charm was deployed locally then use "Local" as the `store` value and "CharmHub" otherwise.
- Pull code
- View your models, do they show "CharmHub" under store?
- View the 'local-test' model, does it show "Local"? Ask me for access if you don't currently have it.
Fixes #545

Change the store column value for local charms

---

src/components/PrimaryNav/PrimaryNav.js

- Make all links external if juju
- Corrected some links to avoid redirects
- Pull code
- Open `config.js` and change `isJuju` to `true`
- Open external nav
- Verify all links are marked as external
Fixes #572

Make all links external if juju

---

src/components/Header/_header.scss

Remove space-on-right bug from models details
- Pull code
- Go to model details page
- View page across different breakpoint and verify spacing on right has been resolved
Fixes #577

Remove space-on-right bug from models details

---

src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/_model-table-list.scss
src/components/ModelTableList/shared.js

Convert the error messages on the model list page into links to the respective model details page.
- Pull code
- Are the error links in the model details page links to the model details page?
Fixes #595

Convert the error messages on the model list page into links.

---

src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/_model-table-list.scss
src/components/ModelTableList/shared.js

Model list error link no longer falls back to the model name.
- Pull code
- In your model list does it show the model name for the error message? Or when refreshing does it flash the model name before the error message?
Fixes #599

Model list error link no longer falls back to the model name.

---

src/pages/Controllers/Controllers.js
src/pages/Controllers/_controllers.scss

Format code snippets in form help text
- Pull code
- Open http://0.0.0.0:8036
- Go to controllers
- Click "Register a new controller"
- Verify code snippets display as code snippets in help text
Fixes #616

Format code snippets in form help text

---

src/app/model-poller.js
src/pages/Controllers/Controllers.js
src/pages/Controllers/_controllers.scss

- Required fields are now marked as such.
- The 'Identity Provider' checkbox how hides if you provide a U/P.
- The user no longer needs to provide the protocol and path for the controller; just the IP.
- The 'Visit Controller' link now only becomes a link when you provide an IP.
- Pull code
- The bugs listed below should be resolved
Fixes #601 
Fixes #611 
Fixes #613 
Fixes #617 
Fixes #618

Register controller UX tweaks

---

src/app/check-auth.js

Allow the user menu to be toggled without authentication.
- Pull code
- Can you open and close the user menu in the bottom left?
Fixes #624

Allow the user menu to be toggled without authentication.

---

src/app/model-poller.js
src/app/selectors.js
src/juju/actions.js
src/juju/index.js
src/pages/Controllers/Controllers.js

When a new controller is registered with the dashboard immediately connect to it and start polling the models.
- Pull code
- Bootstrap a new controller & register it with the dashboard, it should immediately show up in the controller list and the models should appear in the model list.
Fixes #603

Connect to and start polling models when registering a new controller

---

src/app/model-poller.js
src/juju/index.js
src/pages/Controllers/Controllers.js

- Show JAAS instead of admin/jaas for the JAAS controller.
- Resolve the 'unauthorized' error in the console by silently failing.
- Fixed console warning about invalid prop type in the controller.
In the demo link are all three issues below resolved?
Fixes #631
Fixes #632
Fixes #633

Fix: Controller page console errors and JAAS controller name display

---

src/components/Layout/Layout.js
src/components/Layout/_layout.scss

- Add 'skip to main content' link
- Make primary nav accessible via keyboard
- Pull code
- Run through side navigation with keyboard
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/660

Add keyboard navigation to primary navigation

---

src/app/utils.js
src/components/Filter/Filter.js
src/components/Filter/_filter.scss
src/components/SlidePanel/SlidePanel.js
src/components/SlidePanel/SlidePanel.test.js
src/components/SlidePanel/_slide-panel.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Details/generators.js

- Added apps panel to model details page
- Pull feature branch
- Go to models page, click a model
- On model details page, click an app
- Verify side panel opens from the right as expected with correct model info
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1368

Add apps panel to models details page

---

src/components/SlidePanel/SlidePanel.js
src/components/SlidePanel/SlidePanel.test.js
src/pages/Controllers/Controllers.js
src/pages/Controllers/_controllers.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/_model-details.scss

The previous app panel work for the model details incorrectly set a global width and top value for the slide panel which broke the UI for the register controllers panel. This change adds the ability to pass in a className for the slide panel so that each usage of the panel can customize its placement.
As a driveby this also fixes the model link in the controllers page so that it will correctly link when being run with a different basepath.
- Build the dashboard and run it in a self-bootstrapped environment using [this guide](https://github.com/canonical-web-and-design/jaas-dashboard#uploading-the-tarball-to-a-juju-controller)
- Switch to the controller page and click the models link at the top, does it go back to the models list?
- Deploy an application to a model
- Click that …

Allow custom classes to be passed into the slide panel

---

.gitignore
src/app/utils.js
src/components/Counts/Counts.js
src/components/Counts/Counts.test.js
src/components/Counts/_counts.scss
src/components/InfoPanel/_info-panel.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/_model-details.scss

- Added counts to the top of each entity view in the model details page.
- Updated pluralizer to support special case words.
- Pull code
- View a few models and look at the counts on each entity view.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1412
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1413
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1414

Add entity counts to each view in the model details page

---

src/components/SlidePanel/_slide-panel.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Details/generators.js

- Reduce panel to 60% of viewport width
- Enable background interaction when a panel is open
- Pull code
- View model details
- Click a model with more than one app
- Panel will open - should be 60% of viewport
- Click another app under panel and see panel content change
Fixes #685, Fixes #683

Revise panel

---

src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/StatusGroup.test.js

To match the experience in the other views hide empty tables in the status view.
On initial load the page is blank until the data loads, we'll want to add an 'empty' page state as a follow-up.
- Load the demo, is it empty until the data loads? 
- Do the status tables only load if you have data for them?

Hide empty tables in model status view

---

src/scss/index.scss

- Remove redundant override
- Fix focus ring errors styling
- Pull code
- Tab through the page with the keyboard and verify focus styles appear consistently
- Navigate using mouse and verify that no focus rings appear
Fixes #711

Fix focus ring errors styling

---

src/app/selectors.js
src/components/panels/AppsPanel/AppsPanel.js
src/components/panels/MachinesPanel/MachinesPanel.js
src/components/panels/MachinesPanel/_machines-panel.scss
src/components/panels/UnitsPanel/UnitsPanel.js
src/components/panels/_panels.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Details/generators.js
src/scss/custom/_status_icons.scss

- Enable panel tables on model details page
- Change active status dot to green
- Add a loading spinner to model details page
- Conditionally render model details tables based on data available
- Pull code
- Click on a model
- Click the first app
- Observe app panel open
- You can now navigate the tables to slice and dice across apps/units and machines
- Refresh the page
- Observe the loading spinner
Related: https://github.com/canonical-web-and-design/juju-squad/issues/1388

Enable panel tables on model details page

---

public/config.js
src/pages/Models/Details/ModelDetails.js

Add feature flag for WebCLI
- Pull code
- Check WebCLI does not appear
- Open `config.js`
- Change `showWebCLI` to `true`
- WebCLI should now appear on model details page

Add feature flag for WebCLI

---

src/app/selectors.js
src/components/WebCLI/WebCLI.js
src/components/WebCLI/WebCLI.test.js
src/components/WebCLI/__snapshots__/WebCLI.test.js.snap
src/components/WebCLI/connection.js
src/pages/Models/Details/ModelDetails.js

- Refresh the model status data on submitting a command in the Juju Web CLI. This will be removed once we go to the new watcher.
- Split the websocket connection out into its own file to stop working against the React paradigm. 
- Correctly parse the controller/model data to connect to the correct controller in a multi-controller environment like JAAS.
- Bootstrap a new controller with Juju 2.9 (the Juju snap has the 2.9 RC available)
- Build and upload the dashboard to that controller 
- `yarn`
- `yarn generate-release-tarball`
- `juju upgrade-dashboard <path to tarball>` 
- Then log in, the wCLI on the model details page should continue to work as expected.
- Run `juju deploy wordpress` in a model and it should show up in the details page above moments after submitting the command. …

Refresh the model status data on submitting a command

---

src/components/Banner/_banner.scss

Hide banner content when inactive
- Pull code
- Open http://0.0.0.0:8036/models in Firefox
- Minimise vertical height of screen to 6/7 models
- Scroll down and you should not see a banner message as per #747 
Related #747

Hide banner content when inactive

---

src/components/panels/AppsPanel/AppsPanel.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/generators.js

- Rename status to apps in model details view
- Rename apps table to 'Local apps'
- Remove all tables from apps view but apps
- Remove relations table from apps panel
- Switch order of 'rev' and 'store' in apps table
- Pull code
- Go to model details and verify changes above appear as expected
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1512,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1506,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1504,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1505,

Rename status to apps

---

src/scss/index.scss

Add sidenav width override
- Pull code
- Verify side nav now collapses as expected when reducing screen width
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/814

Add sidenav width override

---

src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Details/generators.js

Add apps icon list to machines table
- Pull code
- Click on any model to view details page
- Click 'Machines' tab
- Verify that table now has 'apps' column showing apps icons
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1519

Add apps icon list to machines table

---

src/components/Layout/Layout.js
src/components/Layout/Layout.test.js
src/components/Layout/_layout.scss

Always collapse sidebar on model details pages
- Pull code
- Check sidebar on model details page always collapses regardless of breakpoint
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/794

Always collapse sidebar on model details pages

---

src/components/panels/ConfigPanel/BooleanConfig.tsx
src/components/panels/ConfigPanel/ConfigPanel.tsx
src/components/panels/ConfigPanel/TextAreaConfig.tsx
src/components/panels/ConfigPanel/_config-panel.scss
src/components/panels/LocalAppsPanel/_local-apps-panel.scss

- Ensure that the layout works at `all the widths`!
- Hide the description column for mobile views and show it under the inputs.
- Use the demo.
- View the `charmed-kubernetes` test model.
- View the config page for various apps and resize the browser to various widths.
- Check on your mobile device of choice.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1574
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1582
<details>
<summary>Mobile - short app name w/o reset - expanded description</summary>
</details>
<details>
<summary>Tablet - long app name w/ reset</summary>
</details>
<details>
<summary>Tablet - short app name w/ reset</summary>
</details>
<details>
<summary>Narrow Desktop - long app name w/ reset - expanded description</summary> …

Mobile support for the config panel

---

src/animations/FadeIn.tsx
src/components/panels/ConfigPanel/BooleanConfig.tsx
src/components/panels/ConfigPanel/ConfigPanel.tsx
src/components/panels/ConfigPanel/TextAreaConfig.tsx
src/components/panels/ConfigPanel/_config-panel.scss

Add animations and fades to give the config some life.
Blocked on #843 landing, once it's landed then this can be reviewed and qa'd
- Use the demo link
- Play around with the config and see the animations work, the list of the addressed items are in the issue.
https://github.com/canonical-web-and-design/juju-squad/issues/1601

Add animations to the configuration UI

---

src/components/Header/_header.scss
src/components/SlidePanel/_slide-panel.scss
src/pages/ControllersIndex/ControllersIndex.js
src/pages/ControllersIndex/_controllers.scss
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/Model/Model.test.js
src/pages/EntityDetails/_entity-details.scss
src/pages/ModelsIndex/ModelsIndex.js
src/pages/ModelsIndex/_models.scss

- Increase the header height to `64px`
- Replaced the button group on model details with the [Tabs component](https://canonical-web-and-design.github.io/react-components/?path=/story/tabs--default-story) __Some styling tweaks required__
- Updated panel offset to match the new header height
- Aligned the header titles styling
- Open the demo
- See that the header is now 64px tall
- Go to the controller's list and see the header is aligned and the count is strong
- Go to models list and check the header matches controllers **button group updates to come**
- Go to model details and check the header matches [the design](https://zpl.io/2yKRxDq)
- Click on an application and check the header matches other views
- Click a unit and check the panel is correctly positioned
Fixes …

Switch button group with tabs in model details

---

src/app/utils/utils.js
src/components/Breadcrumb/Breadcrumb.test.tsx
src/components/Breadcrumb/Breadcrumb.tsx
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/_entity-details.scss

Implement the breadcrumb component in the header
Drive-by, fix error while awaiting modelStatusData to become available
- Load the demo and go to a model details
- See that the breadcrumb renders just the model name
- Go into an application and check the breadcrumb now matches [the design](https://zpl.io/aN63dv4)
- To test the drive-by, load the branch locally
- Go to an application details
- Refresh and see that the page loads without an error
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/891

Implement the breadcrumb component in the header

---

src/components/Breadcrumb/Breadcrumb.test.tsx
src/components/Breadcrumb/Breadcrumb.tsx
src/components/Routes/Routes.tsx
src/hooks/useTableRowClick.tsx

- Persist the app name in the unit details URL path
- Update breadcrumbs display correctly on unit details 
- Pull code
- Go to model details and see you get the name and the tabbed options
- Go to an application details and see you get "modelName > Applications > applicationName"
- Go to a unit details and check you get "modelName > Applications > applicationName > unitName"
- Go to a machine details and see you get "modelName > Machines > machineName"  
- [Designs here](https://app.zeplin.io/project/600ef2ab1717a62fd46c0b79/screen/6033c4f2c7763f1716d269c8)
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/911

Update breadcrumbs to support unit details

---

src/components/PanelHeader/PanelHeader.tsx
src/components/RadioInputBox/RadioInputBox.tsx
src/components/RadioInputBox/_radio-input-box.scss
src/juju/index.js
src/pages/EntityDetails/App/App.js
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/_actions-panel.scss
src/panels/RegisterController/RegisterController.js

- Populate the action list with real action data.
- Clicking on the radio opens the description
- Pull code
- `yarn start`
- Open `config.js` and change `showActionsPanel` to `true`.
- View a charm with actions (I've been using `ceph`)
- Click one of them, the description will open (clicking others will just open more of them, this will be addressed in a follow-up)
Fixes: https://github.com/canonical-web-and-design/juju-squad/issues/1662

Populate actions list with real data

---

src/hooks/useTableRowClick.tsx
src/pages/EntityDetails/Machine/Machine.js

Fix the unit row click from machines
**Driveby**, update the empty table message in the machines view
- Pull code
- Click into an model -> app -> unit -> machine -> unit
- Check at all stages the breadcrumb and URL is correct.
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/917

Fix the unit row click from machines

---

src/components/NotFound/NotFound.test.tsx
src/components/NotFound/NotFound.tsx
src/components/Routes/Routes.tsx
src/pages/PageNotFound/PageNotFound.js
src/pages/PageNotFound/PageNotFound.test.js

Split out NotFound component to enable this component to be reused in the EntityDetails template if a model cannot be found  
- Pull code
- Verify nothing breaks
Related #906

Split out NotFound component

---

src/animations/SlideInOut.tsx
src/components/Aside/Aside.tsx
src/components/Aside/_aside.scss
src/layout/BaseLayout/_base-layout.scss

- Horizontal scroll bars no longer appear when aside panels animate in.
- Removed fudge values to position panel content in aside panels.
- Fixed animation so that it animated the aside and not the panel.
- Pull code
- Click to open the register controller panel, it should animate in smoothly with a drop shadow and no scrollbar appearing for the app.
- You can also use the Actions panel if you have a model with actions.
Fixes: https://github.com/canonical-web-and-design/jaas-dashboard/issues/880

Fix aside styling and animations

---

src/components/RadioInputBox/DescriptionSummary.test.js
src/components/RadioInputBox/DescriptionSummary.tsx
src/components/RadioInputBox/RadioInputBox.tsx
src/components/RadioInputBox/__snapshots__/DescriptionSummary.test.js.snap
src/components/RadioInputBox/_radio-input-box.scss
src/panels/ActionsPanel/ActionsPanel.tsx

The actions list is now styled to match the designs.
- Selecting an action opens the actions option list (if one exists)
- If an option description is longer than 30 characters it'll be collapsed and allow for expansion.
Note:
It's still not functional - this is purely UI interactivity. Because of this the functionality tests are going to come in the follow-up branch which hooks this up to the API.
- Pull code
- View a charm with actions, select an action and see the available interactions
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1663

Add interactivity to selecting an action in the Actions panel

---

src/components/EntityInfo/_entity-info.scss

Wrap content in the entity panel if info is too long
- Open the demo
- Go to a unit details
- Check the version to a very long string such as the screenshot and see the word wraps
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/952
| Before | After |
| --- | --- |
| ![Image Pasted at 2021-4-13 13-45](https://user-images.githubusercontent.com/1413534/114575547-2ff93c80-9c72-11eb-9b09-0766dc04a5b3.png) | ![Image Pasted at 2021-4-13 13-48](https://user-images.githubusercontent.com/1413534/114575627-456e6680-9c72-11eb-98e8-fdd90b52bb01.png) |

Wrap content in the entity panel if info is too long

---

src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Model/Model.js
src/pages/EntityDetails/Unit/Unit.js

Add the provider type of the model to all entity info panels. So it is clear which provider you are using at all depths.
- Open https://jaas-dashboard-951.demos.haus
- Go to a model details page and see the provider info in the info panel
- Go to a app details page and see the provider info in the info panel
- Go to a unit details page and see the provider info in the info panel
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1722
Model details:
App details:
Unit details:

Indicate the provider type throughout entity details

---

package.json
src/app/utils/utils.js
src/tables/tableRows.js

Fetch charm icon from charmhub for charms deployed from there.
- In the demo icons should be rendered as expected.
- Bootstrap your own controller with Juju 2.9 
- Point the dashboard to it using [these instructions](https://github.com/canonical-web-and-design/jaas-dashboard#developing-while-connected-to-a-juju-controller)
Fixes #972

Fetch charm icon from charmhub for charms deployed from there

---

package.json
src/app/selectors.js
src/app/utils/utils.js
src/app/utils/utils.test.js
src/components/Aside/Aside.tsx
src/components/Aside/_aside.scss
src/pages/EntityDetails/Model/Model.js
src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss
src/panels/panels.tsx
yarn.lock

Add Sharing panel to model detail pages, showing who a model has already been shared with.
- Pull code
- Click on a model 
- Click on 'Share model' under the topology
- Verify the share model panel opens and lists the users the model has been shared with
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1737,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1739

Add Sharing panel to model detail pages

---

src/app/utils/utils.js
src/pages/EntityDetails/App/App.test.js
src/pages/EntityDetails/App/App.tsx
src/tables/tableRows.js

Add an empty column to a subordinate unit table
Also drive by, to update the empty unit table message to be application now model.
- Open the demo
- Go to a model with a subordinate (hadoopspark(gomboli) > slave)
- Check the subordinate columns now align correctly
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1765

Add an empty column to a subordinate unit table

---

package.json
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.js
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx

If the action logs contains applications that are no longer in the model then fail gracefully by only rendering the application name.
- Contact me for access to a test model.... or...
- Create a new model and `juju deploy cs:ceph-mon`.
- Run a simple action like `get-health`.
- View the action logs page.
- `juju remove-application ceph-mon`
- View the action logs page.
- It shouldn't 💥 
Fixes #1020 
Without application data:
With application data:

Fail gracefully when action logs includes missing applications

---

src/components/UserMenu/_user-menu.scss
src/layout/BaseLayout/BaseLayout.test.tsx
src/layout/BaseLayout/BaseLayout.tsx
src/layout/BaseLayout/_base-layout.scss
src/scss/_settings.scss

- Collapse user menu when active if side nav collapses
- Remove some redundant code related to old external menu in side nav which was removed months ago
- Pull code
- Open user menu
- Go to model details view
- See that menu has collapsed
- Hover side nav
- Menu should expand until closed or you hover away
Fixes #985

Collapse user menu when active if side nav collapses

---

src/animations/SlideDownFadeOut.tsx
src/components/ShareCard/ShareCard.test.tsx
src/components/ShareCard/ShareCard.tsx
src/components/ShareCard/_share-card.scss
src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss

Add focus state and simple animations to sharing cards
- Pull code
- Add and remove sharing access to users of a model
- Click the select box to change their access to see focus states
Related: https://github.com/canonical-web-and-design/juju-squad/issues/1746

Add focus state and simple animations to sharing cards

---

src/layout/BaseLayout/BaseLayout.test.tsx
src/layout/BaseLayout/BaseLayout.tsx

Revert removal of mobile menu toggle and rename it to improve clarity of its purpose.
- Pull code
- Ensure side nav collapses on small screens
Fixes #1041

Revert removal of mobile navigation bar

---

src/components/WebCLI/WebCLI.js
src/components/WebCLI/WebCLI.test.js
src/components/WebCLI/__snapshots__/WebCLI.test.js.snap

The URL paths changed in the Juju documentation so this updates the link to the new path.
- Bootstrap a new controller using Juju 2.9+ `juju bootstrap aws`
- Run `juju dashboard` and then view, in Firefox, the displayed link (accepting the ssl cert warning) 
- Follow these [instructions](https://github.com/canonical-web-and-design/jaas-dashboard#developing-while-connected-to-a-juju-controller) to configure the dashboard
- Check that the webCLI description link works as expected.
Fixes #1028

Update webCLI documentation link.

---

Dockerfile

It appears that Vanilla now required Node v16 to build successfully. This updates the docker image from 14 to 16 in hopes of resolving the build issue in the Vanilla upgrade.
- The app should continue to build and work as expected.

Update to Node v16.x

---

src/components/Aside/_aside.scss
src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss

Sharing view toggles on small screens
- Pull code
- Decrease screen width to 500px wide
- Go to a model
- Click the sharing panel
- Verify that 'Add new user' button appears
- Click it.. to see form
- Verify that 'Back' button appears
- Click it to return to the sharing cards
Fixes #1046

Sharing view toggles on small screens

---

src/components/ToastCard/ToastCard.test.tsx
src/components/ToastCard/ToastCard.tsx
src/components/ToastCard/_toast-card.scss
src/juju/index.js
src/panels/ShareModelPanel/ShareModel.tsx

Add undo action to remove share user toasts
- Pull code
- Click through to a model
- Click the share link in the info panel
- Delete an existing user
- Verify their card disappears and confirmation toast appears with an 'Undo' link
- Click the 'Undo' link
- Their card should reinstate
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1743

Add undo action to remove share user toasts

---

src/pages/EntityDetails/Model/Model.js
src/pages/EntityDetails/Model/Model.test.js

Update button text from 'Share model' to 'Model access'
- Pull code
- Go to a model
- Verify button text under info panel is updated
Fixes #1036

Update button text from 'Share model' to 'Model access'

---

src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss

Improve specificity of button to show sharing close panel
- Pull code
- See sharing panel close button is working again
Fixes https://app.zenhub.com/workspaces/-app-squad-60910956c649200013c0a571/issues/canonical-web-and-design/juju-squad/1777

Improve specificity of button to show sharing close panel

---

src/panels/ShareModelPanel/share-model.scss

Before: 
After:
- Pull code
- Verify button fixed on mobile as above

Fix alignment button on mobile share button

---

src/app/utils/utils.js
src/app/utils/utils.test.js
src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/CloudGroup.test.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/OwnerGroup.test.js
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/StatusGroup.test.js
src/components/ModelTableList/_model-table-list.scss
src/hooks/useActiveUser.tsx
src/pages/EntityDetails/Model/Model.js

Restrict model index visibility to Access button on row hover
- Pull code
- Verify you can only open the access panel for those models you have the correct permissions for
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1779

Restrict model index visibility to Access button on row hover

---

src/panels/ShareModelPanel/ShareModel.tsx

Ensure owner share card always appears first
- Pull code
- Open share panel
- Add a new user which becomes alphabetically before the owner username
- Ensure owner card stays at the top of the list
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1775

Ensure owner share card always appears first

---

src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss

Return to share list when adding new user on mobile
- Pull code
- Open http://0.0.0.0:8036/models on a small screen
- Click into a model you have sharing permissions on
- Click 'model access'
- Click 'add new user'
- Add a user
- Verify you are returned to the share list
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1776

Return to share list when adding new user on mobile

---

src/juju/index.js
src/panels/ShareModelPanel/ShareModel.tsx

Improve share error handling
- Pull code
- Register a dud controller
- Try to add/remove/amend users in model share menu
- Verify that error toast appears

Improve share error handling

---

src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss

Remove the redefinition of the icon mixin
Moved the icon within the heading so to remove the positioning styling
- Check out the demo
- Go to a model and open the share panel
- See that the heading and icon look the same as they did before

Refactor the icon in the sharing heading

---

src/juju/index.js
src/pages/EntityDetails/Model/Model.js

When viewing a model details page connect to the all model watcher.
When leaving the model details page, stop and disconnect from the all model watcher.
This is step 1 of many to convert this page from using the timer based poller to the watcher for displaying model data.
- View a model details page and then inspect the network tab, it should connect to the watcher and disconnect upon leaving.
Fixes: https://github.com/canonical-web-and-design/juju-squad/issues/1542

Connect to the all model watcher when viewing a model details page 

---

src/app/utils/utils.js
src/components/WebCLI/WebCLI.js
src/components/WebCLI/WebCLI.test.js
src/juju/model-selectors.ts
src/juju/reducer.js
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/Machine/Machine.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/tables/tableRows.js

- The all watcher doesn't contain an app status so we have to generate an aggregate app status from parsing the units.
- Remove the `refreshModel` call as a driveby from the webCLI as it's no longer needed now that the model details page uses the watcher data.
- Contact me for access to a model to QA this with.
- It should show the application status on the Application list, Machine details page, Unit details page.

Generate the app status from an aggregate of the unit statuses

---

src/index.js

Added support for relative controller API endpoint paths. This is necessary because the charm can provide a relative path when it's proxying the connections to the same host. This allows the dashboard to connect to the correct endpoint even when we don't know the ultimate endpoint of the proxy.
- The app should continue to work as expected.

Add support for relative controller api endpoint paths.

---

src/components/WebCLI/WebCLI.js

If the WebCLI component isn't passed the necessary data to contruct the websocket address then do not try and render the WebCLI. This is a bandaid for the root cause, which can be seen in #1170.
- Contact me to get access to a known broken model.
- View the demo link and view the model details, the app shouldn't 💥 .

gracefully fail if the web cli is not passed the necessary data to construct the websocket address.

---

.circleci/config.yml

The dev image that we've been using is pretty out of date, we're going to move towards using the circle ci images when appropriate across the projects so this one updates to the LTS version of node.
- CI should pass

Update the docker image to the node LTS from circle CI

---

package.json
public/config.js.go
src/index.js

Add back in support for Juju 2.9. There appears to have been a commit missing, possibly a bad merge that removed the config files and support for Juju 2.9.
Fixes #1196

added back in support for Juju 2.9.

---

src/app/utils/utils.js
src/app/utils/utils.test.js

If loading a `cs:` charm. Parse and generate the charmhub icon URL to load the image from 
- Pull code
- Open http://localhost:3001/
- Go to a model and see the icons load from charmhub.io
- _Not that etcd is not in charmhub and so will 404_
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/1210

Parse and load the cs: icons from charmhub

---

renovate.json

- Revert https://github.com/canonical/jaas-dashboard/pull/1224 so that we get more frequent updates (renovate was changed while this project wasn't getting a lot of attention).
- I made one change to the config which is to change the schedule from weekly to monthly (I thought it could be worth trying that cadence for a while).
n/a

Revert renovate config

---

src/app/utils/utils.js
src/components/Topology/Topology.js

- use fallback charm icon on img load error
Fixes: https://github.com/canonical-web-and-design/jaas-dashboard/issues/1230
- Pull code
- Verify that any images that fail to load use the default icon as a fallback 

feat: use fallback charm icon on img error

---

package.json
yarn.lock

- Update the bakery dep to 1.2.2. This release bundles the crypto libs in preparation for Webpack 5 (which does not polyfill node modules).
- Pull code
- Check that you can log in.
Fixes: #1246.

Upgrade bakery dependency.

---

src/juju/index.js
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.js
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/ActionLogs/_action-logs.scss
src/testing/list-actions-api-response.json

- Show the output of the message
- Add the ability to filter the logs by `stderr`, `stdout` or both
- Add a button maybe in `controls`, that will show the payload of `set_results` 
- Run the dashboard locally
- Open http://0.0.0.0:3000/
- Run a charm that has an action with logs, you can run this one (for some reason this charm successful action fail on juju 3.0 beta4): https://github.com/goulinkh/qa-juju-charm
- Make sure that the logs are present in the dashboard and match the defined behavior in [Figma](https://www.figma.com/file/u9v1jvPc3TwlfwHSWsysn9/JAAS-Baseline?node-id=530%3A38081)
Fixes #1199, #1035

Get missing action logs

---

package.json
src/juju/index.js
yarn.lock

- Update the package `jujulib` to add support for Juju 3.0
- Run the Juju dashboard proxy: `juju dashboard`
- Add a new file at `public/config.local.js`:
```js
var jujuDashboardConfig = {
controllerAPIEndpoint: "ws(s)://<your-dashboard-host:port>/api",
baseAppURL: "/",
identityProviderAvailable: false,
identityProviderURL: "",
isJuju: true,
};
```
- Run the dashboard locally: `yarn install && yarn start`
- Make sure that you can see the list of models
Fixes #1274

add support for juju 3.0 beta4

---

Dockerfile

- Added `/` to the end of ADD path to appease `docker build`
```
DOCKER_BUILDKIT=1 docker build .
```
`docker build` was failing with the following error:
```
Step 3/14 : ADD package.json yarn.lock .
When using ADD with more than one source file, the destination must be a directory and end with a /
```
This PR simply adds a `/` to the end of the destination path.

[Dockerfile] append `/` to ADD path

---

.env
.github/workflows/actions.yml
README.md
src/components/ButtonGroup/_button-group.scss

- Set the correct port for dotrun.
- Pull code
- Run `dotrun`
- The UI should appear at the correct port.

WD-145 - Set the correct port

---

src/app/actions.js
src/app/root.js
src/app/selectors.js
src/components/WebCLI/WebCLI.test.js
src/juju/index.js
src/pages/EntityDetails/Model/Model.test.tsx
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/complete-redux-store-dump.js

- Remove controller connection (e.g. transport, facades) from the Redux store.
- Pull code
- Check that you can log in/out and view models and controllers.

WD-654: Only store controller info in Redux

---

src/app/actions.js
src/app/root.js
src/app/selectors.js
src/components/LogIn/LogIn.tsx
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/complete-redux-store-dump.js

- Remove juju connections from the redux store.
- Store connections in the middleware.
- Handle logging out of models.
- Pull code
- Open your dev tools network tab and filter by the websocket connections.
- You should see a websocket for each model.
- In the sidebar click your name and then logout.
- Each of the model websockets should close.
Fixes: https://warthogs.atlassian.net/browse/WD-591

WD-591 - Remove juju connections from the redux store

---

src/@canonical/macaroon-bakery.d.ts
src/app/action-types.ts
src/app/actions.js
src/app/bakery.ts
src/app/check-auth.js
src/app/root.js
src/app/selectors.js
src/components/LogIn/LogIn.tsx
src/components/WebCLI/WebCLI.js
src/components/WebCLI/WebCLI.test.js
src/index.js
src/juju/action-types.ts
src/juju/actions.js
src/juju/actions.test.js
src/juju/index.js
src/juju/reducer.js
src/panels/RegisterController/RegisterController.js
src/setupTests.js
src/store/index.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/store/store.ts
src/testing/complete-redux-store-dump.js

- Move bakery to a separate file.
- Replace selectors and reducers with bakery import.
- Update tests to use the new bakery setup.
- Pull code
- Check that you can still log in/out and display models.

WD-481 Store and fetch the bakery outside of the Redux store

---

package.json
src/@canonical/macaroon-bakery.d.ts
src/app/bakery.ts
src/store/middleware/model-poller.ts
yarn.lock

- Upgrade bakeryjs to 1.3.0.
- Remove placeholder definition file.
- Remove types that are now provided by bakeryjs.
- Pull code
- Check that the UI loads as normal.
Fixes: https://warthogs.atlassian.net/browse/WD-877

WD-877 - Upgrade to bakeryjs 1.3.0.

---

src/app/utils/utils.js
src/components/ButtonGroup/_button-group.scss
src/pages/EntityDetails/_entity-details.scss
src/tables/tableHeaders.tsx
src/tables/tableRows.js

- Truncate the machine status column on small screens.
- Go to a model -> Machines tab.
- On a large screen the status column should not be truncated.
- On a small screen the status column should truncate and you should be able to see the full status with a tooltip.
Fixes: #530.

Truncate the machine status column

---

src/app/action-types.ts
src/app/actions.js
src/juju/api.ts
src/panels/ShareModelPanel/ShareModel.tsx
src/store/middleware/check-auth.js
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/store/store.ts

Support updating model permissions in the model poller middleware.
- Pull code
- Open the list of models.
- Click the "Access" button for one of the models.
- Enter a username for a real user and click "Add user" and you should get a notification that the user was added and they should appear in the list of users.
- Now enter an incorrect username and click "Add user" and you should get an error.
[WD-922]: https://warthogs.atlassian.net/browse/WD-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-922 - Handle updating model permissions

---

package.json
src/juju/api.ts
src/pages/ModelDetails/ModelDetails.tsx
src/store/general/reducers.test.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/general/types.ts
src/store/juju/types.ts
src/store/middleware/model-poller.ts
yarn.lock

- Upgrade jujulib to 3.1.0
- Replace local types with newly exposed types from jujulib.
- Pull code
- Check that you can still list controllers and models as before.

Upgrade jujulib

---

src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/ModelTableList.test.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/components/PrimaryNav/PrimaryNav.test.tsx
src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/ControllersIndex/__snapshots__/ControllersIndex.test.tsx.snap
src/pages/ModelsIndex/ModelsIndex.test.tsx
src/store/app/thunks.test.ts
src/store/juju/reducers.test.ts
src/store/juju/thunks.test.ts
src/store/middleware/model-poller.test.ts
src/testing/complete-redux-store-dump.js
src/testing/factories/juju/juju.ts

- Add controller factories.
- Update tests to use factories instead of data dump.
- Removed unused test data.
https://warthogs.atlassian.net/browse/WD-2030

WD-2030 - Replace controller test data with factories

---

src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/store/app/thunks.test.ts
src/store/app/thunks.ts
src/store/general/actions.test.ts
src/store/general/reducers.test.ts
src/store/general/slice.ts
src/store/middleware/check-auth.ts

- Fix logout so that login reappears.
- Clean up login errors.
- Pull code
- Log out.
- Enter some incorrect credentials and submit the form.
- You should see login errors.
- Enter correct credentials and submit. You should get logged in.
- Click the logout link in the sidebar.
- You should see the login form and there shouldn't be any errors shown.
#1353.

Fix logout

---

src/components/RadioInputBox/OptionInputs.test.tsx
src/components/RadioInputBox/OptionInputs.tsx
src/panels/ActionsPanel/ActionsPanel.test.tsx
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx

- Support boolean action options.
- Pull code
- Deploy and app that has boolean action options e.g. ceph-osd.
- Navigate to the unit list for that app and tick some units.
- Click 'Run action' and choose one of the actions that has a boolean option.
- Check that the boolean option has a checkbox instead of a text field.
#1204.
https://warthogs.atlassian.net/browse/WD-2356

WD-2356 - Support boolean action options

---

src/pages/ModelsIndex/ModelsIndex.test.tsx
src/pages/ModelsIndex/ModelsIndex.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts

- Correctly check for models so that the no models message doesn't appear while loading.
- Pull code
- Go to the models list and refresh the page.
- While the models are loading you shouldn't see a "no models found" message.
Fixes: #1389.
https://warthogs.atlassian.net/browse/WD-2350

WD-2350 - Fix "no models" appearing while loading

---

public/config.js
public/config.js.go
src/index.tsx

- Validate and display controller endpoint configuration errors.
- Pull code
- Change the value of controllerAPIEndpoint in your config.local.js to an invalid address (e.g. remove the /api or the wss://) and reload the dashboard.
- You should see an error message.
Fixes: #1237.
https://warthogs.atlassian.net/browse/WD-2351

WD-2351- Display controller endpoint configuration errors.

---

src/components/WebCLI/Output.js
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/components/WebCLI/_webcli.scss

- Show help when console is expanded.
- Fix console focus colour.
- Pull code
- Click on a model (you'll need to be using a local Juju 2.9).
- Click on the command field at the bottom and type in some text. It should remain black and the text should be white (it got broken by the Vanilla update and the field would turn white).
- Drag open the terminal and you should see the welcome message.
- Enter in a command (e.g. `help`) and the welcome message should disappear.
Fixes: #1281.
https://warthogs.atlassian.net/browse/WD-2349

WD-2349 - Default CLI help

---

src/components/WebCLI/_webcli.scss
src/layout/BaseLayout/_base-layout.scss
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/scss/_variables.scss

- Compensate for WebCLI at bottom of content.
- Pull code
- Go to a model that has a lot of apps (e.g. openstack).
- Check that you can scroll to the bottom of the content and nothing is cut off by the CLI.
Fixes: 1395.
https://warthogs.atlassian.net/browse/WD-2410
Bottom space without CLI:
Bottom space with CLI:

WD-2410 - Compensate for WebCLI

---

src/pages/EntityDetails/Machine/Machine.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/tables/tableHeaders.tsx

Use the correct plural for the local app on a unit.
- Pull code
- Visit the applications list for a model and check that the title of the first column in the apps table is "Local apps".
- Click on an app and then click on a unit and check that the title of the first column in the apps table is "Local app".
- Click on a machine and check that the title of the first column in the apps table is "Local apps".
Fixes: #937.
https://warthogs.atlassian.net/browse/
Apps:
Unit:
Machine:

WD-2427 - Unit local app title

---

src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx

Display action log dates of 0001-01-01T00:00:00Z as Unknown.
- Pull code
- Run some actions that return dates as 0001-01-01T00:00:00Z (I don't actually know which ones do this but it seems to happen frequently).
- Go to the action log and you should see the date as "Unknown".
#1351
https://warthogs.atlassian.net/browse/WD-2424
Before:
After:

WD-2424 - Display unknown action log dates

---

src/components/utils.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/ActionLogs/_action-logs.scss

- Only show the "show action payload" when the action returns a payload
- Show the payload in a modal with "copy to clipboard' button
- Pull code
- Run an action that returns a payload (charm in the screenshots [qa-test](https://github1s.com/goulinkh/qa-juju-charm)), inside the payload handler this line is called:
```py
event.set_results({"key": "value"})
```
- Make sure that there is another button shown in the actions logs
- Click on that button
- Make sure that the action payload is shown in a modal
https://github.com/canonical/jaas-dashboard/issues/1277
https://warthogs.atlassian.net/browse/WD-2423

Show action payload in details

---

src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/_config-panel.scss

- Only truncate the config panel title when the reset button is visible.
- Pull code
Fixes: #1408.
https://warthogs.atlassian.net/browse/WD-2514

WD-2514 - Fix config title truncation

---

src/panels/ShareModelPanel/ShareModel.tsx

- Add help about admins executing actions.
- Pull code
- Open the access panel for a model.
- Under the admin option it should mention that admins can execute actions.
https://warthogs.atlassian.net/browse/WD-2457
Fixes: #1037.

WD-2457 - Add help about admins executing actions

---

src/juju/api.ts
src/store/juju/thunks.ts
src/store/middleware/check-auth.ts

- Fix the controller list to display the controller region and cloud instead of "unknown."
- Run the dashboard against a local controller (i.e. not JAAS).
- Go to the controller list and check that the cloud and region are displayed.
Fixes: #1087.
https://warthogs.atlassian.net/browse/WD-2425

WD-2425 - Display the controller region and cloud

---

src/components/Header/_header.scss
src/components/SlidePanel/_slide-panel.scss
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/_config-panel.scss
src/scss/_variables.scss

- Fix the config panel so that it scrolls if there are too many config options to appear on the screen.
- Pull code
- Go to an app that has a lot of config options and click the 'Configure' button to show the panel.
- Check that you can scroll down to see all the options.
- Check that the panel for an app with a small number of options does not scroll.
Fixes: #1407.
https://warthogs.atlassian.net/browse/WD-2458

WD-2458 - Fix config panel scrolling

---

src/juju/api.ts
src/panels/ConfigPanel/BooleanConfig.tsx
src/panels/ConfigPanel/ConfigField.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/NumberConfig.tsx

- Display config API errors
- Dedupe config field shared code.
- Add number field.
- Pull code
- Open the config panel for an app with a number config and check that it appears as a number field and that you can't input text.
- The easiest way to get a config error seems to be to inspect a number input and change its type to text and then enter in some non number characters. Save the form and it should display the errors at the top of the form.
Fixes: #849.
https://warthogs.atlassian.net/browse/WD-2459

WD-2459 - config errors and validation

---

src/pages/ControllersIndex/_controllers.scss

Remove custom th spacing for controllers so that the header spacing is the same as models.
- Pull code
- Go to the controller list and check that the spacing between the table header and border is the same as the model list.
Fixes: #695.
https://warthogs.atlassian.net/browse/WD-2456

WD-2456 - Remove custom th spacing for controllers

---

src/components/WebCLI/Output.tsx
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/_webcli.scss
src/layout/BaseLayout/_base-layout.scss
src/scss/_variables.scss

- Migrate the output component to TypeScript.
- Update the mobile CLI drag to use the correct event names and also make the hit area larger so that it's not covered by the larger input hit area.
- Pull code
- Navigate to a model (needs to be a local controller so the CLI appears).
- With your browser set to desktop width check that you can resize the CLI output.
- Resize down to tablet or mobile size.
- Open the dev tools and turn on device simulation (the little mobile/tablet icon).
- Check that you can resize the CLI output.

Fix resizing the CLI on mobile

---

src/panels/ShareModelPanel/ShareModel.tsx

- Move the actions help to 'write' instead of 'admin'.
- Pull code
- Open the access panel for a model.
- Under the **write** option (instead of admin) it should have the help about executing actions.
Fixes: #1037.

Fix the actions help

---

src/scss/custom/_tables.scss
src/tables/tableRows.tsx

- Update the unit list with a hover button to copy the address.
- Pull code
- Navigate to an application that has units with exposed IPs.
- Hover an IP address and you should see a copy button. Click the button and the address should get copied.
Fixes: #725.
https://warthogs.atlassian.net/browse/WD-2409

WD-2409- Display copy button for ip addresses

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/pages/ControllersIndex/ControllersIndex.test.tsx

- Show an warning icon when a new version of the dashboard is available
- Pull code
- Change the version in the `package.json` to an old version
- Make sure that there is a warning icon in the nav bar
https://warthogs.atlassian.net/browse/WD-2529

Show dashboard notification update icon

---

src/components/ButtonGroup/ButtonGroup.test.tsx
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/_button-group.scss
src/pages/ModelsIndex/ModelsIndex.tsx
src/pages/ModelsIndex/_models.scss

- Fix the header at all sizes.
- Pull code
- Go to the model list.
- Resize your window down to mobile and check that the header doesn't break at any size.
- Resize your viewport to exactly 1036px and check that it doesn't break like the following screenshot:
Fixes: #974.
https://warthogs.atlassian.net/browse/WD-2640

WD-2640 - Fix resizing the header

---

src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx

- Revoke all permissions when removing a user from a model.
- Pull code
- Add a user to a model with write or admin permissions.
- Go to the access panel for that model and click the delete button to remove the user.
- Refresh the window and check that the user does not reappear with permissions one level lower than their previous.
Fixes: #1038.
https://warthogs.atlassian.net/browse/WD-2639

WD-2639 - Fix revoking permissions

---

src/components/ModelTableList/StatusGroup.test.tsx
src/components/ModelTableList/StatusGroup.tsx
src/scss/_utils.scss
src/store/juju/utils/models.test.ts
src/store/juju/utils/models.ts

- Add links to apps/units with errors.
- Migrate StatusGroup to TypeScript.
- Pull code
- You'll need some units/apps in error (you could try changing the config options for an app to something invalid).
- Go to the model list and you should see the error in red under the model name.
- Hovering the error should show all the errors and clicking them should take you to the appropriate app/unit.
Fixes: #598.
https://warthogs.atlassian.net/browse/WD-2612

WD-2612 - Add links to apps/units with errors

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx

- Fix lockup caused by API call on each render.
- Pull code
- Load the dashboard.
- Make sure that you can interact with the dashboard and that it doesn't lock up almost immediately.
https://warthogs.atlassian.net/browse/WD-2663

WD-2663 - Fix lockup

---

src/components/Breadcrumb/Breadcrumb.tsx
src/components/hooks.test.tsx
src/components/hooks.ts
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/_entity-details.scss

- Give the breadcrumbs the full width of the header.
- Pull code
- Go to an app, unit or machine details page and the breadcrumb should not be squashed to the left.
https://warthogs.atlassian.net/browse/WD-2669
Fixes: #1419.

WD-2669 - Fix breadcrumbs width

---

src/index.test.tsx
src/index.tsx

- Handle absolute controller API urls.
- Add validation tests.
- Pull code
- Set your `controllerAPIEndpoint` in your config.js to an absolute path (e.g. /api) and load the dashboard.
- There should not be any configuration errors displayed.
https://warthogs.atlassian.net/browse/WD-2688

WD-2688 - Handle absolute controller API urls

---

src/components/InfoPanel/_info-panel.scss
src/components/Topology/Topology.tsx

- Fix the size of the topology on mobile.
- Disable the full width button (it's already full width).
- Pull code
- Resize your window down just until the model image goes full width.
- Click the 'Model access' button and then close the panel (this creates a state update).
- The icons should be the same size as before (it used to make them all tiny).
- Check that there is no full screen button (kind of a "[ ]" icon in the bottom left of the image).
https://warthogs.atlassian.net/browse/WD-2759
Fixes: #858.
Fixes: #859.

WD-2759 - Fix the size of the topology on mobile

---

src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx

- Add history to the WebCLI.
- Pull code
- Using a local controller go to a model details page.
- Using the CLI at the bottom enter a few commands.
- Press the up and down arrows and you should be able to navigate through your history.
- Refresh the page and you should still be able to navigate through your history.
https://warthogs.atlassian.net/browse/WD-2757
Fixes: #724.

WD-2757- WebCLI history

---

src/components/Topology/Topology.tsx

- Prevent unnecessary topology rerenders.
- Pull code
- Using chrome go to a model details page.
- Click on the header tabs and check that each tab change doesn't result in the topology being rerendered (it used to very obviously redraw the icons).
Fixes: #430.
https://warthogs.atlassian.net/browse/WD-2808

WD-2808 - Prevent unnecessary topology rerenders

---

src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Machine/Machine.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/pages/ModelDetails/ModelDetails.tsx

- Refactor EntityDetails so it wraps subroutes.
- Pull code
- Check that the search box is only visible for the applications tab.
- Check that you can navigate to unit/machine/app details and that the tabs disappear and the breadcrumbs appear.
https://warthogs.atlassian.net/browse/WD-2831
Fixes: #959.

WD-2831 - Refactor EntityDetails

---

src/pages/EntityDetails/Model/Model.tsx
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts

- Display model access level on the model details page.
- Pull code
- Go to the model details page for a model that you have been explicitly granted access to and you should see the correct access level in the sidebar.
- Go to a model where you haven't been granted access but you're a controller superuser and you should see "superuser" in the sidebar.
Fixes: #710.
https://warthogs.atlassian.net/browse/WD-2910

WD-2910 - Display model access

---

src/components/InfoPanel/_info-panel.scss
src/components/ModelTableList/StatusGroup.tsx
src/components/Topology/Topology.tsx
src/layout/BaseLayout/_base-layout.scss
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/_entity-details.scss
src/scss/_vanilla-overrides.scss

- Make the entity details sidebar sticky.
- A bunch of small drive-by fixes which were discovered while working on this change.
- Pull code
- Go to a model details page that has longer content than the details sidebar (you might need to add a lot of applications or run a lot of actions).
- Resize your window so that the content doesn't fit on the screen.
- Scroll the content and the details sidebar should not scroll unless it doesn't fit on the screen.
- Try different screen sizes and browsers and check that something hasn't broken.
https://warthogs.atlassian.net/browse/WD-2857
Fixes: #517.

WD-2857 - Sticky entity details sidebar

---

src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts

- Add help for usernames.
- Add suggestions from previously used usernames.
- Pull code
- Open the access panel for a model.
- You should see help below the username field with instructions on the username format.
- You should also see suggestions about domains that are in use on your models (if there are are any - if not add some external users and they should get added to the list).
- Enter in a username without the domain and click a domain and it should get appended to the username.
https://warthogs.atlassian.net/browse/WD-2929
Fixes: #1052.

WD-2929 - Add help for usernames

---

package.json
src/components/ModelTableList/OwnerGroup.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/ShareCard/ShareCard.tsx
src/components/ShareCard/_share-card.scss
src/components/TruncatedTooltip/TruncatedTooltip.test.tsx
src/components/TruncatedTooltip/TruncatedTooltip.tsx
src/components/TruncatedTooltip/_truncated-tooltip.scss
src/components/TruncatedTooltip/index.ts
src/components/utils.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
src/pages/EntityDetails/_entity-details.scss
src/scss/_utils.scss
src/tables/tableRows.tsx
yarn.lock

- Make tooltips only appear if content is truncated.
- Turn urls into links in messages.
- Pull code
- Have a look through the tables. Any columns with long content should get truncated.
- Columns that aren't truncated shouldn't show tooltips.
- Columns with urls in them should get turned into links (e.g. status messages - though I couldn't find a real status message with a URL in it).
https://warthogs.atlassian.net/browse/WD-2985
Fixes: #973.
Fixes: #531.
Fixes: #508.

WD-2985 - Improve tooltips

---

src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/ControllersIndex/__snapshots__/ControllersIndex.test.tsx.snap
src/store/juju/utils/controllers.test.ts
src/store/juju/utils/controllers.ts

- Handle the cloud/region column for JAAS.
- Pull code
- Connect to JAAS.
- Go to the list of controllers.
- In the cloud/region column it should say "Multiple" for the JAAS row.
https://warthogs.atlassian.net/browse/WD-3058
Fixes: #629.

WD-3058 - Handle the cloud/region column for JAAS.

---

src/components/DivButton/DivButton.test.tsx
src/components/DivButton/DivButton.tsx
src/components/DivButton/_div-button.scss
src/components/DivButton/index.ts
src/panels/ConfigPanel/ConfigField.tsx
src/panels/ConfigPanel/TextAreaConfig.tsx
src/panels/ConfigPanel/_config-panel.scss

- Fixed extra tab over hidden config buttons.
- Improved accessibility of config items.
- Pull code
- Go to an app and open the config panel.
- Click inside an input.
- Press tab once and the next config item should be highlighted.
- Press enter or space and the help on the right should update.
- Press tab again and (assuming you haven't changed the value from the default) the focus should move to the input.
- Change one of the values so that the 'use default' button appears and check that you can tab to that button.
Fixes: #862.
https://warthogs.atlassian.net/browse/WD-2832

WD-2832 - Fixed extra tab over hidden config buttons

---

package.json
src/juju/api.test.ts
src/juju/api.ts
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/store/juju/slice.ts
src/store/juju/types.ts
src/testing/factories/juju/Application.ts
src/testing/factories/juju/Charms.ts
yarn.lock

- Update libjuju and set client version to support 3.2.
Note: this PR will need to be updated with the latest jujulib once it has been released to NPM (this will also fix CI).
- Set up a juju 3.2 controller.
- Check out the jujulib branch: https://github.com/juju/js-libjuju/pull/110
- in jujulib run `yarn build` and `yarn link`.
- Pull this dashboard branch.
- Run `yarn clean` then `yarn link "@canonical/jujulib"` (I sometimes also need to change the package.json to `"@canonical/jujulib": "link:../js-libjuju",`) then `yarn install`
- Configure your dashboard to point to the 3.2 controller you set up.
- Finally run `yarn start` and load the dashboard in your browser.
- Go to the controllers page and check that the controller(s) appear in the list.
- Go to the model list and click on a …

WD-3492 - Support Juju 3.2

---

src/components/App/App.test.tsx
src/components/App/App.tsx
src/components/ConnectionError/ConnectionError.test.tsx
src/components/ConnectionError/ConnectionError.tsx
src/components/ConnectionError/index.ts
src/juju/api.test.ts
src/juju/api.ts
src/store/general/actions.test.ts
src/store/general/reducers.test.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/general/slice.ts
src/store/general/types.ts
src/store/middleware/check-auth.ts
src/testing/factories/general.ts

- Upgrade libjuju to 3.1.3.
- Handle login timeouts.
- If you're using a local dashboard then make sure you're connected to JAAS (the demo service already is).
- Log out if you're logged in and refresh the page.
- Click "Login to the dashboard" but don't do anything on the new tab that opens.
- Wait for at least a minute (this is just long enough to look out the window and start having an existential crisis).
- Now, ignore any feelings that might lead to good and lasting change in your life, knowing you can substitute them with social media and online shopping, and complete the SSO login.
- Go back to the dashboard and there should be a message: "Could not log into controller".
Fixes: #491.
https://warthogs.atlassian.net/browse/WD-3060

WD-3060 - Handle login timeouts

---

src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.tsx.snap
src/components/PrimaryNav/PrimaryNav.tsx
src/urls.ts

- - Update new issues links to point to new repo URL.
- Pull code
- In the sidebar click the link to report a bug.
- Check that it takes you to the juju-dashboard repo.
https://warthogs.atlassian.net/browse/WD-3994

WD-3994 - Update new issues links

---

CONTRIBUTING.md
HACKING.md
README.md
RELEASING.md

- Fix links pointing to CONTRIBUTING.md, HACKING.md and RELEASING.md in the docs files.
Fixes: #1511 
https://warthogs.atlassian.net/browse/WD-5004

WD-5004 - fix: Broken docs links

---

src/panels/ConfigPanel/_config-panel.scss

- Short panels stretch vertically until the bottom of the page and the buttons appear at the bottom of the page.
Fixes: #1505 
https://warthogs.atlassian.net/browse/WD-5039

WD-5039 - fix: Short panels don't stretch

---

src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.tsx

- Clicking outside action confirmation will close the action confirmation screen
Fixes: #1499 
https://warthogs.atlassian.net/browse/WD-5050

WD-5050 - fix: Clicking outside action confirmation has error

---

package.json
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
yarn.lock

- Sort action logs by default and add sorting to other columns.
- Pull code
- If you don't have any action logs go to a model -> click on an app -> tick some units and click the run action button.
- Go to the model's action logs tab.
- Check that the most recent logs are first.
- Check that you can sort the table using the headers.
Fixes: #1033.
https://warthogs.atlassian.net/browse/WD-2833

WD-2833 - Sort action logs

---

src/components/AuditLogsTable/AuditLogsTable.test.tsx
src/components/AuditLogsTable/AuditLogsTable.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.tsx

- Updated the AuditLogsTable to take a prop to hide the Model column.
- Set the prop to hide the model column on the model level audit logs view.
https://warthogs.atlassian.net/browse/WD-5215

WD-5215 - feat: Hide model column from table in model logs view

---

src/components/LogIn/LogIn.tsx
src/components/Logo/Logo.tsx
src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/Routes/Routes.tsx
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/Logs/Logs.test.tsx
src/pages/EntityDetails/Model/Logs/Logs.tsx
src/store/general/selectors.test.ts
src/store/general/selectors.ts

- Hid audit log views when not using JAAS.
- Add tests.
https://warthogs.atlassian.net/browse/WD-5216
Using JAAS:
Using local controller:

WD-5216 - feat: Hide audit log views when not using JAAS

---

src/components/AuditLogsTable/AuditLogsTable.test.tsx
src/components/AuditLogsTable/AuditLogsTable.tsx

- Added refresh button to AuditLogsTable that re-requests the first page of Audit Logs and navigates to it.
- Not sure where to put the button, so I just left it in the default position. It will most likely be necessary to add some css to move it in the desired position.
https://warthogs.atlassian.net/browse/WD-5223
https://warthogs.atlassian.net/browse/WD-5224

feat: Add refresh button to AuditLogsTable

---

src/juju/api.test.ts
src/juju/api.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts

- Pass audit log params to the API call.
- Open `AuditLogsTable.tsx`.
- Find the line `dispatch(jujuActions.fetchAuditEvents({ wsControllerURL }));` and add `limit: 5` to the object.
- Load the Logs page and the audit logs should only have five entries.

Pass audit log params

---

src/components/AuditLogsTable/AuditLogsTable.tsx
src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.test.tsx
src/components/AuditLogsTable/AuditLogsTableActions/AuditLogsTableActions.tsx
src/components/AuditLogsTable/AuditLogsTableFilters/AuditLogsTableFilters.tsx
src/components/AuditLogsTable/consts.ts
src/components/AuditLogsTable/hooks.test.tsx
src/components/AuditLogsTable/hooks.ts
src/hooks/useQueryParams.test.tsx
src/hooks/useQueryParams.ts
src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.tsx
src/panels/AuditLogsFilterPanel/Fields/Fields.test.tsx
src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/types.ts

- Refetch the audit logs when the filters change.
- Connect to staging.
- Go to the logs page.
- Open the filters panel and enter some filters (note: facade name and version aren't currently supported - I've added a Jira task for this - and the facade method does not appear to be changing anything in the response from the API).
- Click Filter and the logs should reload.
https://warthogs.atlassian.net/browse/WD-5221

WD-5221- Fetch when filters change

---

src/components/AuditLogsTable/AuditLogsTableFilters/AuditLogsTableFilters.tsx
src/components/AuditLogsTable/hooks.test.tsx
src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.test.tsx
src/panels/AuditLogsFilterPanel/AuditLogsFilterPanel.tsx
src/panels/AuditLogsFilterPanel/Fields/Fields.test.tsx
src/panels/AuditLogsFilterPanel/Fields/Fields.tsx
src/panels/AuditLogsFilterPanel/types.ts

- Remove the facade name and version filters as they are not supported by the API.
- Go to the logs page.
- Open the filter panel.
- See that the facade name and version inputs are no longer there.
https://warthogs.atlassian.net/browse/WD-5745

WD-5745 - Remove facade name and version filters

---

src/components/AuditLogsTable/AuditLogsTable.tsx
src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.test.tsx
src/components/AuditLogsTable/AuditLogsTablePagination/AuditLogsTablePagination.tsx

- Fixed pagination navigating to new blank page by temporarily disabling the next page button until the audit logs are fetched.
- _Note: I was unable to reproduce the issue where, if navigating to the next page slowly so that it manages to refresh, we can navigate to a blank page. Maybe it somehow managed to get fixed in the latest pull requests?_
https://warthogs.atlassian.net/browse/WD-5746

WD-5746 - fix: Fix pagination navigating to new blank page

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
src/components/PrimaryNav/PrimaryNavLink/index.ts
src/components/Routes/Routes.tsx
src/pages/AdvancedSearch/AdvancedSearch.test.tsx
src/pages/AdvancedSearch/AdvancedSearch.tsx
src/pages/AdvancedSearch/index.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/urls.ts

- Set up the page component with an “Advanced search“ header.
- Set up a “/search“ URL and route. Route is not accessible when using Juju controller.
- Added an “Advanced search“ link to the sidebar that is not shown when using Juju controller.
https://warthogs.atlassian.net/browse/WD-5811

WD-5811 - feat: Add page component, route and side nav link

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
src/components/PrimaryNav/PrimaryNavLink/index.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts

- Refactored `PrimaryNav` component and added `getIsJuju` selector. This change will make it easier to merge `audit-logs` and `cross-model-queries` branches into `main`.

refactor: Add getIsJuju and refactor PrimaryNav

---

docs/multipass-microk8s.md
src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.test.tsx
src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.tsx
src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/index.ts
src/pages/AdvancedSearch/SearchForm/types.ts
src/scss/index.scss

- Add a history of queries to the cross model search form.
- Connect to staging.
- See that there is a button to open the search history.
- Perform a search.
- Open the menu and you should see the search item.
- Do a second search and open the menu again and click on the first search you did. The URL and input should update.
- Refresh the page and open the menu again and your items should be there again.
- Click the clear button and they should get removed.
https://warthogs.atlassian.net/browse/WD-5815

WD-5815 - Add search history

---

src/pages/AdvancedSearch/SearchForm/QueryLink/QueryLink.test.tsx
src/pages/AdvancedSearch/SearchForm/QueryLink/QueryLink.tsx
src/pages/AdvancedSearch/SearchForm/QueryLink/index.ts
src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
src/pages/AdvancedSearch/SearchForm/SearchHelp/SearchHelp.test.tsx
src/pages/AdvancedSearch/SearchForm/SearchHelp/SearchHelp.tsx
src/pages/AdvancedSearch/SearchForm/SearchHelp/index.ts
src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.test.tsx
src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.tsx
src/pages/AdvancedSearch/SearchForm/_search-form.scss

- Add cross model queries help.
- Check that the help appears next to the form on desktop.
- Resize to mobile and the help should move below the input and the examples should disappear.
https://warthogs.atlassian.net/browse/WD-5814

WD-5814 - Add help

---

src/components/Status/Status.test.tsx
src/components/Status/Status.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
src/pages/AdvancedSearch/ResultsBlock/_results-block.scss
src/scss/custom/_status_icons.scss

- Insert status icons into the JSON tree output.
- Do a search.
- Look through the tree and you should see status icons next to the status values.
https://warthogs.atlassian.net/browse/WD-5823

WD-5823 - Display status icons

---

src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx

- Theme the JSON tree to use Vanilla colours.
- Search for something.
- The tree should use Vanilla colours based on the [syntax highlighting colours](https://vanillaframework.io/docs/base/code#syntax-highlighting).
https://warthogs.atlassian.net/browse/WD-5821

WD-5821 - JSON tree theme

---

src/components/Breadcrumb/Breadcrumb.tsx
src/components/ModelDetailsLink/ModelDetailsLink.test.tsx
src/components/ModelDetailsLink/ModelDetailsLink.tsx
src/components/ModelTableList/ModelSummary/ModelSummary.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
src/pages/AdvancedSearch/ResultsModelLink/ResultsModelLink.test.tsx
src/pages/AdvancedSearch/ResultsModelLink/ResultsModelLink.tsx
src/pages/AdvancedSearch/ResultsModelLink/index.ts
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/urls.ts

- Link keys to the model tabs in the tree view.
- Display `[none]` for empty string keys.
- Go to the advanced search page and do a search.
- Check that various keys such as applications and machines link to the model details tabs (but won't currently load due to the API issues).
- https://warthogs.atlassian.net/browse/WD-5959

WD-5959 - Link keys to the model tabs

---

src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.test.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx

- Link to Charmhub from charms.
- Go to the advanced search page and do a search.
- In the tree open an applications object and then open an app.
- The "charm" value should link to charmhub.io.
https://warthogs.atlassian.net/browse/WD-6052

WD-6052 - Link charms to Charmhub

---

src/components/ModelTableList/ModelDetailsLink/ModelDetailsLink.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/WebCLI/WebCLI.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/store/juju/selectors.ts
src/store/juju/utils/models.ts
src/utils/getUserName.test.ts
src/utils/getUserName.ts

- Add util for getting the username from a tag (originally added in the audit-logs branch: https://github.com/canonical/juju-dashboard/pull/1541).

Tag to username util

---

src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
src/pages/AdvancedSearch/SearchForm/SearchHistoryMenu/SearchHistoryMenu.tsx

- Scroll the history menu if it has too many items to fit on the screen.
- Perform a number of searches so that your history menu is long.
- Resize your screen so that the history menu doesn't fit on the screen.
- The history dropdown should scroll instead of causing the entire app to scroll.
https://warthogs.atlassian.net/browse/WD-6051

WD-6051 - Scroll the history menu

---

src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts

- Display errors from the API.
- Open `jimm-facade.ts` and at the bottom change the version to `JIMMV4.VERSION = 99;`.
- Load the dashboard
- Do a search.
- You should see an error.
https://warthogs.atlassian.net/browse/WD-6094

WD-6094 - Display JIMM errors

---

src/components/AuditLogsTable/hooks.ts
src/juju/jimm/JIMMV3.ts

- Sort audit logs by most recent first.
- Go to the logs page.
- Check that the audit logs appear with most recent first.
https://warthogs.atlassian.net/browse/WD-5786

WD-5786 - Sort by most recent first

---

src/components/Topology/Topology.test.tsx
src/components/Topology/Topology.tsx

- Fix annotation mutations so that the topology gets centred.
- Using a local controller add a model.
- Deploy a bundle that has annotations information e.g. `juju deploy charmed-kubernetes`.
- Load the dashboard.
- Go to the model list and click on the model you added.
- In the little bundle visualisation check that the contents are nicely centred, with even space around the edges.
https://warthogs.atlassian.net/browse/WD-6180
Fixes: https://github.com/canonical/juju-dashboard/issues/1507

WD-6180 - Fix topology position

---

src/panels/RegisterController/RegisterController.test.tsx
src/panels/RegisterController/RegisterController.tsx

- Remove help text about not filling in username/password when using external auth and instead disable the fields.
- Change field order so that you make the decision about using external auth first.
- Go to the controllers page.
- Click "Register a controller".
- Fill in the username and password.
- Tick "This controller uses an external identity provider."
- The username and password fields should get disabled and cleared.
https://warthogs.atlassian.net/browse/WD-6179
Fixes: https://github.com/canonical/juju-dashboard/issues/1501.

WD-6179 - Disable username/password instead of help text

---

src/layout/BaseLayout/_base-layout.scss

- Fixed sidebar scroll when BaseLayout height exceeds viewport height.
- Fix was previously implemented in a7f42ab for Audit Logs feature.
- Fixes: #1616 
Without fix:
With fix:

fix: Fix sidebar scroll when BaseLayout height exceeds viewport height

---

src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
src/panels/CharmsPanel/CharmsPanel.test.tsx
src/panels/CharmsPanel/CharmsPanel.tsx

- Disable charm radio input in `CharmsPanel` when no action is available.
- Jira: https://warthogs.atlassian.net/browse/WD-6249
- Fixes: #1533

WD-6249 - feat: Disable charm radio input when no action is available

---

src/components/ModelTableList/CloudGroup.tsx
src/components/ModelTableList/OwnerGroup.tsx
src/components/ModelTableList/StatusGroup.tsx
src/hooks/useCanConfigureModel.test.tsx
src/hooks/useCanConfigureModel.ts
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.test.tsx
src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.tsx
src/pages/EntityDetails/Model/Model.tsx
src/store/juju/utils/models.test.ts
src/store/juju/utils/models.ts
src/tables/tableHeaders.tsx

- Don't display configure and action controls if the user has read only permissions.
- Using a local controller add a new user with `juju add-user [username]`.
- Grant them read only permissions for a model with at least one app: `juju grant [username] read [model-name]`.
- In the dashboard log in as the new user.
- Go to the model with read-only permissions.
- Search for an app. There shouldn't be any checkboxes or a "Run action" button.
- Click on an app. There shouldn't be a "Configure" button on the left or a "Run action" button and there should be no checkboxes.
https://warthogs.atlassian.net/browse/WD-6258
Fixes: https://github.com/canonical/juju-dashboard/issues/1620

WD-6258 - Hide controls on read only models

---

src/juju/types.ts
src/juju/watchers.ts
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/ModelDetails/ModelDetails.test.tsx
src/pages/ModelDetails/ModelDetails.tsx
src/store/juju/reducers.test.ts
src/store/juju/slice.ts
src/testing/factories/juju/model-watcher.ts
src/utils/getMajorMinorVersion.test.ts
src/utils/getMajorMinorVersion.ts
src/utils/index.ts

- Use data from the watcher instead of getting the full status when using Juju 3.2 and later. This reduces the number of full status calls we need to make, which is expensive for the server.
- Connect to a local Juju 3.2 controller.
- Go to the model list and click on a model.
- On the left side there should be data for controller, cloud/region and version.
- Open the redux dev tools and filter the dispatched actions by `populateMissingAllWatcherData`. There should be no entries.
- Connect to a pre Juju 3.2 controller (e.g. JAAS which is 2.9).
- Go to the model list and click on a model.
- On the left side there should be data for controller, cloud/region and version.
- Open the redux dev tools and filter the dispatched actions by `populateMissingAllWatcherData`. There should be at least …

WD-6200 - reduce full status calls for Juju 3.2

---

src/components/Aside/_aside.scss

- Fix position of panels in Safari.
- Open the dashboard in Safari.
- Go to the controllers page.
- Click "Register a controller".
- The panel should appear on the right of the screen.
- Check this still works in Firefox/Chrome.
- https://warthogs.atlassian.net/browse/WD-6700
- Fixes: #1643.

WD-6700 - Fix position of panels in Safari

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/Routes/Routes.tsx
src/juju/jimm/JIMMV4.test.ts
src/juju/jimm/JIMMV4.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/general/types.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/factories/general.ts

- Check if user is an administrator when logging in.
- Only show audit logs link and route if the user is as an admin.
- Connect to staging.
- Load the dashboard and you should see the Logs link in the sidebar.
- Click Logs and it should show you the logs page.
- Connect to production JAAS.
- Load the dashboard and there should be no Logs link.
- https://warthogs.atlassian.net/browse/WD-5398

WD-5398 - Restrict log access

---

src/juju/api.test.ts
src/juju/api.ts
src/juju/jimm/JIMMV3.ts
src/pages/ControllersIndex/ControllersIndex.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts

- Display dashboard as usual instead of error message when there are 0 controllers.
- Login with a user that has 0 controllers.
- Check that the dashboard loads as usual instead of a `Notification` component with an error message being displayed on the whole page.
- https://warthogs.atlassian.net/browse/WD-7282
- Fixes: https://github.com/canonical/juju-dashboard/issues/1652

WD-7282 - fix: Display dashboard with 0 controllers

---

src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/CloudGroup.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/OwnerGroup.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/ModelTableList/_model-table-list.scss
src/components/ModelTableList/shared.test.tsx
src/components/ModelTableList/shared.tsx
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Machine/Machine.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/pages/Logs/Logs.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts

- Update the model status, owner and cloud tables to be responsive.
- Go to models.
- Switch between the Status, Cloud and Owner tables and make sure that the tables look OK at each 
- https://warthogs.atlassian.net/browse/WD-7495
- https://warthogs.atlassian.net/browse/WD-7496
- https://warthogs.atlassian.net/browse/WD-7497

WD-7495 - Make model tables responsive

---

src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/ControllersIndex/ControllersIndex.tsx

- Specify cloud info for JIMM controllers
- Verify that, in the controllers table, JIMM enabled controllers have actual `CLOUD/REGION` info, instead of `unknown/unknown`.
- https://warthogs.atlassian.net/browse/WD-7607

WD-7607 - fix: Specify cloud info for JIMM controllers

---

src/components/Status/Status.test.tsx
src/components/Status/Status.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss
src/scss/_utils.scss
src/scss/custom/_status_icons.scss

- Make action logs table responsive.
- Go to the 'Action logs' tab in a model.
- If you don't have a model with action logs you might need to run some actions on an app.
- Check that the action logs table appears OK at all screen sizes.
- https://warthogs.atlassian.net/browse/WD-7494

WD-7494 - Make action logs table responsive

---

src/pages/ControllersIndex/_controllers.scss
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/_entity-details.scss

- Make integrations tables responsive.
- Rename 'relation' to 'integration'.
- Go to the model details for a model with integrations.
- Click on the integrations tab.
- Check that the table(s) appear OK at all browser sizes.
https://warthogs.atlassian.net/browse/WD-7613

WD-7613 - Make integrations tables responsive

---

src/pages/EntityDetails/_entity-details.scss
src/tables/tableRows.tsx

- Make machines table responsive.
- Go to the 'Machines' tab in a model.
- Check that the table of machines looks OK at all screen sizes.
- https://warthogs.atlassian.net/browse/WD-7500

WD-7500 - Make machines table responsive

---

HACKING.md
RELEASING.md
package.json

- Update version to 0.12.0.
- Update release docs.

Update version to 0.12.0

---

.github/workflows/actions.yml

- Fix dotrun install in GitHub action.
https://warthogs.atlassian.net/browse/WD-8392

WD-8392 - Fix dotrun install in GitHub action

---

src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/pages/EntityDetails/Model/Secrets/index.ts
src/urls.ts

- Add a component for the secrets tab.
- Linked to the secrets tab from the model details.
- Go to the details page for a model.
- Check that there is a "Secrets tab".
- Clicking on the secrets tab should take you to a blank page.
https://warthogs.atlassian.net/browse/WD-8394

WD-8394 - Add secrets tab

---

src/store/app/thunks.test.ts
src/store/app/thunks.ts
src/store/middleware/check-auth.ts

- When `connectAndStartPolling()` fails, the error is sent to Redux store, and caught and displayed in `ConnectionError` component.
- Modify the end of the `try` block in `connectAndStartPolling()` by throwing a dummy error there e.g. `throw new Error("Dummy error.");`.
- Log into the Juju Dashboard and check that just the `ConnectionError` component renders, same as in the attached screenshot.
- Check that the error is logged in the console as `Error while triggering the connection and polling of models. Error: Dummy error.` followed by the stack trace.
- https://warthogs.atlassian.net/browse/WD-8294

WD-8294 - feat: Display connection and polling of models error

---

src/juju/api.test.ts
src/juju/api.ts
src/pages/ModelsIndex/ModelsIndex.test.tsx
src/pages/ModelsIndex/ModelsIndex.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/factories/juju/juju.ts

- Throw the “Unable to fetch the status.” error instead of using return. Afterward, throw the error, so that it is further caught in `fetchAllModelStatuses()`.
- If less than 10% of models error out, no error is processed in `fetchAllModelStatuses()`. Else, throw the error back, so that it is further caught in `modelPollerMiddleware()`.
- When trying to retrieve models info in `modelPollerMiddleware()`, send "Unable to load models." error if it is the first polling and all models error out, "Unable to load some models." error if it is the first polling and some models error out, "Unable to load latest model data." if it is later polling and the error appears in `fetchAllModelStatuses()` call, else send "Unable to list or update models." error. The error should be sent to `juju -> …

WD-8309 - feat: Display error when trying to retrieve models info

---

src/juju/api.test.ts
src/juju/api.ts
src/juju/apiHook.test.tsx
src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/juju/types.ts
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/store/types.ts
src/testing/factories/juju/juju.ts

- Fetch and store secrets.
- Set up a controller with Juju 3.3.1.
- Add some secrets to a model with: `juju add-secret my-apitoken token=34ae35facd4`
- Open the dashboard and navigate to the model.
- Click on the Secrets tab.
- The secrets should get fetch and displayed in a list.
https://warthogs.atlassian.net/browse/WD-8431

WD-8431 - Fetch and store secrets

---

src/components/AuditLogsTable/AuditLogsTable.tsx
src/components/RelativeDate/RelativeDate.test.tsx
src/components/RelativeDate/RelativeDate.tsx
src/components/RelativeDate/index.ts
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/index.ts

- Add a table of secrets.
- Add a reusable component for displaying relative dates.
- Go to the secrets tab for a model with secrets.
- You should see a basic table displaying the secrets (there are quite a few changes to come in future PRs).
https://warthogs.atlassian.net/browse/WD-8395

WD-8395 - Add secrets table

---

src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/panels/AddSecretPanel/AddSecretPanel.test.tsx
src/panels/AddSecretPanel/AddSecretPanel.tsx
src/panels/AddSecretPanel/Fields/Fields.test.tsx
src/panels/AddSecretPanel/Fields/Fields.tsx
src/panels/AddSecretPanel/Fields/index.ts
src/panels/AddSecretPanel/index.ts
src/panels/AddSecretPanel/types.ts
src/panels/Panels.test.tsx
src/panels/Panels.tsx

- Create components for the add secrets form and panel (submitting the form will be handled in [WD-8546](https://warthogs.atlassian.net/browse/WD-8546)).
- Click "Add secret"
- The panel should open and display a form.
https://warthogs.atlassian.net/browse/WD-8399
[WD-8546]: https://warthogs.atlassian.net/browse/WD-8546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8399 - Create add secrets panel

---

src/juju/api.test.ts
src/juju/api.ts
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/store/middleware/model-poller.ts
src/testing/factories/juju/juju.ts

- Hide the secrets tab if the model doesn't support it.
- Connect to a Juju 3.3 controller.
- You should see a secrets tab.
- Connect to a Juju 2.9 controller.
- You should not see a secrets tab.
https://warthogs.atlassian.net/browse/WD-8412

WD-8412 - Hide secrets tab

---

package.json
src/components/FormikField/FormikField.test.tsx
src/components/FormikField/FormikField.tsx
src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/panels/AddSecretPanel/AddSecretPanel.test.tsx
src/panels/AddSecretPanel/AddSecretPanel.tsx
src/panels/AddSecretPanel/Fields/Fields.test.tsx
src/panels/AddSecretPanel/Fields/Fields.tsx
src/panels/AddSecretPanel/types.ts
src/store/middleware/model-poller.ts
yarn.lock

- Create secrets when the add secret form is submitted.
- Go to the secrets tab in a model.
- Click the "Add secret" button.
- Fill out the form and submit.
- Refresh the page and the secret should appear in the table (the secrets will get refetched in another update).
https://warthogs.atlassian.net/browse/WD-8546

WD-8546 - Create secrets

---

src/hooks/useInlineErrors.test.ts
src/hooks/useInlineErrors.ts
src/panels/ActionsPanel/ActionsPanel.tsx

- Add a hook to store inline errors by key.
- Update ActionPanel to use the hook.
- Open the action panel.
- Check that inline errors appear like they did before (you might need to throw some errors in the component).

Store inline errors by key

---

.eslintrc
package.json
src/components/WebCLI/Output.test.tsx
src/components/WebCLI/Output.tsx
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/panels/ActionsPanel/ActionsPanel.tsx
yarn.lock

- Issue resolved: Until now, if the content in the `WebCLI` started straight away with a color, we displayed twice the beginning of the content. The second time it was displayed without color and with the color encoding appended to it (see screenshots).
- https://warthogs.atlassian.net/browse/WD-8617
Before:
After:

WD-8617 - fix: Fix displaying the first colorless part of the message in WebCLI

---

src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/panels/AddSecretPanel/AddSecretPanel.test.tsx
src/panels/AddSecretPanel/AddSecretPanel.tsx

- Fetch the list of secrets after creating a new one.
- Go to the secrets list.
- Open the add secret panel. Fill out the form and submit.
- The panel should close and the list of secrets should reload with the new secret.
https://warthogs.atlassian.net/browse/WD-8566

WD-8566 - fetch new secrets

---

src/components/FormikField/index.ts
src/components/secrets/RevisionField/RevisionField.test.tsx
src/components/secrets/RevisionField/RevisionField.tsx
src/components/secrets/RevisionField/index.ts
src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
src/pages/EntityDetails/Model/Secrets/SecretContent/index.ts
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/testing/factories/juju/juju.ts

- Fetch and display secret contents in a modal.
- Click the eye next to a secret.
- Choose a revision and click "View"
- The secret contents should be displayed.
https://warthogs.atlassian.net/browse/WD-8398

WD-8398 - View secret contents

---

src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/panels/Panels.test.tsx
src/panels/Panels.tsx
src/panels/RemoveSecretPanel/Fields/Fields.test.tsx
src/panels/RemoveSecretPanel/Fields/Fields.tsx
src/panels/RemoveSecretPanel/Fields/index.ts
src/panels/RemoveSecretPanel/RemoveSecretPanel.test.tsx
src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
src/panels/RemoveSecretPanel/index.ts
src/panels/RemoveSecretPanel/types.ts

- Add a panel to remove secrets.
- Get the URI for a secret.
- In a terminal add a few revisions to the secret: `juju update-secret <URI> token=34ae35facd4` (you can run the same command a few times and each time a new revision will get created).
- Open secrets tab.
- Find the row for the secret you added the revisions to.
- Open the actions menu on the right hand side and click "Remove secret".
- In the panel either choose a revision or click the checkbox to remove them all.
- Submit the form and confirm.
- If all revisions were removed the secret should get removed from the list.
https://warthogs.atlassian.net/browse/WD-8401

WD-8401 - Remove secrets

---

src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx

- Display fetch action logs error in Action Logs.
- https://warthogs.atlassian.net/browse/WD-8828

WD-8828 - feat: Display errors in Action Logs

---

src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/panels/GrantSecretPanel/GrantSecretPanel.test.tsx
src/panels/GrantSecretPanel/GrantSecretPanel.tsx
src/panels/GrantSecretPanel/index.ts
src/panels/Panels.test.tsx
src/panels/Panels.tsx
src/testing/factories/juju/juju.ts

- Add a panel for granting/revoking secrets.
- Go to the secrets tab for a model with more than one application.
- Open the action menu for a secret.
- Click "Grant"
- Choose an application and save.
- The panel should close and the number of granted counts should update.
- Open the grant panel again and deselect the selected app and select another and save.
- Reopen the panel and the checkboxes should reflect the changes you just made.
https://warthogs.atlassian.net/browse/WD-8403
https://warthogs.atlassian.net/browse/WD-8402

WD-8402 - grant/revoke secrets

---

src/index.test.tsx
src/pages/ModelsIndex/ModelsIndex.test.tsx
src/panels/ActionsPanel/ActionsPanel.test.tsx
src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.tsx
src/panels/CharmsPanel/CharmsPanel.test.tsx
src/panels/CharmsPanel/CharmsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx

- Display get charm application(s) error (triggered in `CharmsAndActionsPanel`) in `CharmsPanel`.
- https://warthogs.atlassian.net/browse/WD-8829

WD-8829 - feat: display errors in Charms and Actions Panel

---

src/scss/_vanilla-overrides.scss

- Fix notifications overlapping top navigation bar.
- This PR fixes this bug: https://github.com/canonical/vanilla-framework/issues/4990
- https://warthogs.atlassian.net/browse/WD-8858
Before:
After:

WD-8858 - fix: fix notifications overlapping top navigation bar

---

src/hooks/useCanManageSecrets.test.tsx
src/hooks/useCanManageSecrets.ts
src/juju/api.test.ts
src/juju/api.ts
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/pages/ModelDetails/ModelDetails.tsx
src/panels/Panels.test.tsx
src/panels/Panels.tsx

- Limit write actions for secrets to users that are have write or admin permission and are using a version of Juju with the Secrets v2 facade.
- Log in as a model admin (your normal user probably is otherwise log in as the admin user).
- Go to the secrets tab and check that you can open the panels for adding/updating secrets etc.
- Create a new user that has write permissions to a model (you will also need to make them a controller superuser due to this bug: https://bugs.launchpad.net/juju/+bug/2053102):
```
juju add-user writeuser
juju grant writeuser superuser
juju grant writeuser write [model-name]
```
- Log in as that user.
- Go to the secrets tab and check that you can open the panels for adding/updating secrets etc.
- Create a new user that has read permissions for a model:
```
juju …
```

WD-8411 - Limit write actions for secrets

---

src/panels/RemoveSecretPanel/Fields/Fields.tsx

- Update remove secret panel to use the revision field.
- Go to the secrets tab and open the remove panel for a secret with more than one revision.
- Tick the 'remove all' checkbox and the revision field should get disabled.
- Untick the remove all checkbox and choose a revision that isn't the latest.
- Submit the form and open the panel again and the revision you removed shouldn't appear in the select box.
- https://warthogs.atlassian.net/browse/WD-8753

WD-8753 - Use revision field in remove form

---

src/components/ConnectionError/ConnectionError.test.tsx
src/components/ConnectionError/ConnectionError.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/store/middleware/check-auth.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/factories/juju/juju.ts

- Displayed the Audit Logs user permission check error.
- Run either demo or staging of JIMM.
- Throw an error on line 155 in `store/middleware/model-poller.ts`.
- A toast identical to the one in the attached screenshot should appear.
- https://warthogs.atlassian.net/browse/WD-8855

WD-8855 - feat: display model-poller errors

---

src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx

- Include the secret owner in the access count
- Check that secrets that are owned by an application include the owner in the count of applications that have been granted access.
https://warthogs.atlassian.net/browse/WD-8929

WD-8929 - owner in access count

---

src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
src/panels/GrantSecretPanel/GrantSecretPanel.tsx
src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx

- Display secret name/URI in panels.
- Open the grant panel and check that the secret name/URI is displayed near top.
- Open the remove panel and check that the secret name/URI is displayed near top.
- Click the eye icon to view the secret content and check that the secret name/URI is displayed near top.
- https://warthogs.atlassian.net/browse/WD-8971

WD-8971 - Display secret name

---

src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/SecretsPicker/SecretsPicker.test.tsx
src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
src/utils/index.ts
src/utils/secretIsAppOwned.test.ts
src/utils/secretIsAppOwned.ts

- Disable write actions for app-owned secrets.
- Check that app-owned secrets don't display an actions menu.
- Go to the config panel for a charm.
- Open the secrets picker.
- Check that no app-owned secrets are in the list.
- https://warthogs.atlassian.net/browse/WD-8972

WD-8972 - Disable app-owned secret actions

---

src/juju/api.test.ts
src/juju/api.ts
src/juju/apiHooks.test.tsx

- Reject on timeout instead of returning special string.
- Go to the model list and check that the models appear.
- Open api.ts and change `LOGIN_TIMEOUT` to a very low number.
- Reload the model list and check that the console has timeout errors.

Improve timeout promise

---

src/juju/api.test.ts
src/juju/api.ts
src/store/middleware/check-auth.ts

- Handle storing models after logout.
- Connect to a slow local controller.
- Login and then immediately logout.
- The uncaught error should not appear.
- https://warthogs.atlassian.net/browse/WD-9169
- https://github.com/canonical/juju-dashboard/issues/1635

WD-9169 - Handle model store error

---

package.json
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/panels/RemoveSecretPanel/Fields/Fields.tsx
yarn.lock

- Refactored after the fix to stop click event propagation in `Modal` and `ConfirmationModal` in `react-components`.
- https://warthogs.atlassian.net/browse/WD-9981

WD-9981 - refactor: remove click propagation

---

.env.development
.gitignore
vite.config.ts

- Add a proxy to the JIMM API for OIDC login.
- Set up JIMM following the instructions in this PR: https://github.com/canonical/juju-dashboard/pull/1764.
- Visit `http://jimm.localhost:8036/auth/whoami`.
- Check that you see the logged in user details or forbidden message if you're not logged in (or you might even get `Internal Server Error - failed to retrieve session` if you've never logged in before ).
https://warthogs.atlassian.net/browse/WD-11704

WD-11704 - feat: add development proxy to JIMM

---

package.json
src/global.d.ts
src/juju/jimm/api.ts
src/juju/jimm/thunks.test.ts
src/juju/jimm/thunks.ts
src/store/middleware/check-auth.ts
src/testing/setup.ts
yarn.lock

Add thunks for whoami and logout requests.
- Open `LogIn.tsx`.
- Inside the component add:
```typescript
const dispatch = useAppDispatch();
useEffect(() => {
void (async () => {
//   await dispatch(logout());
const whoamiResponse = await dispatch(whoami());
console.log("whoami:", unwrapResult(whoamiResponse));
})();
}, [dispatch]);
```
- Visit http://jimm.localhost:8036/auth/logout to make sure you're not logged in.
- Open the dashboard and in the console you should see `whoami: null`.
- Visit http://jimm.localhost:8036/auth/login and log in.
- Go to the login page again and this time you should see `whoami: {display-name: 'jimm-test', email: 'jimm-test@canonical.com'}`.
- In the useEffect you added uncomment the logout line.
- Reload the login page and it should display `whoami: null`. …

WD-11705 - feat: add API thunks for JIMM endpoints

---

src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
src/components/LogIn/IdentityProviderForm/index.ts
src/components/LogIn/IdentityProviderForm/types.ts
src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/LogIn/OIDCForm/OIDCForm.test.tsx
src/components/LogIn/OIDCForm/OIDCForm.tsx
src/components/LogIn/OIDCForm/index.ts
src/components/LogIn/OIDCForm/types.ts
src/index.test.tsx
src/index.tsx
src/juju/jimm/thunks.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts

- Display the login for OIDC.
- Visit http://jimm.localhost:8036/auth/logout to make sure you're logged out.
- Go to the dashboard (http://jimm.localhost:8036/).
- You should see a "Log in to dashboard" button.
- Click the button and follow the login flow (depending on whether you're logged into the auth provider you'll either be asked to enter your username/password or you'll just get redirected back to the dashboard).
- At this point you'll see the login screen with an error: "Could not log into controller" which is expected as the controller/model login hasn't been implemented yet.
https://warthogs.atlassian.net/browse/WD-11706

WD-11706 - feat: display OIDC login form

---

.github/workflows/actions.yml

- Updated the dotrun action to use the python version and prevent it always failing
- The dotrun job should work for this PR

fix: dotrun workflow task

---

HACKING.md
package.json
src/juju/api.test.ts
src/juju/api.ts
src/juju/jimm/JIMMV3.ts
src/juju/jimm/JIMMV4.test.ts
yarn.lock

Note: this will fail CI until https://github.com/juju/js-libjuju/pull/127 is released which needs to be QAed along with this PR.
- Log in to controllers and models using OIDC.
- Inside the Multipass running the dashboard and JIMM with OIDC, checkout out this branch: https://github.com/juju/js-libjuju/pull/127.
- `yarn install` and `yarn build` inside the jujulib dir.
- Go to the dashboard dir and `yarn link` to the jujulib dir you just checked out.
- Start the dashboard and visit it in your browser.
- Log in (if you're not already logged in) and the dashboard should load and display your models and controllers.
- Now configure your dashboard to point to a local controller using local (username/password) users (or check this branch out somewhere that has access to a local controller - …

WD-11707 - feat: OIDC ws login

---

src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts

- Handle 500 errors when checking if the user is authenticated.
- Log in using OIDC.
- Using your browser's dev tools find the `jimm-browser-session` cookie and change the value to anything.
- Reload the dashboard.
- It should display the "Unable to check authentication status." error.
https://warthogs.atlassian.net/browse/WD-12178
https://warthogs.atlassian.net/browse/WD-12176

WD-12178 - fix: handle 500 errors for the whoami endpoint

---

src/store/app/thunks.test.ts
src/store/app/thunks.ts

- Log out when using OIDC
- Log in using OIDC.
- Open the user menu (bottom of the left nav panel).
- Click "Log out".
- Refresh the dashboard and you should see the login button.
- Log in again.
- Using your browser's dev tools find the jimm-browser-session cookie and change the value to anything.
- Open the user menu and click "Log out".
- You should see an error.
Note: the reason this logout error takes over the entire screen is because at the point this error is returned by the API the dashboard has already disconnected from the websocket connections and cleared all the data for models, controllers etc. so we don't have anything to display.
https://warthogs.atlassian.net/browse/WD-11708

WD-11708 - feat: log out using OIDC

---

src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/ActionPayloadModal.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/ActionPayloadModal.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/index.ts
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/types.ts
src/pages/EntityDetails/Model/Logs/ActionLogs/types.ts

- Remove nested components from `ActionLogs`.
- https://warthogs.atlassian.net/browse/WD-11593

WD-11593 - refactor: remove nested components from ActionLogs

---

.github/workflows/tics-coverage.yml

- remove tics report upload to prevent a security issue

chore(ci) remove ticls report upload to prevent a security issue

---

.eslintrc
src/consts.ts
src/index.tsx
src/juju/jimm/listeners.test.ts
src/juju/jimm/listeners.ts
src/juju/jimm/thunks.test.ts
src/juju/jimm/thunks.ts
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/store/app/thunks.test.ts
src/store/app/thunks.ts
src/store/listenerMiddleware.ts
src/store/middleware/check-auth.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/store/store.ts

- Poll the whoami endpoint to handle refreshing and revoking tokens.
- Log out if the user is no longer authenticated.
- Set up an OIDC enabled JIMM with the session max age to something short e.g. 30 seconds by changing `JIMM_SESSION_COOKIE_MAX_AGE: 30` in `docker-compose.yaml` before you set up the env.
- In the dashboard open `src/consts.ts`.
- Set the poll interval to less than the max age above e.g. `export const OIDC_POLL_INTERVAL = 20 * 1000;`.
- Run the dashboard.
- Log in.
- Using the network tab you should see that the whoami endpoint is pinged at the interval you set above.
- Inside the container running JIMM run the following commands to revoke the token (but don't stop the running environment or your dashboard you want this to keep pinging the API):
```
docker exec -it …
```

WD-12713 - feat: handle oidc refresh and revoke

---

.github/workflows/tics-coverage.yml

[List of work items including drive-bys]
- Pull code

ci: update TICS Auth Secret in workflow

---

.github/workflows/tics-coverage.yml

From the request of the Tiobe team, reducing the number of submissions to once per week. Specifically, on Friday night at 10pm.
- Check back next week to see the job ran on Friday

chore: update tics coverage frequency

---

src/components/EntityInfo/EntityInfo.test.tsx
src/components/EntityInfo/EntityInfo.tsx
src/components/EntityInfo/_entity-info.scss
src/components/TruncatedTooltip/TruncatedTooltip.test.tsx
src/components/TruncatedTooltip/TruncatedTooltip.tsx
src/pages/AdvancedSearch/SearchForm/SearchHelp/SearchHelp.tsx

- Fixed the second JQ query example which was wrong beforehand.
- Fixed the model info that showed the model owner's name in the left hand side. It got wrapped a fair bit as the owner was a service account.
- https://warthogs.atlassian.net/browse/WD-15784
- Screen width < 1580px:
- Screen width >= 1580px:

WD-15784 - fix: fix issues observed in k8s charm

---

src/components/App/App.test.tsx
src/components/App/App.tsx
src/components/CaptureRoutes/CaptureRoutes.test.tsx
src/components/CaptureRoutes/CaptureRoutes.tsx
src/components/CaptureRoutes/index.ts
src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/Routes/Routes.tsx
src/pages/PageNotFound/PageNotFound.test.tsx

- replace BrowserRouter with createBrowserRouter to support the routing in ReBACAdmin as they require the data APIs that are not supported by BrowserRouter.
- Check that the routing works as before.
https://warthogs.atlassian.net/browse/WD-16020

WD-16020 - refactor: replace BrowserRouter with createBrowserRouter

---

package.json
src/components/PrimaryNav/PrimaryNav.tsx
src/components/PrimaryNav/types.ts
src/components/Routes/Routes.tsx
src/layout/BaseLayout/BaseLayout.tsx
src/pages/Permissions/Permissions.test.tsx
src/pages/Permissions/Permissions.tsx
src/pages/Permissions/index.ts
src/scss/index.scss
src/urls.ts
vite.config.ts
yarn.lock

- Display ReBAC Admin in the dashboard.
- Point your dashboard to a [local JIMM](https://github.com/canonical/juju-dashboard/blob/main/HACKING.md#jimm-controller).
- Click on the Permissions Links in the sidebar and ReBAC Admin should be displayed.
https://warthogs.atlassian.net/browse/WD-16080

WD-16080 - feat: add ReBAC Admin

---

src/components/LogIn/LogIn.tsx
src/components/LogIn/index.ts
src/components/LogIn/types.ts
src/components/Routes/Routes.test.tsx
src/components/Routes/Routes.tsx

- Don't display the 404 page for some routes until after login.
- Connect your dashboard to JAAS.
- Log out.
- Go to /permissions.
- It should ask you to log in.
https://warthogs.atlassian.net/browse/WD-18219

fix: log in before displaying 404 for some routes

---

.github/workflows/actions.yml
.github/workflows/coverage.yml
.github/workflows/test.yml
HACKING.md
README.md
codecov.yml
vite.config.ts

- Migrated code coverage to vitest-coverage-report-action
- Added coverage threshold to lines(95), statements(95), functions(95) and branches(90)
- Pipeline runs and passes
https://warthogs.atlassian.net/browse/WD-18338

chore(testing): Migrate code coverage to vitest-coverage-report-action

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/store/juju/selectors.ts

- Check if the primary nav permissions have already been fetch and if so don't fetch them again. This is required as the nav is part of the layout that wraps each component and gets recreated on each top level route change.
- Check that the logs and permissions nav items are visible.
- Click on a different page e.g. go from models to controllers.
- Check that the logs and permissions items don't disappear and then reappear during navigation.
https://warthogs.atlassian.net/browse/WD-18854

fix: don't refetch nav permissions

---

src/components/LogIn/LogIn.test.tsx
src/components/LogIn/OIDCForm/OIDCForm.test.tsx
src/components/LogIn/OIDCForm/OIDCForm.tsx
src/components/LogIn/types.ts
src/juju/jimm/listeners.ts
src/pages/ControllersIndex/ControllersIndex.test.tsx
src/store/general/reducers.test.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/general/slice.ts
src/store/general/types.ts
src/store/middleware/check-auth.ts
src/store/middleware/model-poller.ts
src/testing/factories/general.ts

- Fixes the phenomenon where the OIDC button was being shown after redirecting from login
- Shows a spinner within the button and disables it while authentication is in progress
- Try logging in from with a JIMM controller
- After redirection, the button should not be interactive and show spinner
https://warthogs.atlassian.net/browse/WD-18340

fix(oidc): Display spinner in OIDC login button during loading

---

src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/Logs/Logs.test.tsx
src/pages/EntityDetails/Model/Logs/Logs.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/ModelTabs/ModelTabs.test.tsx
src/pages/EntityDetails/Model/ModelTabs/ModelTabs.tsx
src/pages/EntityDetails/Model/ModelTabs/index.ts
src/pages/EntityDetails/Model/ModelTabs/types.ts

- Refactor tabs into a component.
- Check permissions for audit logs via JIMM.
- Go to a model and check that there is a Logs tab.
- Click on the logs tab and check that there are two sub-tabs: "Audit logs" and "Action logs" and that you can view the "Audit logs" tab.
- Connect to a local (non-jimm) controller.
- Go to a model and check that there is an "Action logs" tab and no sub-tabs.
https://warthogs.atlassian.net/browse/WD-19056

feat: check audit logs access via jimm

---

src/components/AccessButton/AccessButton.test.tsx
src/components/AccessButton/AccessButton.tsx
src/components/AccessButton/index.ts
src/components/AccessButton/types.ts
src/components/ModelTableList/AccessButton/AccessButton.test.tsx
src/components/ModelTableList/AccessButton/AccessButton.tsx
src/components/ModelTableList/CloudGroup/CloudGroup.test.tsx
src/components/ModelTableList/CloudGroup/CloudGroup.tsx
src/components/ModelTableList/OwnerGroup/OwnerGroup.test.tsx
src/components/ModelTableList/OwnerGroup/OwnerGroup.tsx
src/components/ModelTableList/StatusGroup/StatusGroup.test.tsx
src/components/ModelTableList/StatusGroup/StatusGroup.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Model/types.ts
src/pages/Permissions/Permissions.tsx
src/urls.ts

- Make a shared access button to handle logic in one place (the existing access button wraps the new component as it sets the appearance for all the model tables).
- Update the access button to link to groups when using JIMM.
- Connect to a local Juju controller.
- In the model list hover a model and click on the access button and it should show the access panel.
- In the model list hover a model and click on the access button and it should take you to the groups page.
https://warthogs.atlassian.net/browse/WD-19058
https://warthogs.atlassian.net/browse/WD-19057

feat: access buttons link to groups when using rebac

---

src/hooks/useCanConfigureModel.test.tsx
src/hooks/useCanConfigureModel.ts
src/hooks/useCanManageSecrets.test.tsx
src/juju/api-hooks/permissions.test.tsx
src/juju/api-hooks/permissions.ts
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/ApplicationsTab/LocalAppsTable/LocalAppsTable.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Model/Secrets/Secrets.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/SecretsPicker/SecretsPicker.test.tsx
src/panels/Panels.test.tsx

- Update useCanConfigureModel hook to check permissions via rebac when using JIMM.
- Go to a model details page
- Check that model access button appears on the left hand side.
- Click on an app and check that the configure button appears.
https://warthogs.atlassian.net/browse/WD-19055

feat: update useCanConfigureModel hook to check permissions via rebac

---

package.json
src/components/App/App.test.tsx
src/components/App/App.tsx
src/components/CaptureRoutes/CaptureRoutes.test.tsx
src/components/LogIn/LogIn.tsx
src/hooks/useAnalytics.test.ts
src/hooks/useAnalytics.tsx
src/store/middleware/model-poller.ts
src/testing/setup.ts
src/utils/analytics.test.ts
src/utils/analytics.ts
yarn.lock

- Upgraded react-ga to react-ga4
- Implemented usage analytics using event params
- Login to dashboard
- Dashboard should send values like dashboard version, controller version and whether you’re using JAAS on successful login
https://warthogs.atlassian.net/browse/WD-18723

feat(analytics): Implement usage analytics with react-ga4

---

src/components/EntityInfo/EntityInfo.test.tsx
src/components/SecondaryNavigation/_secondary-navigation.scss
src/components/TruncatedTooltip/TruncatedTooltip.test.tsx
src/pages/EntityDetails/_entity-details.scss
src/panels/ShareModelPanel/_share-model.scss
src/scss/index.scss
vite.config.ts

- Fix `EntityInfo` overflowing items by importing `truncated-tooltip` into top level SCSS file
- Include new test case in `TruncatedTooltip` to ensure the style is overridden
- Update `EntityInfo` tests
- Clean up references to `topology`
- Add new test for empty entity data
- Clean up duplicated SCSS includes (close #1866, close #1867)
- Turn on CSS source maps in dev mode
- closes #1870 
- https://warthogs.atlassian.net/jira/software/c/projects/WD/issues/WD-19878

fix: overflowing tooltip on model page

---

src/panels/ConfigPanel/_config-panel.scss

- use `break-word` in `pre` containing configuration description, to prevent wrapping from changing panel aside width
- close #1868 
- WD-19882

fix: apply word break in config panel

---

src/components/CheckPermissions/CheckPermissions.test.tsx
src/components/CheckPermissions/CheckPermissions.tsx
src/components/CheckPermissions/index.ts
src/components/CheckPermissions/types.ts
src/components/Routes/Routes.test.tsx
src/components/Routes/Routes.tsx
src/layout/BaseLayout/BaseLayout.test.tsx
src/layout/BaseLayout/BaseLayout.tsx
src/layout/BaseLayout/index.ts
src/layout/BaseLayout/types.ts
src/pages/AdvancedSearch/AdvancedSearch.test.tsx
src/pages/AdvancedSearch/AdvancedSearch.tsx
src/pages/Logs/Logs.test.tsx
src/pages/Logs/Logs.tsx
src/pages/PageNotFound/PageNotFound.tsx
src/pages/Permissions/Permissions.test.tsx
src/pages/Permissions/Permissions.tsx

- Correctly disable routes for disabled features.
- Check user permissions if the feature is enabled.
- Connect to a local Juju controller.
- Visit one of the disabled features by typing the URL e.g. /search or /logs or /permissions (these won't be in the side nav).
- It should not require you to log in and instead display a 404 page.
- Make sure rebac is enabled with `?enable-flag=rebac`
- You should see the search, logs and permissions nav items.
- Clicking on them should display the pages.
- Enter `?disable-flag=rebac` and then visit /permissions
- It should display a 404 page.
https://warthogs.atlassian.net/browse/WD-19883

fix: correctly disable routes for disabled features

---

src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.test.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Label/Label.test.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Label/Label.tsx
src/pages/EntityDetails/Unit/Unit.test.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/pages/EntityDetails/Unit/index.ts
src/pages/EntityDetails/Unit/types.ts
src/pages/EntityDetails/_entity-details.scss

- correctly generate unit links in advanced search
- create not found page for units instead of crashing
- Pull code
- Open http://0.0.0.0:8036/search?q=.
- Expand root -> 0 -> units, click on a unit (eg `source/4`)
- Should correctly navigate to source page
- Navigate to junk unit page (add something to end of current URL) for not found page
- WD-19966
- close #1869 
https://github.com/user-attachments/assets/14059413-baca-44a3-b337-ac320904d38b

fix: unit link generation

---

src/pages/ModelsIndex/ModelsIndex.test.tsx
src/pages/ModelsIndex/ModelsIndex.tsx

- previously `modelsLoaded` took precedence over checking `modelError`
- includes test to ensure spinner is hidden and no other content is displayed on the page
- Pull code
- Apply patch to `model-poller` (see below)
- Open dashboard
<details>
<summary>Patch with error</summary>
```patch
diff --git a/src/store/middleware/model-poller.ts b/src/store/middleware/model-poller.ts
index 39d9b6e6..7012da47 100644
--- a/src/store/middleware/model-poller.ts
+++ b/src/store/middleware/model-poller.ts
@@ -217,6 +217,7 @@ export const modelPollerMiddleware: Middleware<
const models = await conn.facades.modelManager?.listModels({
tag: identity,
});
+              throw new Error("model loading failure");
if (models) { …
```

fix: show error on initial model error

---

src/components/AuditLogsTable/AuditLogsTable.test.tsx
src/pages/ModelsIndex/ModelsIndex.test.tsx
src/pages/ModelsIndex/ModelsIndex.tsx
src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/testing/queries/index.ts
src/testing/queries/notifications.ts
src/testing/queries/queries.ts
src/testing/queries/spinners.ts
src/testing/queries/tables.ts
src/testing/queries/within.ts
src/testing/utils.tsx

- copy queries into `src/testing`
- update a handful of tests to use each available query
- includes suggestion from #1878 which was missed in original PR

refactor(tests): migrate test queries from rebac-admin

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/hooks/useCanConfigureModel.test.tsx
src/juju/api-hooks/permissions.test.tsx
src/pages/EntityDetails/Model/Logs/Logs.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/ModelTabs/ModelTabs.test.tsx
src/pages/Logs/Logs.test.tsx
src/pages/Permissions/Permissions.test.tsx
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/testing/factories/juju/juju.ts

Rename types and state for the ReBAC data related to the allowed responses. This is in preparation for some additional ReBAC data for relationships between two objects.
https://warthogs.atlassian.net/browse/WD-20082

refactor: rename rebac relation state

---

src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss

Feels a little bit wacky, but the issue boils down to elements with an opacity != 0 will create a new stacking context, meaning the z-index set within for the backdrop doesn't interact with the rest of the page (eg navigation bars)
- render modal inside `Portal`
- add to framer element:
- `position` to create a new stacking context which the modal can't break out of
- `z-index` to imitate Vanilla's modal backdrop
- Pull code
- Navigate Models -> a model -> Action Logs -> click a result
- close #1784 
- WD-20084
https://github.com/user-attachments/assets/811ba812-0da3-40ae-8884-775e6dc0baee

fix: prevent action log modal from breaking out of stacking context

---

package.json
yarn.lock

Updated framer-motion to fix an issue where reopening actions panel didn't reset it as `AnimatePresence` wasn't removing the panel from the DOM when closing it.
- Go to a model with multiple apps.
- Search and tick multiple apps.
- Click "Run action".
- Choose one of the apps and click 'Next'.
- Close the panel and click "Run action" again.
- See that you don't get to choose an app and you get taken straight to the action options.
Fixes #1888.
https://warthogs.atlassian.net/browse/WD-20173

fix: actions panel reopen

---

src/components/RadioInputBox/RadioInputBox.tsx
src/components/RadioInputBox/_radio-input-box.scss

Since the charm action item height was set in JS, there was a moment of time where the default item height was displayed before React kicked in and set it to the correct value.
This fix includes a few changes:
- No more magic values: animation points are pulled out of CSS variables, rather than hard coded pixel values
- Height enforced via CSS: JS is only used for triggering animations, there are no manual overrides of `el.style.height` in JS
- Pull code
- Select an application, and click 'Run Action'
- Close #1557
- WD-20172
I've slowed down the recording for some of these which have caused some frames to go weird. This doesn't seem to be the case when actually using it (see the last video). …

fix: flash of charm actions on load

---

src/auth/Auth.test.ts
src/auth/Auth.ts
src/auth/index.ts

- Create `Auth` base class
- WD-20704
- `constructor(dispatch: AppDispatch)`
- Checks if singleton has already been initialised, and will emit a warning if it has been
- Should the constructor also be passed `getState` to thunk-ify it?
- `bootstrap(): Promise<void>`
- Replaces: https://github.com/canonical/juju-dashboard/blob/93c1d3fbf7fd037a27e598f7b499f0917187c62d/src/index.tsx#L161-L172
- `logout(): Promise<void>`
- Replaces: https://github.com/canonical/juju-dashboard/blob/93c1d3fbf7fd037a27e598f7b499f0917187c62d/src/store/app/thunks.ts#L39-L47
- `onControllerListFetched(conn: ConnectionWithFacades): Promise<void>`
- Candid implementation requires `conn` in order to call `disableControllerUUIDMasking`
- Could be renamed to `afterControllerListFetched` to make it clear where in the …

feat: implement base `Auth` class

---

HACKING.md
RELEASING.md

[List of work items including drive-bys]
- Pull code

chore(docs): add instructions for charm access and port forwarding

---

package.json
src/auth/Auth.ts
src/auth/LocalAuth.ts
src/auth/OIDCAuth.test.ts
src/auth/OIDCAuth.ts
src/auth/index.ts
src/auth/utils.test.ts
src/auth/utils.ts
src/index.test.tsx
src/index.tsx
src/juju/api-hooks/actions.test.tsx
src/juju/api-hooks/application.test.tsx
src/juju/api-hooks/common.test.tsx
src/juju/api-hooks/common.ts
src/juju/api-hooks/secrets.test.tsx
src/juju/api.test.ts
src/juju/api.ts
src/store/app/actions.test.ts
src/store/app/actions.ts
src/store/app/thunks.test.ts
src/store/app/thunks.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/utils.tsx
yarn.lock

- Utilise `Auth` methods (WD-20708)
- Update `js-libjuju` to `8.0.1`
- Ensure local juju multipass is running
- `yarn start`
- http://localhost:8036
- Login with local user account
- Verify dashboard functionality
- Logout of user in bottom left corner
- Ensure access to JIMM instance
- `sudo yarn start-jaas --port 443`
- https://jimm-dashboard.k8s.dev.canonical.com
- Login with Google account
- Verify dashboard functionality
- Logout of user in bottom left corner
- Ensure access to [Juju controller with Candid](https://github.com/canonical/juju-dashboard/blob/main/HACKING.md#juju-controller-with-candid)
- `yarn start`
- http://localhost:8036
- Login with external account
- Verify dashboard functionality
- Logout of user in bottom left corner
Unfortunately this is a bit of a messy PR as …

feat: utilise `Auth` methods in place of `AuthMethod`

---

src/auth/OIDCAuth.test.ts
src/auth/OIDCAuth.ts
src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
src/components/LogIn/LogIn.tsx
src/components/LogIn/OIDCForm/OIDCForm.test.tsx
src/components/LogIn/OIDCForm/OIDCForm.tsx
src/components/LogIn/UserPassForm/UserPassForm.test.tsx
src/components/LogIn/UserPassForm/UserPassForm.tsx
src/index.tsx
src/juju/bakery.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts

WD-20709
- Move spinner logic out of `OIDCForm` to `LogIn`
- Ensure local juju multipass is running
- `yarn start`
- http://localhost:8036
- Login with local user account
- Ensure access to JIMM instance
- `sudo yarn start-jaas --port 443`
- https://jimm-dashboard.k8s.dev.canonical.com
- Login with Google account
- Ensure access to [Juju controller with Candid](https://github.com/canonical/juju-dashboard/blob/main/HACKING.md#juju-controller-with-candid)
- `yarn start`
- http://localhost:8036
- Login with external account

feat: hoist login state

---

.github/actions/run-playwright/action.yml
.github/actions/setup-candid/action.yaml
.github/actions/setup-k8s-charm/action.yml
.github/actions/wait-for-snap/action.yml
.github/workflows/e2e-juju-k8s-charm-local-auth.yml
.github/workflows/end-to-end.yml

Add a workflow for testing the dashboard with Juju, local auth and the k8s charm.
Check that the workflow completes successfully:
https://github.com/canonical/juju-dashboard/actions/runs/14299184682/job/40070634428?pr=1921
Check the uploaded artefact:
https://github.com/canonical/juju-dashboard/actions/runs/14299184682?pr=1921
https://warthogs.atlassian.net/browse/WD-20939

chore(ci): add Juju, k8s and local auth e2e workflow

---

e2e/base/init.spec.ts
e2e/fixtures/auth-setup.ts
e2e/fixtures/setup.ts
e2e/helpers/auth-helpers.ts
tsconfig.json

- Introduces basic authentication integration tests for all Juju workflows
- Verify the login functionality using username and password for Candid as well as Local Auth
- Implement helpers for authentication
- Inject the helpers as fixtures into the test
- The authentication tests should pass for all workflows
- Check the test results for all available End-to-End test workflows:
1. https://github.com/canonical/juju-dashboard/actions/runs/14304424635/job/40085019396?pr=1926
2. https://github.com/canonical/juju-dashboard/actions/runs/14304424635/job/40085019912?pr=1926
3. https://github.com/canonical/juju-dashboard/actions/runs/14304424635/job/40085020348?pr=1926
https://warthogs.atlassian.net/browse/WD-20934

feat(e2e): add basic auth tests for juju workflows

---

.github/actions/send-notification/action.yml
.github/workflows/e2e-juju-k8s-charm-local-auth.yml
.github/workflows/e2e-juju-machine-charm-candid-auth.yml
.github/workflows/e2e-juju-machine-charm-local-auth.yml
.github/workflows/end-to-end.yml

- Use [`secrets: inherit`](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow) for re-usable workflows
- Create `send-notification` action
- https://github.com/canonical/juju-dashboard/actions/runs/14326157448/job/40151897274#step:3:1
WD-20958

feat: create webhook notification action

---

e2e/base/models.spec.ts
e2e/juju/model-access-control.spec.ts

- Added test suite to check that a user can change model permissions
- Also verifies that a user with permission can view another's model
- All tests should pass
https://warthogs.atlassian.net/browse/WD-20952

feat(e2e): Add test suite for model access control

---

.github/actions/prepare-action/action.yml
.github/workflows/e2e-juju-k8s-charm-local-auth.yml
.github/workflows/e2e-juju-machine-charm-candid-auth.yml
.github/workflows/e2e-juju-machine-charm-local-auth.yml

- Use commit SHA instead of named ref for checking out source in action
- Actions pass
This seems to be a side effect of running the action across forks, rather than solely on branches within the repository. Branch names aren't shared across forks, so when `pull_request.head.ref` returns a branch name, the action isn't able to correctly determine how to resolve it. Using `pull_request.head.sha` appears to solve this.

fix(ci): use commit sha for pull request workflow

---

.github/workflows/end-to-end.yml

- Fix an issue where changing an unrelated label would trigger the e2e workflows if the PR already had the `e2e` label applied.
https://warthogs.atlassian.net/browse/WD-21780

fix: don't trigger e2e from other labels

---

.github/actions/setup-jimm/action.yml

- Outputs various  logs if the JIMM set up fails.
https://warthogs.atlassian.net/browse/WD-21843

chore(CI): display logs if JIMM fails

---

e2e/base/models.spec.ts
e2e/helpers/actions/addModel.ts
e2e/helpers/auth/Users.ts
e2e/juju/model-access-control.spec.ts
e2e/juju/web-cli.spec.ts

- Updated the `models.spec.ts` test suite
- The test to verify list of created + shared models is now run from a secondary user's perspective that does not have superuser permissions
- Removed hard-coded model names and added incrementing model name.
https://warthogs.atlassian.net/browse/WD-21920

feat(e2e): Update test suite for models

---

e2e/helpers/juju-cli.ts
e2e/jimm/audit-logs.spec.ts
e2e/jimm/rebac.spec.ts

- Test that audit logs can be viewed on the top level page and in model details.
https://warthogs.atlassian.net/browse/WD-20955

chore(ci): add e2e tests for accessing audit logs

---

e2e/base/configure.spec.ts
e2e/helpers/auth/Users.ts
e2e/helpers/auth/backends/Candid.ts
e2e/helpers/auth/backends/Local.ts
e2e/helpers/auth/backends/OIDC.ts
e2e/helpers/objects/application.ts

- Add support for reloading the dashboard and logging back in.
- Added configure application test.
Passing run:
https://github.com/canonical/juju-dashboard/actions/runs/14986276376?pr=1966
https://warthogs.atlassian.net/browse/WD-20945

chore(ci): add e2e test for configuring an application

---

.github/actions/failure-log/action.yml
.github/actions/setup-jimm/action.yml
.github/actions/setup-k8s-charm/action.yml
.github/actions/setup-machine-charm/action.yml
.github/workflows/e2e-jimm-k8s-charm-oidc-auth.yml
.github/workflows/e2e-juju-k8s-charm-local-auth.yml
.github/workflows/e2e-juju-machine-charm-candid-auth.yml
.github/workflows/e2e-juju-machine-charm-local-auth.yml

- Increase timeout when running actions on a unit.
- Wait for the vault cert file to be created.
- Retry `charmcraft pack` if it fails.
- Replace `|| true` with a retry so that it doesn't continue on real failures (if it times out the first time wait-for is called then that usually means the status updates stopped and the retry will run wait-for again and this time it will succeed as it will already be in the right state).
- Added logs to all workflows.
https://warthogs.atlassian.net/browse/WD-21941

chore(CI): Make e2e runs more reliable

---

e2e/helpers/auth/backends/OIDC.ts
e2e/juju/model-access-control.spec.ts

- Update the test for changing model access to support Candid users. This was failing because refreshing the page in Candid logs you in as the previous user.
Passing run:
https://github.com/canonical/juju-dashboard/actions/runs/14960599944?pr=1963
https://warthogs.atlassian.net/browse/WD-22015

Update model access test to support Candid

---

e2e/base/actions.spec.ts
e2e/base/configure.spec.ts
e2e/base/models.spec.ts
e2e/base/secrets.spec.ts
e2e/helpers/actions/utils/give-access.ts
e2e/jimm/audit-logs.spec.ts
e2e/jimm/rebac.spec.ts

Add tests that controls aren't displayed for read-only permissions.
https://warthogs.atlassian.net/browse/WD-20949
Passing run:
https://github.com/canonical/juju-dashboard/actions/runs/15010802849/job/42179029947?pr=1967

chore(ci): add read-only tests

---

e2e/base/actions.spec.ts
e2e/base/auth-validation.spec.ts
e2e/base/configure.spec.ts
e2e/base/models.spec.ts
e2e/base/secrets.spec.ts
e2e/helpers/actions/deployApplication.ts
e2e/helpers/auth/backends/Candid.ts
e2e/helpers/auth/backends/Local.ts
e2e/helpers/auth/backends/OIDC.ts
e2e/helpers/objects/application.ts
e2e/helpers/objects/model.ts
e2e/jimm/audit-logs.spec.ts
e2e/jimm/rebac.spec.ts
e2e/juju/model-access-control.spec.ts
e2e/juju/web-cli.spec.ts
e2e/utils/addFeatureFlags.ts
e2e/utils/index.ts

- Use the URLs defined in the dashboard in the e2e tests to make them more easily to change in one place.
- Automatically add the feature flag.

chore(ci): use urls definition and automatically add feature flags

---

.github/workflows/actions.yml
.github/workflows/e2e-jimm-k8s-charm-oidc-auth.yml
.github/workflows/e2e-juju-k8s-charm-local-auth.yml
.github/workflows/e2e-juju-machine-charm-candid-auth.yml
.github/workflows/e2e-juju-machine-charm-local-auth.yml
.github/workflows/end-to-end.yml
.github/workflows/test.yml
.github/workflows/tics-coverage.yml

- Address code scanning alerts (https://github.com/canonical/juju-dashboard/security/code-scanning) by setting read-only permissions on workflows..
https://warthogs.atlassian.net/browse/WD-22134

chore(CI): set read permissions for workflows

---

e2e/juju/web-cli.spec.ts
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx

- Fix the origin that the macaroons are stored under when authenticating with the web CLI using Candid.
- Connect to a controller that uses Candid.
- Enter a command into the CLI e.g. `status`.
- A result should be returned from Juju.
https://warthogs.atlassian.net/browse/WD-22214

fix: make the commands websocket authentication work with candid

---

src/components/WebCLI/Output/Output.test.tsx
src/components/WebCLI/Output/Output.tsx
src/components/WebCLI/Output/consts.ts
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/components/WebCLI/_webcli.scss

- Fix the help link colour.
- close the terminal when closing the help
- adjust height of terminal help for mobile
- Go to a model and click the help icon next to the terminal input.
- The link in the help text should be readable.
- Click the help icon again and the help should close.
https://warthogs.atlassian.net/browse/WD-22301
Link colour before fix:

fix: small visual glitches in web CLI

---

src/components/JujuCLI/JujuCLI.test.tsx
src/components/JujuCLI/JujuCLI.tsx
src/components/JujuCLI/index.ts
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx

- Wrap the WebCLI component in a new `JujuCLI` component.
- Move selectors/hooks get model/controller data for the CLI out of EntityDetails and into the new component.
- Connect to a local Juju.
- Go to a model.
- Check you can run CLI commands for that model.
https://warthogs.atlassian.net/browse/WD-22423

refactor: wrap WebCLI in a new component

---

src/pages/ControllersIndex/ControllerChart/ControllerChart.test.tsx
src/pages/ControllersIndex/ControllerChart/ControllerChart.tsx

- Correct controller percentage calculation
- Pull code
- Click on controllers tab
- Verify that the percentages add up to 100%
I also decided to use `Math.round` instead of `Math.trunc`, since the fractional component was already being discarded. `Math.round` will help the totals add to 100% in more situations (such as the 33% and 66% example in the screenshots below).

fix: correct controller overview chart percentages

---

HACKING.md
src/components/JujuCLI/JujuCLI.test.tsx
src/components/JujuCLI/JujuCLI.tsx
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx

- Moved dashboard-specific code like the `useAnalytics` and the `useStore` hooks out of the WebCLI
- Corrected a typo in `HACKING.md`
We are moving code strictly tied to the dashboard out of the WebCLI component to reduce tight coupling of the two. This is to aid in making the WebCLI component a standalone project someday.
- Login to the dashboard
- Go to Model details page and expand the WebCLI
- Try using it with a couple of commands, clicking help, etc. Everything should work fine.
https://warthogs.atlassian.net/browse/WD-22424

refactor: move dashboard-specific code out of WebCLI

---

src/components/EntityInfo/EntityInfo.tsx
src/components/TruncatedTooltip/TruncatedTooltip.tsx
src/hooks/useModelAccess.test.tsx
src/hooks/useModelAccess.ts
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/store/general/selectors.test.ts
src/store/general/selectors.ts

- Fetch the user's relations to a model and use them to display their model access entitlement on the model details page.
- Turn on ReBAC with `?enable-flag=rebac`.
- Go to a model and on the left hand side you should see your access.
https://warthogs.atlassian.net/browse/WD-19884

feat: fetch and display the ReBAC model access

---

src/components/WebCLI/Output/Output.test.tsx
src/components/WebCLI/Output/Output.tsx
src/components/WebCLI/Output/consts.ts
src/components/WebCLI/Output/types.ts
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/components/WebCLI/_webcli.scss

- Display the previous commands and their responses in the web CLI.
- Go the web CLI in a model.
- Run a couple of commands and you should see that the commands and their responses are displayed in the scrollback.
https://warthogs.atlassian.net/browse/WD-22814

feat: display full scrollback in web CLI

---

.github/workflows/actions.yml
actions/package.json
actions/src/lib/changelog.test.ts
actions/src/lib/changelog.ts
actions/src/lib/git.ts
actions/src/lib/github/index.ts
actions/src/lib/github/pull-request.ts
actions/src/lib/github/repository.ts
actions/src/lib/github/types.ts
actions/src/lib/index.ts
actions/src/lib/util.ts
actions/src/lib/versioning/branch.test.ts
actions/src/lib/versioning/branch.ts
actions/src/lib/versioning/index.ts
actions/src/lib/versioning/labels.test.ts
actions/src/lib/versioning/labels.ts
actions/src/lib/versioning/severity.test.ts
actions/src/lib/versioning/severity.ts
actions/src/lib/versioning/types.ts
actions/tsconfig.json
actions/vite.config.ts
eslint.config.mjs
yarn.lock

- tweak eslint rules to remove conflicting rules
- remove un-needed `actions/setup-node` from renovate step (this isn't needed as the renovate action provides it's own NodeJS instance, and dashboard code isn't being run)
- implement utilities for future actions:
- `lib/github`: Abstractions over `Octokit` (Github REST API) for easy interactions with repositories and pull requests
- `lib/versioning`: Collection of methods relating to calculating and resolving release versions, including translating to/from pull request labels, parsing release branch names, and detecting version conflicts
- `lib/changelog`: Methods for building and parsing changelogs
- `lib/git`: Basic abstraction over simple git operations, intended to be slightly nicer then `exec('git ... ')` (and easier to mock too) …

feat(actions): common utilities

---

src/components/JujuCLI/JujuCLI.test.tsx
src/components/JujuCLI/JujuCLI.tsx
src/components/WebCLI/Output/types.ts
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/store/juju/types.ts
src/store/middleware/check-auth.ts
src/testing/factories/juju/juju.ts

- Support storing the history for each model.
- Store the history in Redux.
- Recreate the history when revisiting a model.
- Enter a command in the CLI.
- Navigate away from the model details and then back again and open the CLI and it should display the previous output.
https://warthogs.atlassian.net/browse/WD-22422

feat: persist CLI history

---

src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/connection.ts
src/components/WebCLI/types.ts

- Reconnect the CLI websocket when sending a new command if it has closed.
- Display an error if it can't reconnect.
What I did to test this was:
- Add `window.conn = conn;` after this line: https://github.com/canonical/juju-dashboard/blob/main/src/components/WebCLI/WebCLI.tsx#L166.
- Go to a model and enter a command and the response should be displayed.
- In your dev tools console run `conn.disconnect()`.
- In the web cli submit a new command and the result should be displayed.
- In your dev tools open the device simulator and set Throttling to Offline.
- In your dev tools console run `conn.disconnect()`.
- Submit and new command in the web CLI and it should display a connection error.
https://warthogs.atlassian.net/browse/WD-22420

feat: reconnect the CLI websocket when sending new commands

---

src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.tsx.snap
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/pages/ModelsIndex/ModelsIndex.tsx
src/urls.ts

- Updated old URLs to use documentation.ubuntu.com/*
- Moved all external URLs to `externalURLs`
- Check that all these new URLs work and are leading to expected pages
https://warthogs.atlassian.net/browse/WD-23693

chore: update outdated URLs with new ones

---

charms/k8s-charm/build.sh
charms/k8s-charm/metadata.yaml

- Update metadata for k8s charm to include `upstream-source` field
This field isn't actually used by charmcraft directly, but it's relied on for other automations, including the `publish-charm` action of [canonical/charming-actions](https://github.com/canonical/charming-actions). The action uses this field to query the local Docker image repository in order to push the image to Charmhub, so it must match whatever is used in the build script.

fix(k8s-charm): `upstream-source` for docker image

---

actions/src/lib/git.ts

Fix https://github.com/canonical/juju-dashboard/security/code-scanning/31

fix: make `Git.exec` private to prevent second-order code execution

---

src/components/JujuCLI/JujuCLI.tsx

Fixes https://github.com/canonical/juju-dashboard/security/code-scanning/32

use `replaceAll` instead of `replace` to catch every instance of replaced values

---

HACKING.md

- Updated the `HACKING.md` with latest steps to restart a local JIMM environment.
This change was needed as the controllers needed to fetch the correct public key from JIMM. Without this, any operation in controller context threw the following error:
They were probably using the public key that was generated and stored in Vault rather than the initial one stored in Postgres.
https://warthogs.atlassian.net/browse/WD-25613

chore: Update docs for restarting local JIMM setup

---

.github/workflows/release.yml

- Publish built k8s image to ghcr on release
- Successful run (manually triggered): https://github.com/canonical/juju-dashboard/actions/runs/17147765838/job/48647243767
- ghcr entry: https://github.com/canonical/juju-dashboard/pkgs/container/juju-dashboard
In place of #2051

feat: publish docker image to ghcr

---

.github/actions/run-playwright/action.yml
.github/workflows/e2e-jimm-docker-keycloak.yml
e2e/helpers/auth/backends/Keycloak.ts

This PR makes some fixes to the `run-playwright` action. Each fix below corresponds to 1 commit.
1. Set the correct working-directory for steps that use `run` and need files from the repo. The default working-directory when executing an action is the original workflow's directory i.e. if we call `run-playwright` from a jimm workflow the current directory is the checked out jimm repo and commands like `yarn install` fail because `yarn.lock` is unavailable.
2. Related to the above, when running the `setup-node` action, if we specify `cache: "yarn"` we need to specify `cache-dependency-path` to point to the `yarn.lock` file which is not available in the current dir. Unfortunately when I tried to specify the path I encountered the error `Relative pathing '.' and '..' is not allowed` so I've …

test: update run playwright action and keycloak backend e2e test fix

---

.github/workflows/create-cut-pr.yml
.github/workflows/create-release-pr.yml

For the actions that create a PR, use the `pull_request_target` event so that they can run with write permissions when triggered by pull requests that originate from a fork.

fix(ci): use `pull_request_target` for PR actions

---

e2e/fixtures/setup.ts
package.json
src/store/middleware/model-poller.ts
src/store/store.ts
vite.config.ts
yarn.lock

- remove `vite-plugin-node-polyfills`
- Ensure `identityProviderURL` is set in `config.local.js`, so that Candid is used
- `yarn start`
- Login with Candid
- `yarn build`
- `cp -f public/config.local.js build/config.js`
- `yarn vite preview`
- Login with Candid
Vite will inject `process.env.NODE_DEBUG` into the global scope in development, and will replace all occurrences during build. Ideally the dependency would use `import.meta` instead so vite could do this automatically, but it's quite old and unmaintained.
Will close #2055, close #2054 and close #1994 as those deps are removed.

fix: alternate workaround for `node-util`, to remove `vite-plugin-node-polyfills`

---

.github/workflows/tics-coverage.yml

- Enable running the tics workflow manually.

chore(CI): allow manually running TICS

---

src/store/juju/reducers.test.ts
src/store/juju/slice.ts

- Fixed the bug where a deleted model still appeared in the models list until the dashboard was reloaded
- Add one model
- Verify that it is available on the dashboard's models list page
- Delete it
- Without reloading the dashboard, check with the network tab that the deleted model is removed as soon as the `listModels` endpoint is polled next
- Do the same with more than one model added
- Do the same with multiple models deleted at once
https://warthogs.atlassian.net/browse/WD-26700

fix: Deleted models are not updated

---

eslint.config.mjs

- disable booleans for prefer-nullish-coalescing otherwise optional booleans are required to use nullish coalescing, but `isA ?? isB` is not the same thing as `isA || isB`.

chore(lint): disable booleans for prefer-nullish-coalescing

---

.github/actions/setup-machine-charm/action.yml
e2e/helpers/auth/Users.ts
e2e/helpers/auth/backends/Candid.ts
e2e/helpers/auth/backends/Keycloak.ts
e2e/helpers/auth/backends/Local.ts
e2e/helpers/auth/backends/OIDC.ts
e2e/jimm/rebac.spec.ts
e2e/utils/addFeatureFlags.ts
src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/WebCLI/WebCLI.test.tsx
src/hooks/useAnalytics.test.ts
src/hooks/useLocalStorage.test.ts
src/hooks/useModelAttributes.test.ts
src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
src/pages/Permissions/Permissions.test.tsx
src/pages/Permissions/Permissions.tsx
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/setup.ts
src/utils/analytics.test.ts
src/utils/isFeatureFlagEnabled.test.ts

- Check rebac permissions when using JIMM without needing to enable the flag (ReBAC Admin is still behind the flag).
- Connect to JIMM and make sure you don't have the rebac feature flag enabled.
- Check that the Permissions item is not in the side nav.
- Check that permissions are checked (i.e. you have audit logs in the side nav, have model access buttons etc.)
- Enable the rebac flag and the permissions item should appear in the side nav.
https://warthogs.atlassian.net/browse/WD-28065

feat: enable rebac permissions checking
