.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Copy over our template files for new Issues and Pull Requests.

Add team Github templates

---

.prettierrc.json
src/App.js
src/App.test.js
src/components/Nav/Nav.js
src/components/Nav/Nav.test.js
src/index.js
src/serviceWorker.js

Remove Prettier override config
- Pull code
- Close your eyes and just rip off that sticky plaster Jeff

Remove Prettier override config

---

package.json
src/index.js
src/juju/index.js
yarn.lock

When starting the application, asynchronously connect to JAAS, present the user the macaroon login link and then list their models on successful login in the browser console.
- Pull code
- The browser console will have a link to click to log in, do so.
- After a moment it'll list your models in the browser console.

Add jujulib and connect to JAAS on load.

---

.env
src/juju/index.js

Create .env file and add the REACT_APP_CONTROLLER_URL to it.
- Pull code
- In the console it should present you with a login URL.

Create .env file and add the REACT_APP_CONTROLLER_URL to it.

---

src/App.js
src/index.js
src/scss/_layout.scss
src/scss/index.scss

Tweak side nav designs to match designs
- Pull code
- Check layout sidebar is full height

Tweak side nav designs to match designs

---

README.md

Basic update to README
- Pull code
- Sanity check text

Basic update to README

---

package.json
src/components/Nav/Nav.test.js
src/setupTests.js
yarn.lock

Switch to using Enzyme for testing
- Pull code
- Run `./run clean && ./run test`
- Verify no errors
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/798

Switch to using Enzyme for testing

---

src/App.js
src/components/ErrorBoundary/ErrorBoundary.js
src/components/ErrorBoundary/ErrorBoundary.test.js

Simple error boundary
- Pull code
- Throw an error in one of the components and verify the error notification appears

Simple error boundary

---

.github/workflows/assignee-to-reviewer-action.yml

Add simple Github Action to request PR reviews from assignees. 
Ref: https://github.com/marketplace/actions/github-action-for-assignee-to-reviewer

Add simple Github action to request PR reviews from assignees

---

src/App.js
src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/PrimaryNav.test.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/SecondaryNav/SecondaryNav.js
src/components/SecondaryNav/SecondaryNav.test.js
src/components/SecondaryNav/__snapshots__/SecondaryNav.test.js.snap
src/components/SecondaryNav/_secondary-nav.scss
src/scss/_layout.scss
src/scss/index.scss

- Abstract secondary nav out to a component
- Hard-code `is-selected` style until routing is implemented
- Rename `<Nav>` to `<PrimaryNav>`
- Add external links from Vanilla so icons show in Primary Nav
- Pull code
- Verify everything is as expected
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/799

Update secondary nav to match designs

---

.eslintrc
package.json
src/index.js
src/juju/actions.js
src/juju/actions.test.js
src/juju/index.js
src/juju/reducers.js
src/reducers/actions.js
src/reducers/root.js
yarn.lock

Add model list into the redux store
- Pull code
- Click the link in the console to log in
- After a few moments check the redux console you should have the models in state.

Add model list into the redux store

---

src/components/TableSet/TableSet.js
src/components/TableSet/__snapshots__/TableSet.test.js.snap

Do not use index for list keys
- Pull code
- Check app loads correctly without error
- Verify linting passes
Fixes #28

Do not use index for list keys

---

.eslintrc
package.json
yarn.lock

Add hooks linting
- Pull code
- Run `./run exec yarn run eslint-check`
Related https://github.com/canonical-web-and-design/jaas-dashboard/issues/26

Add hooks linting

---

.eslintrc
package.json
yarn.lock

It's already part of CRA Eslint config.

Revert "Add hooks linting"

---

src/index.js
src/juju/actions.js
src/juju/index.js
src/juju/reducers.js
src/reducers/root.js

Fetch the model status for the list of models returned by modelList and then store that data in the Redux under the model.
- Pull code
- Click the link to log into the controller and then switch to redux devtools
- You will see the model status values being updated.

Fetch model statuses and store in Redux

---

.github/main.workflow
.github/workflows/assignee-to-reviewer-action.yml

I was not previously using them correctly - this should now work.

Fix up Github Actions

---

src/components/App/App.js
src/components/TableList/TableList.js

Display the model data in the table format from the data retrieved from the controller stored in the Redux store.
- You'll want a number of juju models with a various number of applications/units/machines before starting to QA.
- Pull code
- Log in via the link in the browser console. 
- Now your model data should populate as it becomes available.

Display model data from Redux store.

---

.prettierignore
package.json
src/components/App/App.js
src/components/TableList/TableList.js
src/components/TableList/TableList.test.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/testing/complete-redux-store-dump.js
yarn.lock

Add tests for the model list table and add mock data for testing with the redux store.
- CI should pass

Add tests for model list table

---

.circleci/config.yml
.stylelintrc
package.json
src/components/Button/_button.scss
src/components/InfoPanel/_info-panel.scss
src/components/Layout/_layout.scss
src/components/SecondaryNav/_secondary-nav.scss
src/components/Shell/_shell.scss
yarn.lock

Add stylelint ✨
- Pull code
- Ensure CI tests pass

Add stylelint ✨

---

src/components/App/App.js
src/components/App/__snapshots__/App.test.js.snap

Routes all components in layout and add 404 component
- Pull code
- Open http://0.0.0.0:8036/mdoels/foo
- Verify all links in the sidebar render with header and sidebar
- Verify 404 component is displayed
Fixes #44

Routes all components in layout and add 404

---

src/app/actions.js
src/app/root.js
src/index.js
src/juju/index.js

Add the bakery VisitURL to the Redux store.
- Pull code
- Open the redux devtools and the root key should have a visit url
Fixes #59

Add VisitURL Redux

---

src/components/Terminal/Terminal.js
src/components/Terminal/setup-terminal.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

Switch the CLI to the model you're viewing the details of.
- Pull code
- Pick a model **you own** from the model list and click on it (there is a bug if you don't own the model)
- The terminal should switch to that model.

Switch the CLI to the model you're viewing

---

src/app/selectors.js
src/components/Terminal/Terminal.js
src/juju/actions.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

Show the model status details on the model details page. 
- Pull code
- Click on a model you own and it should show your model status.
- Navigate back to the model listing and click on a model you don't own. It should also show you the model status.
- Requires #70 to land first (contains code from #70).
- This is unstyled, that will be able to be done as a follow-up.

Show the model status using real data

---

src/app/selectors.js

Grab the macaroons from the new location in the bakery now that the bakery uses `localStorage`. 
- Pull code
- View the details of one of your models
- The terminal should connect as expected.
Fixes #80

Grab the macaroons from the correct storage location in the bakery.

---

Dockerfile
nginx.conf
package.json

Add nginx to serve on staging and production
Update the dockerfile to work with the nginx
- Pull code
- Run `./run build`
- Open http://0.0.0.0:8080/
- Run `docker build --build-arg REVISION_ID=test --tag jaas-dashboard .`
- `docker run -d -p 8080:8036 jaas-dashboard`

Add nginx to serve in staging

---

src/components/ButtonToggle/ButtonToggle.js
src/components/ButtonToggle/ButtonToggle.test.js
src/components/ButtonToggle/__snapshots__/ButtonToggle.test.js.snap
src/components/ButtonToggle/_button-toggle.scss
src/components/FilterTags/FilterTags.js
src/components/FilterTags/FilterTags.test.js
src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
src/components/FilterTags/_filter-tags.scss
src/components/Header/Header.js
src/components/Header/Header.test.js
src/components/Header/__snapshots__/Header.test.js.snap
src/components/Header/_header.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Models.js
src/pages/Models/__snapshots__/Models.test.js.snap
src/pages/Models/_models.scss
src/scss/index.scss

Add static UI build for filtering of models
- Pull code
- Cross ref with designs
https://zpl.io/VqkEBGl

Add static UI build for filtering of models

---

nginx.conf

- ` docker build --build-arg REVISION_ID=test --tag prod-comms.docker-registry.canonical.com/dashboard.jaas.ai .`
- `docker run -d -p 8080:8036  prod-comms.docker-registry.canonical.com/dashboard.jaas.ai:latest`
- http://localhost:8080/_status/check
- should get ok

Add check endpoint

---

src/components/MainTable/Table/TableHeader/TableHeader.js
src/components/MainTable/Table/TableHeader/__snapshots__/TableHeader.test.js.snap
src/components/MainTable/Table/TableRow/TableRow.js
src/components/MainTable/Table/TableRow/__snapshots__/TableRow.test.js.snap
src/components/TableList/__snapshots__/TableList.test.js.snap
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

Remove superfluous role attributes
- Pull code

Remove superfluous role attributes

---

src/components/PrimaryNav/_primary-nav.scss

Fix sidebar hover bug
- Pull code
- Hover over primary nav and verify no wierd hover overlay
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/98

Fix sidebar hover bug

---

src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/PrimaryNav/_primary-nav.scss

Add sidebar icons
- Pull code
- Verify sidebar icons are [as in design](https://zpl.io/adYzyrn)
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/95

Add sidebar icons

---

src/scss/index.scss

Remove resolve Vanilla bug override
- Pull code
- Check no errors
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/113

Remove Vanilla bug override

---

src/app/actions.js
src/app/root.js
src/app/utils.js
src/components/TableList/TableList.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/components/TableList/_table-list.scss
src/components/UserIcon/UserIcon.js
src/components/UserIcon/UserIcon.test.js
src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
src/components/UserIcon/_user-icon.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Details/_model-details.scss
src/pages/Models/Models.js
src/scss/_status_icons.scss
src/scss/index.scss

Update Models listing styling
- Pull code
- Check user icon dropdown and logout button
Fixes #937

Update Models listing styling

---

src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
src/components/TableList/TableList.test.js
src/components/TableList/__snapshots__/TableList.test.js.snap
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Models.test.js
src/testing/complete-redux-store-dump.js

Update the mock test data
- CI should pass.
Fixes #115

Update test scaffold data

---

src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/PrimaryNav.test.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/PrimaryNav/_primary-nav.scss

Use NavLink to determine `.is-selected` state
- Pull code
- Check selected state in sidenav works as expected
Fixes #118

Use NavLink to determine is-selected state

---

src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/PrimaryNav.test.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/PrimaryNav/_primary-nav.scss

Add blocked notification in the sidebar
- Pull code
- Verify that the model indicator matches the number of blocked models

Add blocked notification in sidebar

---

src/components/Header/_header.scss
src/components/Layout/Layout.js
src/components/Layout/_layout.scss

Float the collapsible sidebar
- Pull code
- Go to models details page - roll over sidebar

Float the collapsible sidebar

---

src/pages/Models/Details/_model-details.scss

Models details icons should be rounded
- Pull code
- Go to model details page
- Verify icons are rounded
Fixes #149

Models details icons should be rounded

---

src/components/FilterTags/_filter-tags.scss
src/components/Layout/_layout.scss
src/components/PrimaryNav/_primary-nav.scss
src/components/Terminal/_terminal.scss
src/components/UserIcon/_user-icon.scss
src/pages/Models/Details/_model-details.scss

Use vf-animations mixin across all stylesheets
- Pull code
- Ensure no errors

Use vf-animations mixin across all stylesheets

---

src/scss/custom/_status_icons.scss

- Add missing colored icons
- Reduce size of icons
- Pull code
- Check out the all new icons
Fixes #161, Fixes #133

Add missing colored icons

---

src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

Swap Unit/Machine tables to match the design
- Pull code
- Check tables are swapped
Fixes #172

Swap tables on ModelDetails

---

src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/PrimaryNav/_primary-nav.scss

Sidebar style tweaks
- Pull code
- View sidebar and check icons and logo are aligned
https://zpl.io/bJgWNnr

Sidebar style tweaks

---

src/components/Header/_header.scss
src/components/Layout/Layout.js
src/components/Layout/Layout.test.js
src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/Layout/_layout.scss
src/components/PrimaryNav/_primary-nav.scss
src/components/Terminal/_terminal.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Models.js

Make sidebar, headers and terminal sticky
- Pull code
- View all the screens, see that the sidebar, headers and terminal are sticky
Fixes #127, Fixes #151, Fixes #152

Make sidebar, headers and terminal sticky

---

src/components/App/App.js
src/components/App/__snapshots__/App.test.js.snap
src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap

Selected nav should highlight nested urls
- Pull code
- Go to models detail page and verify that "Models" in the nav is selected

Selected nav should highlight nested urls

---

src/components/UserIcon/UserIcon.js
src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
src/components/UserIcon/_user-icon.scss

- Increase click area
- Close panel when user clicks away from panel
- Pull code
- Test statements above
Fixes #153

Improve user icon and dropdown panel

---

src/components/App/App.js
src/components/App/__snapshots__/App.test.js.snap
src/components/InfoPanel/InfoPanel.test.js
src/components/Routes/Routes.js
src/components/Routes/TestRoute.js
src/pages/Models/Details/ModelDetails.test.js

- Extract the routes of the application out into a separate component that generates them from a shared object.
- Created and implemented a TestRoute component which validates the supplied route to see if the application supports that route.
- Pull code
- The CI should pass
- The application should navigate as usual. Navigate to every page.
Fixes #82 
Fixes #86

Extract routes into separate component

---

src/pages/Models/Details/_model-details.scss

Tweak info panel breakpoint
- Pull code
- Go to models details and ensure wide topology at 1581px and above
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/987

Tweak info panel breakpoint

---

src/components/TableList/__snapshots__/TableList.test.js.snap
src/pages/Models/Models.test.js
src/testing/complete-redux-store-dump.js

Add a model with subordinates to test data.
- Pull code
- CI should pass

Add a model with subordinates to test data 

---

src/components/Button/_button.scss
src/components/ButtonToggle/ButtonToggle.js
src/components/ButtonToggle/__snapshots__/ButtonToggle.test.js.snap
src/components/ButtonToggle/_button-toggle.scss

Synchronise button styles
- Pull code
- View filters and button toggles and verify they look the same
Fixes #162

Synchronise button styles

---

src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap
src/pages/Models/Details/_model-details.scss

Added icons to the model details relations table and tweaked some of the columns to better fit the real data.
- Pull code
- View a model that has relations to make sure that the icons for the applications show up.
Fixes #150

Add relation icons

---

Dockerfile
nginx.conf

``` bash
DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=master --tag dashboard .
docker run -ti -p 8555:80 dashboard
```
Go to http://localhost:8555, see it work. Also go to http://localhost:8555/models, see it also work.

Multistage dockerfile

---

src/app/selectors.js
src/app/utils.js
src/components/FilterTags/FilterTags.js
src/components/FilterTags/FilterTags.test.js
src/components/FilterTags/__snapshots__/FilterTags.test.js.snap
src/components/FilterTags/_filter-tags.scss
src/components/ModelTableList/shared.js
src/pages/Models/Models.js

Populate filter panel with real data from models
- Pull code
- Click filter box in the header
- Verify all those real filters
Fixes #124

Populate filter panel with real data from models

---

src/components/Layout/__snapshots__/Layout.test.js.snap
src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/PrimaryNav.test.js
src/components/PrimaryNav/__snapshots__/PrimaryNav.test.js.snap
src/components/PrimaryNav/_primary-nav.scss
src/components/UserIcon/UserIcon.js
src/components/UserIcon/__snapshots__/UserIcon.test.js.snap
src/pages/Controllers/Controllers.js
src/pages/Logs/Logs.js
src/pages/Logs/__snapshots__/Logs.test.js.snap
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Models.js
src/pages/Models/_models.scss
src/pages/Usage/Usage.js
src/pages/Usage/__snapshots__/Usage.test.js.snap
src/scss/index.scss

- Add alpha label
- Remove placeholder link in components table 
- Remove Logs and Usage from the sidebar
- Tidy up model count in header
- Fix About link in the sidebar
- Point logo link at jaas.ai
- Add notifications to routes still under development
- Truncate unit workload status
- Pull code
- Check the above
Fixes #297,
Fixes #290,
Fixes #288,
Fixes #285

Responsive cleanup

---

src/components/InfoPanel/InfoPanel.js
src/components/InfoPanel/__snapshots__/InfoPanel.test.js.snap
src/components/InfoPanel/_info-panel.scss
src/components/Topology/Topology.js
src/pages/Models/Details/__snapshots__/ModelDetails.test.js.snap

For applications that have x and y coordinates defined in the model annotations, position them on the topology.
- Pull code
- View models you have with positional annotations
Fixes #239

Position applications in the topology with x,y coordinates

---

src/components/Topology/Topology.js

Draw relation lines on the Topology.
- Pull code
- View a few models with relations, lines should be drawn representing them.
Fixes #240
Fixes #311

Draw a relation lines on the Topology

---

package.json

There is an issue on staging #321 which I'm not able to debug because the build transpiles the async await code making it not possible to step through the code. 
This can be reverted or modified later once #321 has been resolved.
- Pull code
- The app should work as expected, but staging after landing will show the change.

Set browserslist production to latest

---

src/juju/index.js

Add error object to error message.
- Pull code
- It should work as usual.
This isn't really possible to QA unless you just happen to get a model that refuses the connection.
Fixes #344

Add error object to error message.

---

src/components/FilterTags/FilterTags.js
src/components/FilterTags/FilterTags.test.js
src/components/FilterTags/_filter-tags.scss

Add filtering interactions to drop-down panel
- Pull code
Related #125

Add filtering interactions to drop-down panel

---

src/components/FilterTags/FilterTags.js
src/components/FilterTags/FilterTags.test.js
src/pages/Models/Models.test.js

Add query params for active filters on the models view
- Pull code
- Add and remove filters and verify that URL reflects correct changes.
Related #148

Add query params for active filters on the models view

---

src/components/Filter/Filter.js
src/components/Filter/_filter.scss
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js

Add view filtering to models details pages
- Pull code
Fixes #334

Add view filtering to models details pages

---

src/app/selectors.js
src/components/UserMenu/UserMenu.js
src/components/UserMenu/UserMenu.test.js
src/components/UserMenu/__snapshots__/UserMenu.test.js.snap

Add active user name to settings header
- Pull code
- Settings header should display your username
Fixes #365

Add active user name to settings header

---

src/components/FilterTags/FilterTags.js
src/components/FilterTags/FilterTags.test.js
src/components/FilterTags/_filter-tags.scss
src/components/ModelGroupToggle/_model-group-toggle.scss

Switch filter tags input to a button
- Pull code
- Clicky the button and verify all works as expected
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1081

Switch filter tags input to a button

---

public/index.html

Load config.js from the root host
- Pull code
- Load the application from paths that aren't `/` and it should load
Fixes #380

Load config.js from the root host

---

src/pages/Models/Details/ModelDetails.js

Hide status filters in Model Details
- Pull code
- View model details and verify status filters are hidden

Hide status filters in Model Details

---

src/components/InfoPanel/_info-panel.scss
src/components/Topology/Topology.js

Make the Topology responsive
- Pull code
- Go to a model details
- Check that the topology renders correctly
- Resize your screen until the panel reduces in size
- See that the toplogy is responsive
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/325

Make the Topology responsive

---

public/config.js.go
src/index.js

When the dashboard is being served by the Juju controller then provide a config template that it can populate with the necessary values.
This can't yet be QA'd except by me so I can demo it if you like.

Povide config template file for Juju core

---

src/components/Terminal/Terminal.js
src/components/Terminal/_terminal.scss

Added ability to drag to resize terminal on model details pages
- Pull code
- Go to model details page and drag the top of terminal window

Resize terminal

---

src/components/FilterTags/FilterTags.js
src/components/InfoPanel/InfoPanel.js
src/components/Routes/Routes.js
src/components/UserMenu/UserMenu.js
src/hooks/useAnalytics.js

Move and rename analytics hook
- Pull code
- Move and rename analytics hook
Fixes #399

Move and rename analytics hook

---

src/components/InfoPanel/InfoPanel.js

[List of work items including drive-bys]
- Pull code

Topology tweaks

---

renovate.json

Update renovate config to sync with other projects.
None necessary

Update renovate config to sync with other projects.

---

src/components/Layout/Layout.js

Add Discourse link
- Pull code
- Check banner links to correct Discourse post

Add Discourse link

---

src/components/Layout/Layout.js

Add missing “to” to release notification
- Check code

Add missing “to” to release notification

---

src/components/PrimaryNav/PrimaryNav.js

Add event tracking when clicking link to return to old GUI
- Pull code

Add event tracking when clicking link to return to old GUI

---

src/components/Layout/Layout.js
src/hooks/useLocalStorage.js

Use state to set localStorage for notification
- Pull code
- Dismiss release banner
- It should immediately disappear
- Refresh
- It should not return
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/457

Use state to set localStorage for notification

---

src/pages/Controllers/Controllers.js
src/pages/Controllers/__snapshots__/Controllers.test.js.snap

Add full stop and make affirmative action explicit.
- Pull code
- Assuming you don't have permission to see this page, you should see an error
- Sanity check copy suggestion

Add full stop and make affirmative action explicit.

---

src/components/PrimaryNav/PrimaryNav.js
src/components/PrimaryNav/_primary-nav.scss

Tweak hr styling
- Pull code
- Verify tweaked hr rules in sidebar match the nav
Fixes #485

Tweak hr styling

---

src/pages/Settings/Settings.js
src/pages/Settings/settings.scss

Refactor styling of the settings page
- Pull code
- Open http://0.0.0.0:8036/settings
- View new styling
Fixes #464

style(settings): Update styling of settings page

---

package.json
src/app/utils.js
src/components/InfoPanel/InfoPanel.js
src/components/InfoPanel/_info-panel.scss
src/components/LogIn/LogIn.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Details/_model-details.scss
src/pages/Models/Details/generators.js

There were a number of UI issues that needed resolving. See the details list for the full list of issues.
- Install the juju 2.8-rc2 snap
- `juju bootstrap` into a public cloud
- `juju deploy cs:bundle/canonical-kubernetes`
- `juju dashboard` and connect to that dashboard to accept the self-signed cert.
- take note of the ip address and u/p
- Open config.js and change: 
- `baseControllerURL` to the ip address and port (if any) from above.
- `isJuju` to `true`
- `identityProviderAvailable` to `false`
- `./run`
- Use the above u/p to log in. 
- View the model details for your `default` model which will contain the kubernetes bundle deployment.
Fixes #510 #511 #512 #513 #514 #516 #518 #519

Resolve a number of UI issues

---

README.md

Expand the readme to add instructions on accessing via nested vms.

Expand the readme to add instructions on accessing via nested vms.

---

README.md

Just some cleanups to the readme

formatting and cleanup.

---

README.md

This is meant to be a reasonable first start to these docs - I imagine that we'll expand and modify these over time.

Added 'Writing React components' and 'Writing tests' content to the README.

---

README.md

Document how to perform a release.

Document how to perform a release

---

.eslintrc
package.json
src/app/root.js
src/components/InfoPanel/InfoPanel.js
src/components/UserMenu/UserMenu.js
src/components/UserMenu/__snapshots__/UserMenu.test.js.snap
src/juju/reducer.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Models.test.js
src/ui/index.js
yarn.lock

We no longer use the `airbnb` rules as we use prettier.
There were also a few other plugins that were installed but never ran. This has enabled those and fixed the errors.
- Pull code
- The app should work as expected.

Fix lint config for installed dependencies.

---

.gitignore
src/index.js

Wait for the `config.js` file to load before bootstrapping the application.
- Pull code
- Does the application boot?
Fixes #584

Wait for config.js before bootstrap.

---

README.md
src/app/utils.js
src/components/ModelTableList/StatusGroup.js
src/pages/Controllers/Controllers.js

Use e.g. for example, not ex)
- Pull code
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/615

Use e.g. for example, not ex)

---

src/pages/Models/Details/_model-details.scss

Reduce the width of the name columns and increase the width of the status columns in details
- Pull code
- Go to a model details and see the name column in the tables are slightly smaller
- See that the status has more room.
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/649
| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/1413534/90263250-521e8e80-de47-11ea-916b-107238431c93.png) | ![image](https://user-images.githubusercontent.com/1413534/90263375-82662d00-de47-11ea-94a6-e2d51a962bbe.png) |

Reduce the width of the name in details

---

src/components/SlidePanel/SlidePanel.js
src/components/SlidePanel/_slide-panel.scss
src/pages/Controllers/Controllers.js

Make the slide panel slide
- Pull code
- Click 'Add a controller'
- The side panel should slide in and then slide out when closed

Make the slide panel slide

---

src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.js
src/pages/Models/Details/generators.js

Remove dud links
Sanity check code
Fixes #654

Remove dud links

---

src/pages/Controllers/Controllers.js

Fixes #656
Fix duplicate form field ids
- Pull code

Fix duplicate form field ids

---

src/pages/Controllers/_controllers.scss

Update controllers header element
- Pull code
- Verify spacing and colour tweaks
Fixes #689

Update controllers header element

---

src/components/Banner/Banner.js
src/components/Banner/Banner.test.js
src/components/Banner/_banner.scss
src/components/Layout/Layout.js
src/hooks/useOffline.js

Whipped up an offline banner this evening as an exercise in creating a custom hook - thoughts?
- View the demo
- Toggle your internet connection via dev tools or the [Work Offline Chrome extension](https://chrome.google.com/webstore/detail/work-offline/gcjdagaoojgeilcobhibkgbodajcojda?hl=en) 
- See the banner in action

Add an offline banner

---

src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/generators.js

As the data and designs are in flux for this feature this is an MVP to get the CMR and Offers rendered to the details pages.
- Follow [cmr-scenario-1 docs](https://juju.is/docs/cmr-scenario-1) to setup an environment with cross model relations
- Follow [developing while connected to a Juju controller](https://github.com/canonical-web-and-design/jaas-dashboard#developing-while-connected-to-a-juju-controller) to connect your local running instance of the dashboard to the remove environment created above.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1215

MVP to render the cross model relations and offers

---

package.json

Bumped version to 0.3.0 in preparation for the release.

Bump version number to 0.3.0

---

src/hooks/useWindowTitle.js
src/pages/Controllers/Controllers.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Details/ModelDetails.test.js
src/pages/Models/Models.js
src/pages/Models/Models.test.js
src/pages/NotFound/NotFound.js
src/pages/Settings/Settings.js

Add custom page titles
- Pull code
- Run through the site and verify page titles match the pages
Fixes #744

Add custom page titles

---

src/components/UserMenu/UserMenu.js

Conditionally load user menu so it's only shown if there is an active user
- Pull code
- Log out and verify user menu is not still displaying under login overlay
Fixes #751

Conditonally load user menu

---

.circleci/config.yml
.eslintrc
.gitignore
jsconfig.json
package.json
src/react-app-env.d.ts
tsconfig.json
yarn.lock

Enable Typescript
- Pull code
- Ensure all tests pass
Fixes #771

Enable Typescript

---

src/components/ModelTableList/shared.js

Check for status.since before splitting
- Pull code
- App should not crash in flames
Fixes #782

Check for status.since before splitting

---

src/components/ButtonGroup/ButtonGroup.test.tsx
src/components/ButtonGroup/ButtonGroup.tsx

Convert ButtonGroup to Typescript
- Pull code
- Verify every works as expected

Convert ButtonGroup to Typescript

---

package.json
src/animations/FadeIn.tsx
src/pages/Controllers/Controllers.js
src/pages/Models/Details/ModelDetails.js
src/pages/Models/Models.js
src/pages/Settings/Settings.js

Wrap pages in subtle FadeIn animation
- Pull code
- Click through each page

Wrap pages in subtle FadeIn animation

---

src/pages/Controllers/_controllers.scss
src/pages/Models/Details/_model-details.scss

Fix header alignment on models and controllers to make them consistent
Before:
After:
- Pull code
- Verify the above

Fix header alignment

---

package.json
src/app/utils.js

Check tag in `extractCredentialName` exists before splitting
- Pull code
Fixes #823

Check tag in extractCredentialName exists before splitting

---

package.json
yarn.lock

Bump @canonical/jujulib to 2.0.0-beta.4
- Pull code

Bump @canonical/jujulib to 2.0.0-beta.4

---

package.json
src/components/InfoPanel/InfoPanel.tsx
src/declarations/global.d.ts
yarn.lock

Convert InfoPanel to Typescript
- Pull code
- Convert InfoPanel to Typescript

Convert InfoPanel to Typescript

---

src/components/Header/Header.tsx

Revert function typing in header
- Pull code

Revert function typing in header

---

src/pages/Controllers/Controllers.js
src/pages/ModelDetails/ModelDetails.js

Make controller tables display conditional on content
- Pull code
- Check tables display correctly
Fixes #857

Make controller tables display conditional on content

---

src/components/Header/_header.scss
src/components/SlidePanel/_slide-panel.scss

Overlay panels over webcli, if enabled
- Pull code
- Enable webCLI, ensure panel actions accessible

Overlay panels over webcli, if enabled

---

src/layout/BaseLayout/BaseLayout.tsx

Update offline banner wording for consistency
- Pull code
- Sanity check wording

Update offline banner wording for consistency

---

src/components/Header/_header.scss
src/pages/ControllersIndex/ControllersIndex.js
src/pages/EntityDetails/_entity-details.scss

Improve the responsive navigation styling
- Load model details
- Scale your screen too small screen
- See that the header section matches [the new small-screen designs](https://zpl.io/bL6rrnY).
Fixes #890

Improve the responsive navigation styling

---

src/components/ButtonGroup/_button-group.scss
src/pages/ModelsIndex/_models.scss

Update button group styling
- Load the demo
- Click on a model
- Check the "Group by:" button group matches [the design](https://zpl.io/VQ6O47A)
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/889

Update button group styling

---

src/components/Breadcrumb/Breadcrumb.tsx
src/components/Breadcrumb/_breadcrumbs.scss
src/components/Header/_header.scss
src/components/PrimaryNav/_primary-nav.scss
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/Model/Model.test.js
src/pages/EntityDetails/_entity-details.scss
src/pages/ModelsIndex/_models.scss

Address the navigations design polish comments
- Check that all ticked design items have been addressed
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/898

Address the navigations design polish comments

---

src/app/utils/utils.js
src/components/ButtonGroup/ButtonGroup.test.tsx
src/components/ButtonGroup/ButtonGroup.tsx
src/components/EntityInfo/EntityInfo.tsx
src/components/FormikFormData/FormikFormData.test.js
src/components/FormikFormData/FormikFormData.tsx
src/hooks/useTableRowClick.tsx
src/pages/EntityDetails/App/App.test.js
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/Model/Model.js
src/pages/EntityDetails/_entity-details.scss
src/panels/_panels.scss
src/tables/tableHeaders.tsx
src/tables/tableRows.js

- Convert App.js to TypeScript.
- Convert tableHeaders.js to TypeScript.
- Clean up invalid call signature for `generateIdentityIdentifier`.
- Fix some types in ButtonGroup.tsx, EntityInfo.tsx.
- Created generic `FormikFormData` component to extract form change events from Formik forms.
- Converted the table rendering to be more fluid. The table column sizing fixes will come with the `ModularTable` update.
- Add checkbox to each unit row only in the App view.
- Add select-all checkbox to the header for the unit table only in the App view.
- Ask me for model access to `action-test` if you don't already have.
- Select the Select-All checkbox, it should select them all.
- De-select the Select-All checkbox, it should de-select them all.
- Select then de-select a single unit row.
- Select each …

Add checkbox column to the unit list.

---

package.json
yarn.lock

Bump the jaaslib to 0.6.1
- Check out demo and see things work as expected

Bump the jaaslib to 0.6.1

---

src/tables/tableHeaders.tsx
src/tables/tableRows.js

Display the version of an application correctly on the application list
- Check out the demo
- Add an application with a version and see that you see it in the model details
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/955
**This wrapping will be fixed with a change to the table styling in https://github.com/canonical-web-and-design/jaas-dashboard/pull/957**

Display the version of an application correctly on the application list

---

public/config.js
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/Unit/Unit.js
src/tables/tableHeaders.tsx
src/tables/tableRows.js

- Remove the models machines tab on k8s
- Hide the Machine switcher on application view on kubernetes
- Hide machine table on units view on k8s 
- Remove machine column from app view
- You will need K8s model so ask me for that or we can pair on the QA
- Check all the above items are addressed
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1721

Remove machines for k8s

---

package.json
src/pages/EntityDetails/App/App.test.js
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Unit/Unit.js
src/pages/EntityDetails/_entity-details.scss
src/pages/EntityDetails/counts.js
src/panels/ConfigPanel/ConfigPanel.tsx

- Do not fall over if app units value is null, like with subordinates without a relation.
- Wait for the unit data to load if accessing the page directly.
- Support unit names with dashes.
- Disable config save button when saving.
- Correct unit counts on the units listing page.
- Roll through the issues to ensure they have been resolved.
Fixes #946 
Fixes #947 
Fixes #948 
Fixes #949 
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1726

Fix a number of issues

---

package.json
src/juju/index.js
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx

- Send the proper unit ID format when executing actions.
- Support rendering charm names with multiple hyphens.
- Display the unit ID properly in the ActionsLog.
- I have a running controller with this dashboard, contact me for details.
- Can you execute actions and view the resulting action logs.
Fixes #981

Fix bug in executing and displaying actions in Juju 2.9

---

src/components/Banner/_banner.scss

Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/977
Fix close button position in the offline banner
- Pull code
- Toggle online/offline banner in small screens
- Close button should be positioned correctly
Fix close button position in offline banner

Fix close button position in the offline banner

---

README.md

Update readme to remove usage of the run script

Update readme to remove usage of the run script

---

src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/_entity-details.scss

- Added loading indicator to Action Logs page.
- View the Action Logs page for a model, it should show a spinner while the request is being made and then the table afterwards.

Add loading indicator to Action Logs page

---

.stylelintrc
src/app/selectors.js
src/app/utils/utils.js
src/components/Aside/Aside.tsx
src/components/Aside/_aside.scss
src/components/FormikFormData/FormikFormData.tsx
src/juju/actions.js
src/juju/index.js
src/pages/EntityDetails/EntityDetails.js
src/panels/ShareModelPanel/ShareModel.tsx
src/panels/ShareModelPanel/share-model.scss

Add new sharing user to model details
- Pull code
- Open a model
- Click the 'Share model' button in the InfoPanel
- Check that you can add/remove users
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1744,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1742,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1738.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1740,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1745

Add new sharing user

---

Dockerfile

Add build-essential for vanilla framework build.
- Does the app work?

Add build-essential for vanilla framework build.

---

package.json
src/components/ShareCard/ShareCard.tsx
src/components/ToastCard/ToastCard.test.tsx
src/components/ToastCard/ToastCard.tsx
src/components/ToastCard/_toast-card.scss
src/layout/BaseLayout/BaseLayout.tsx
src/panels/ConfigPanel/_config-panel.scss
src/panels/ShareModelPanel/ShareModel.tsx
yarn.lock

Add Toast notifications to sharing UI
- Go to model
- Open sharing panel
- Add new user / change an existing users access / delete a user
- See positive action toast
- Try to add a user which already exists
- See negative (error) toast

Add Toast notifications to sharing UI

---

src/pages/EntityDetails/Model/Model.js

Conditionally render sharing model access button only if access
- Pull code
- Click to models you now you have owner/admin/write access on and verify model access button appears under the info panel
- Click to model you do not have the above permissions on and verify the button does not appear
Fixes https://github.com/canonical-web-and-design/app-squad/issues/112

Conditionally render sharing model access button only if access

---

src/components/InfoPanel/InfoPanel.test.js
src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/CloudGroup.test.js
src/components/ModelTableList/ModelTableList.test.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/OwnerGroup.test.js
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/StatusGroup.test.js
src/components/ModelTableList/_model-table-list.scss
src/components/ModelTableList/shared.js
src/components/PanelHeader/PanelHeader.test.tsx
src/components/PanelHeader/PanelHeader.tsx
src/hooks/useModelStatus.js
src/pages/EntityDetails/_entity-details.scss
src/pages/ModelsIndex/_models.scss
src/panels/ShareModelPanel/ShareModel.tsx

Share from models index page on large and small screens
- Pull code
- Ensure you can open the correct model access panel from different screen widths
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1748,
Fixes https://github.com/canonical-web-and-design/jaas-dashboard/issues/1034

Share from models index page

---

src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.js
src/pages/EntityDetails/Model/Model.js

Check for model users before calling info otherwise the app can crash after a hard refresh
- Pull code
Fixes https://github.com/canonical-web-and-design/app-squad/issues/143

Check for model users before calling info

---

src/components/ShareCard/ShareCard.test.tsx
src/components/ShareCard/ShareCard.tsx
src/components/ShareCard/_share-card.scss
src/juju/index.js
src/panels/ShareModelPanel/ShareModel.tsx

Add status update to share component
- Pull code
- Open a model you have permission to admin access privileges on
- Change one of the dropdowns and verify status appears correctly
https://user-images.githubusercontent.com/505570/123952257-a9651900-d99d-11eb-9849-4ceb58694c00.mp4
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1741

Add status update to share component

---

src/app/check-auth.js
src/juju/actions.js
src/juju/index.js
src/juju/reducer.js
src/juju/types.ts
src/juju/watchers.ts
src/pages/EntityDetails/Model/Model.js

- Type the AllWatcher deltas .
- Dispatch the deltas.
- Placeholder file started for the `processDelta`.
This doesn't really do anything so no QA required. 
As long as the app doesn't explode when you use it.
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/173

Type AllWatcher deltas and setup dispatch of the deltas.

---

src/juju/types.ts
src/juju/watchers.ts

- Add support for the "remove" deltas.
- Simplify delta parsing code.
- The redux store should have all data available for the model
- When you remove an application it should also remove it from the store.

Add missing deltas and simplify delta parsing

---

src/juju/types.ts
src/pages/EntityDetails/App/App.tsx
src/tables/tableRows.js

There are some issues with how the delta's can sometimes arrive out of order and in which case the expected values aren't always available yet. This branch fixes that with some optional chaining and type updates.
It's not really possible to QA this as it's a spurious failure. But you can try deploying to an existing model while the dashboard is open looking at it and seeing if there are any failures.

Fix some issues related to data availability.

---

package.json
src/juju/model-selectors.ts
src/pages/EntityDetails/EntityDetails.js
src/pages/EntityDetails/EntityDetails.test.js
src/setupTests.js
src/testing/redux-factory.ts
yarn.lock

Convert the EntityDetails component to use the model watcher data.
- If you can view a model details then this is working as expected.

Convert EntityDetails to use the model watcher data

---

src/components/InfoPanel/InfoPanel.test.js
src/components/InfoPanel/InfoPanel.tsx
src/components/Topology/Topology.js
src/juju/model-selectors.ts
src/juju/types.ts
src/juju/watchers.ts
src/testing/redux-factory.ts

- Converted the InfoPanel and Topology components to use the new watcher data structure.
- Added a delta handler for the annotation delta events.
Make sure that the side InfoPanel is shown with the topology.

Convert the InfoPanel and Topology components to new watcher data structure

---

src/components/RadioInputBox/DescriptionSummary.test.js
src/components/RadioInputBox/DescriptionSummary.tsx

Support actions without a description
- Ask me for access to a model with a charm with actions without descriptions.
Fixes #1164

If no description is provided for an action don't try and render one.

---

renovate.json

Adopt the webteam renovate config while this project is receiving infrequent changes.
N/A

Use webteam renovate config

---

package.json

Bump the version to 0.9.3

---

.gitignore
README.md
public/index.html

- Provide a way to configure the dashboard locally while keeping a clean git tree.
- Follow the modified instructions in the readme to configure your dashboard.
- Run `git status` and your tree should be clean.

Add a local config file.

---

src/components/ButtonGroup/_button-group.scss
src/juju/index.js

- Fix setting config for an app.
- Click on a model -> click an app -> Click 'Configure' button.
- Change a value, click 'Save and apply' and then 'Yes, apply changes'.
- The form should save correctly.
- Refresh the page and the form should contain the new values.
Fixes: #1280.

Fix setting config for an app

---

src/components/ButtonGroup/_button-group.scss
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/TextAreaConfig.tsx
src/panels/ConfigPanel/__snapshots__/ConfigPanel.test.tsx.snap
src/panels/ShareModelPanel/ShareModel.test.tsx
src/panels/panels.test.tsx

Migrate simple panel tests to RTL.
Fixes: #1326.

WD-618 - Migrate simple panel tests to RTL

---

src/components/ButtonGroup/_button-group.scss
src/components/UserMenu/UserMenu.test.tsx

Migrate UserMenu to RTL.
Fixes: #1320.

WD-618 - Migrate UserMenu to RTL

---

src/components/ButtonGroup/_button-group.scss
src/components/ToastCard/ToastCard.test.tsx

Migrate ToastCard to RTL.
Fixes: #1319.

WD-618 - Migrate ToastCard to RTL

---

src/components/ButtonGroup/_button-group.scss
src/components/ShareCard/ShareCard.test.tsx

Migrate ShareCard to RTL.
Fixes: #1316.

WD-618 - Migrate ShareCard to RTL

---

src/components/ButtonGroup/_button-group.scss
src/components/PrimaryNav/PrimaryNav.test.tsx

Migrate PrimaryNav to RTL.
Fixes: #1312.

WD-618 - Migrate PrimaryNav to RTL

---

src/components/ButtonGroup/_button-group.scss
src/components/FormikFormData/FormikFormData.test.tsx

Migrate FormikFormData to RTL.
Fixes: #1303.

WD-618 - Migrate FormikFormData to RTL.

---

src/components/ButtonGroup/_button-group.scss
src/components/ContentReveal/ContentReveal.test.tsx

Migrate ContentReveal to RTL.
Fixes: #1301.

WD-618 - Migrate ContentReveal to RTL

---

src/components/ButtonGroup/ButtonGroup.test.tsx
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/_button-group.scss

Migrate ButtonGroup to RTL.
Fixes: #1297.

WD-618 - Migrate ButtonGroup to RTL

---

src/components/Breadcrumb/Breadcrumb.test.tsx
src/components/Breadcrumb/Breadcrumb.tsx
src/components/ButtonGroup/_button-group.scss

Migrate Breadcrumb to RTL.
Fixes: #1295.

WD-618 - Migrate Breadcrumb to RTL

---

src/components/Banner/Banner.test.tsx
src/components/Banner/Banner.tsx
src/components/ButtonGroup/_button-group.scss

Migrate Banner to RTL.
Fixes: #1293.

WD-618 - Migrate Banner to RTL

---

src/animations/SlideInOut.tsx
src/components/Aside/Aside.test.tsx
src/components/Aside/Aside.tsx
src/components/ButtonGroup/_button-group.scss

Migrate Aside to RTL.
Fixes: #1291.

WD-618 - Migrate Aside to RTL

---

src/components/ButtonGroup/_button-group.scss
src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/ModelTableList.test.tsx
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.js
src/components/ModelTableList/StatusGroup.test.tsx
src/components/ModelTableList/shared.js

Migrate ModelTableList and child components to RTL.
Fixes: #1307.

WD-618 - Migrate ModelTableList and child components to RTL

---

README.md
src/app/actions.js
src/app/general.js
src/app/selectors.js
src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/WebCLI/WebCLI.test.tsx
src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/store/middleware/model-poller.test.ts
src/store/store.ts
src/testing/complete-redux-store-dump.js
src/testing/redux-factory.ts
src/types.ts

- Rename root state (that's not actually the real root state, but a subsection of state) to 'general'.
- Pull code
- The UI should load as normal.
Fixes: https://warthogs.atlassian.net/browse/WD-912

WD-912 - Rename root state

---

.dockerignore
package.json
src/app/jimm-facade.js
src/juju/index.js
yarn.lock

- Update `@canonical/jujulib` imports
- See this PR

WD-694 - Update jujulib imports

---

src/async-limiter.d.ts
src/juju/actions.js
src/juju/api.ts
src/juju/reducer.js
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/ModelDetails/ModelDetails.tsx
src/panels/ActionsPanel/ActionsPanel.test.tsx
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/store/general/reducers.test.ts
src/store/general/selectors.test.ts
src/store/general/types.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/store/store.ts
src/testing/factories/juju/juju.ts
src/types.ts

Migrate Juju API methods to TypeScript.
https://warthogs.atlassian.net/browse/WD-1085

WD-1085 - Migrate Juju API methods to TypeScript

---

src/components/LogIn/LogIn.test.tsx
src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/juju/api.ts
src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/store/general/reducers.test.ts
src/store/general/selectors.test.ts
src/store/general/types.ts
src/store/middleware/model-poller.test.ts
src/testing/factories/general.ts
src/testing/factories/root.ts

- Create factories for general state.
- Update tests to use the new factories.
https://warthogs.atlassian.net/browse/WD-822

WD-822 - Create general state factories

---

src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/panels/RegisterController/RegisterController.tsx

Migrate RegisterController panel to TypeScript.
https://warthogs.atlassian.net/browse/WD-1401

WD-1401 - Migrate panels to TypeScript

---

src/hooks/useTableRowClick.tsx
src/juju/model-selectors.ts
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/tables/tableRows.tsx
src/testing/factories/juju/juju.ts
src/types.ts

Migrate table row utils to TypeScript.
https://warthogs.atlassian.net/browse/WD-1402

WD-1402 - Migrate table row utils to TypeScript

---

src/components/InfoPanel/InfoPanel.test.tsx
src/juju/types.ts
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/testing/factories/index.ts
src/testing/factories/juju/juju.ts
src/testing/factories/juju/model-watcher.ts

- Add model watcher factories.
- Update tests to use new factories.
https://warthogs.atlassian.net/browse/WD-2043

WD-2043 - Add model watcher factories

---

src/testing/factories/juju/juju.ts

- Add factories for model data (these factories aren't used yet).
https://warthogs.atlassian.net/browse/WD-1200

WD-1200 - Add factories for model data

---

src/components/ChipGroup/ChipGroup.tsx
src/components/utils.tsx
src/juju/api.ts
src/pages/EntityDetails/counts.ts
src/pages/ModelDetails/ModelDetails.tsx
src/panels/ActionsPanel/ActionsPanel.tsx
src/store/middleware/model-poller.ts
src/store/store.ts
src/tables/tableRows.tsx

- Remove TSFixMes and TODOs from migrating to test factories.
https://warthogs.atlassian.net/browse/WD-2115

WD-2115 - Test factories cleanup

---

src/juju/api.ts

Fix status responses with null annotations.
- I don't actually know how to get a null annotations response, I just hit this error today.
https://warthogs.atlassian.net/browse/WD-2426

WD-2426 - Fix status responses with null annotations

---

package.json
src/components/DonutChart/DonutChart.test.tsx
src/components/DonutChart/DonutChart.tsx
src/pages/ControllersIndex/ControllerChart/ControllerChart.test.tsx
src/pages/ControllersIndex/ControllerChart/ControllerChart.tsx
src/pages/ControllersIndex/ControllerOverview/ControllerOverview.tsx
yarn.lock

- Replace chart data with single props.
- Migrate donut chart to TypeScript.
Fixes: #567.
https://warthogs.atlassian.net/browse/WD-2575

WD-2575 - Improve chart props

---

src/components/ModelTableList/CloudGroup.js
src/components/ModelTableList/ModelTableList.test.tsx
src/components/ModelTableList/OwnerGroup.js
src/components/ModelTableList/StatusGroup.tsx
src/components/ModelTableList/shared.test.tsx
src/components/ModelTableList/shared.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/types.ts
src/store/juju/utils/models.ts
src/testing/factories/juju/juju.ts

Fix custom model filters.
- Pull code
- Go to the model list.
- Type something in the search box and hit enter.
- The model list should get filtered.
https://warthogs.atlassian.net/browse/WD-2928

WD-2928 - Fix custom filters

---

src/components/Breadcrumb/Breadcrumb.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/ModelTableList/shared.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/Routes/Routes.tsx
src/components/UserMenu/UserMenu.js
src/hooks/useTableRowClick.tsx
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
src/pages/ModelDetails/ModelDetails.tsx
src/pages/PageNotFound/PageNotFound.tsx
src/panels/RegisterController/RegisterController.tsx
src/urls.ts
src/utils/argPath.test.ts
src/utils/argPath.ts
src/utils/index.ts

- Add argPath util from [maas-ui](https://github.com/canonical/maas-ui/blob/main/src/app/utils/argPath.ts) with a modification to support relative paths.
- Add URL definition.
- Update paths to use the URL definition.
- Pull code
- Check that you can navigate around the app.
https://warthogs.atlassian.net/browse/WD-2882

WD-2882 - Add URL definition

---

src/components/WebCLI/Output.tsx
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/components/WebCLI/connection.js
src/components/WebCLI/connection.ts

- Remove timeouts from CLI tests.
https://warthogs.atlassian.net/browse/WD-3084
Fixes: #1064.

WD-3084 - Improve async CLI tests

---

src/juju/api.ts
src/juju/jimm-facade.ts
src/juju/types.ts
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/ModelDetails/ModelDetails.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/store/juju/slice.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts

- Annotate the connection type with the facades.
- Fix type errors.
- Pull code
- Even though these are mostly type changes, it's probably worth doing a quick check that the controllers, models etc. still load.
https://warthogs.atlassian.net/browse/WD-3191

WD-3191 - Add facade types

---

src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/juju/api.test.ts
src/juju/api.ts
src/pages/EntityDetails/Model/Model.test.tsx
src/panels/ShareModelPanel/ShareModel.test.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/utils/models.test.ts
src/testing/factories/juju/Clientv6.ts
src/testing/factories/juju/ModelManagerV9.ts
src/testing/factories/juju/juju.ts

- Added tests to some of the API methods.
- Added test factories and moved ModelManager factories to their own file.
https://warthogs.atlassian.net/browse/WD-3159

WD-3159 - Add some API tests

---

src/components/CharmIcon/CharmIcon.test.tsx
src/components/CharmIcon/CharmIcon.tsx
src/components/CharmIcon/index.ts
src/components/EntityIdentifier/EntityIdentifier.test.tsx
src/components/EntityIdentifier/EntityIdentifier.tsx
src/components/EntityIdentifier/index.ts
src/components/ModelTableList/CloudGroup.tsx
src/components/ModelTableList/OwnerGroup.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/RelationIcon/RelationIcon.test.tsx
src/components/RelationIcon/RelationIcon.tsx
src/components/RelationIcon/index.ts
src/components/Status/Status.test.tsx
src/components/Status/Status.tsx
src/components/Status/index.ts
src/components/utils.test.tsx
src/components/utils.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/tables/tableRows.tsx

- Add tests for utils.
- Move utils that were components to individual component files and add tests.
- Pull code
- Go to a model and check that icons are rendered for the apps and units.
https://warthogs.atlassian.net/browse/WD-3229

WD-3229 - Add tests for utils

---

src/components/ModelTableList/shared.tsx
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
src/pages/EntityDetails/Model/Model.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx

- Fix panels that weren't opening in in the built dashboard.
- Open the demo.
- Check that each panel opens:
- Go to the controller list and click "Register a controller"
- Go to the model list and click on a model and then click "Modify access"
- On a model page click on an application and then click "Configure"
- On the application page tick a unit and then click "Run action"

Fix production panels

---

src/components/ChipGroup/ChipGroup.tsx
src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/components/RelationIcon/RelationIcon.tsx
src/juju/api.test.ts
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Machine/Machine.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/pages/EntityDetails/Unit/Unit.test.tsx
src/pages/EntityDetails/counts.test.ts
src/pages/EntityDetails/counts.ts
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/utils/models.test.ts
src/tables/tableRows.tsx
src/testing/factories/juju/ClientV6.ts
src/testing/factories/juju/juju.ts

- Add tests for entity details components.
https://warthogs.atlassian.net/browse/WD-3452

WD-3452 - Entity details tests

---

package.json
src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/juju/api.ts
src/store/juju/types.ts
yarn.lock

- Handle no versions returned from the API.

Handle no version response

---

src/hooks/useAnalytics.test.ts
src/hooks/useAnalytics.tsx
src/hooks/useLocalStorage.test.ts
src/hooks/useLocalStorage.ts
src/hooks/useModelAttributes.test.ts
src/hooks/useModelStatus.test.tsx
src/hooks/useOffline.test.ts
src/hooks/useWindowTitle.test.ts
src/hooks/useWindowTitle.ts
src/pages/Settings/Settings.tsx

- Add tests for hooks.
https://warthogs.atlassian.net/browse/WD-3769

WD-3769 - Add hook tests

---

src/juju/watchers.test.ts
src/juju/watchers.ts
src/testing/factories/juju/model-watcher.ts

- Add delta processing tests.
https://warthogs.atlassian.net/browse/WD-3680

WD-3680 - Add watcher tests

---

src/index.test.tsx
src/index.tsx
src/store/general/types.ts

- Add tests for bootstrapping the app.
https://warthogs.atlassian.net/browse/WD-3564

WD-3564 - Add bootstrap tests

---

src/components/LogIn/LogIn.test.tsx
src/juju/api.test.ts
src/juju/api.ts
src/testing/factories/juju/Application.ts
src/testing/factories/juju/ModelManagerV9.ts
src/testing/factories/juju/jujulib.ts

- Add tests for remaining API methods.
https://warthogs.atlassian.net/browse/WD-3500

WD-3500 - Remaining API tests

---

src/components/App/App.test.tsx
src/components/App/App.tsx
src/components/ChipGroup/ChipGroup.test.tsx
src/components/InfoPanel/InfoPanel.test.tsx
src/components/InfoPanel/InfoPanel.tsx
src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/ModelTableList/shared.test.tsx
src/components/ModelTableList/shared.tsx
src/components/WebCLI/Output.tsx
src/components/WebCLI/WebCLI.test.tsx

- Add miscellaneous component tests.
https://warthogs.atlassian.net/browse/WD-3813

WD-3813 - Add component tests

---

src/juju/api.ts
src/layout/BaseLayout/BaseLayout.test.tsx
src/layout/BaseLayout/BaseLayout.tsx
src/pages/EntityDetails/App/App.test.tsx
src/panels/ActionsPanel/CharmActionsPanel.test.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/selectors.test.ts
src/store/juju/thunks.test.ts
src/store/middleware/check-auth.test.ts

- Add miscellaneous tests.
https://warthogs.atlassian.net/browse/WD-3768

WD-3768 - Add miscellaneous tests

---

src/components/ModelTableList/ModelTableList.test.tsx
src/components/WebCLI/WebCLI.test.tsx
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/Machine/Machine.test.tsx
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
src/pages/EntityDetails/Unit/Unit.test.tsx
src/pages/ModelDetails/ModelDetails.test.tsx
src/panels/ActionsPanel/ActionsPanel.test.tsx
src/panels/ActionsPanel/CharmActionsPanel.test.tsx
src/panels/CharmsPanel/CharmsPanel.test.tsx
src/testing/utils.tsx

- Add test render util.
- Replace render functions with the util.
https://warthogs.atlassian.net/browse/WD-3814

WD-3814 - test render util

---

src/components/Breadcrumb/Breadcrumb.test.tsx
src/components/ConnectionError/ConnectionError.test.tsx
src/components/EntityInfo/EntityInfo.test.tsx
src/components/InfoPanel/InfoPanel.test.tsx
src/components/LogIn/LogIn.test.tsx
src/components/ModelTableList/CloudGroup.test.tsx
src/components/ModelTableList/OwnerGroup.test.tsx
src/components/ModelTableList/StatusGroup.test.tsx
src/components/Panel/Panel.test.tsx
src/components/PanelHeader/PanelHeader.test.tsx
src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/UserMenu/UserMenu.test.tsx
src/components/hooks.test.tsx
src/layout/BaseLayout/BaseLayout.test.tsx
src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/ModelDetails/ModelDetails.test.tsx
src/pages/ModelsIndex/ModelsIndex.test.tsx
src/pages/PageNotFound/PageNotFound.test.tsx
src/pages/Settings/Settings.test.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/Panels.test.tsx
src/panels/RegisterController/RegisterController.test.tsx
src/panels/ShareModelPanel/ShareModel.test.tsx
src/testing/utils.tsx

- Update tests to use the render util.
https://warthogs.atlassian.net/browse/WD-3851

WD-3851 - Replace render with util

---

.github/workflows/actions.yml
codecov.yml

- Set up codecov.
https://warthogs.atlassian.net/browse/WD-3873

WD-3873 - Add codecov

---

src/store/store.ts

- Allow the redux store to be prefilled with mock data for snapshotting.

Support preloading redux data

---

src/components/ModelTableList/AccessButton/AccessButton.test.tsx
src/components/ModelTableList/AccessButton/AccessButton.tsx
src/components/ModelTableList/AccessButton/index.ts
src/components/ModelTableList/CloudCell/CloudCell.test.tsx
src/components/ModelTableList/CloudCell/CloudCell.tsx
src/components/ModelTableList/CloudCell/index.ts
src/components/ModelTableList/CloudGroup.tsx
src/components/ModelTableList/ModelDetailsLink/ModelDetailsLink.test.tsx
src/components/ModelTableList/ModelDetailsLink/ModelDetailsLink.tsx
src/components/ModelTableList/ModelDetailsLink/index.ts
src/components/ModelTableList/ModelSummary/ModelSummary.test.tsx
src/components/ModelTableList/ModelSummary/ModelSummary.tsx
src/components/ModelTableList/ModelSummary/index.ts
src/components/ModelTableList/OwnerGroup.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/ModelTableList/shared.test.tsx
src/components/ModelTableList/shared.tsx

- Make some shared table functions to be components.
- Split utils for extracting data from a model.
- Pull code
- Go to the model list.
- Check that data in the tables is unchanged.
https://warthogs.atlassian.net/browse/WD-3854

WD-3854 - split table utils

---

.gitignore
package.json
scripts/clean-files
src/components/Topology/Topology.tsx

- Update package.json, readme etc. with new repo.
https://warthogs.atlassian.net/browse/WD-3992
https://warthogs.atlassian.net/browse/WD-3993

WD-3992- Update git url

---

docs/HACKING.md

- Add hacking doc.
https://warthogs.atlassian.net/browse/WD-4027
https://warthogs.atlassian.net/browse/WD-4028
https://warthogs.atlassian.net/browse/WD-4029
https://warthogs.atlassian.net/browse/WD-4030
https://warthogs.atlassian.net/browse/WD-4031
https://warthogs.atlassian.net/browse/WD-4032
https://warthogs.atlassian.net/browse/WD-4033
https://warthogs.atlassian.net/browse/WD-4034
https://warthogs.atlassian.net/browse/WD-4038
https://warthogs.atlassian.net/browse/WD-4045

Add hacking doc

---

docs/RELEASING.md

- Add release instructions.
- Add QA instructions.
https://warthogs.atlassian.net/browse/WD-4039
https://warthogs.atlassian.net/browse/WD-4047

WD-4039 - Add release doc

---

docs/CONTRIBUTING.md

- Add contribution guide.
https://warthogs.atlassian.net/browse/WD-4040

WD-4040 - Add contribution guide

---

docs/multipass-microk8s.md

- Add doc for setting up Multipass, MicroK8s, Juju and the dashboard.
https://warthogs.atlassian.net/browse/WD-4026

WD-4026 - Add MicroK8s doc

---

src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/WebCLI/WebCLI.tsx
src/components/WebCLI/__snapshots__/WebCLI.test.tsx.snap
src/urls.ts

- Fix link to the Juju web CLI
Fixes: #1503 
https://warthogs.atlassian.net/browse/WD-5018

WD-5018 - fix: CLI docs link

---

src/components/RelationIcon/RelationIcon.tsx
src/juju/api.ts
src/juju/types.ts
src/juju/watchers.ts
src/pages/EntityDetails/Model/ActionLogs/ActionLogs.tsx
src/store/juju/selectors.ts
src/store/middleware/model-poller.ts
src/testing/factories/juju/ActionV7.ts
src/testing/factories/juju/Application.ts
src/testing/factories/juju/model-watcher.ts
src/types.ts

- Replace AdditionalProperties types with references from parent types so that changes to types will be picked up.

Remove AdditionalProperties types

---

Dockerfile

- Set the Yarn proxy settings to the values of the proxy env vars which are available in the demos environment.
- Go to the demo and see that it works! https://juju-dashboard-1530.demos.haus/
https://warthogs.atlassian.net/browse/WD-5130

WD-5130 - Fix demo proxy settings

---

.github/workflows/actions.yml
src/pages/Logs/audit-logs-fake-data.ts

- Add fake data for audit logs. This is contained in one file to make it easy to remove all fake data, types, factories etc.
https://warthogs.atlassian.net/browse/WD-5227

WD-5227 - Add fake audit log data

---

.github/workflows/actions.yml
src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.test.tsx
src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.tsx
src/pages/EntityDetails/Model/Logs/AuditLogs/index.ts
src/pages/EntityDetails/Model/Logs/Logs.test.tsx
src/pages/EntityDetails/Model/Logs/Logs.tsx
src/pages/EntityDetails/Model/Logs/_logs.scss
src/pages/EntityDetails/Model/Model.test.tsx
src/pages/EntityDetails/Model/Model.tsx
src/urls.ts

- Added model level audit logs view, nav item and route
https://warthogs.atlassian.net/browse/WD-5213

WD-5213 - feat: Model level Audit Logs view

---

src/components/AuditLogsTable/AuditLogsTable.test.tsx
src/components/AuditLogsTable/AuditLogsTable.tsx
src/components/AuditLogsTable/index.ts
src/components/ModelTableList/ModelDetailsLink/ModelDetailsLink.tsx
src/components/ModelTableList/StatusGroup.tsx
src/components/WebCLI/WebCLI.tsx
src/components/utils.tsx
src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.test.tsx
src/pages/EntityDetails/Model/Logs/AuditLogs/AuditLogs.tsx
src/pages/EntityDetails/Model/Logs/Logs.test.tsx
src/pages/EntityDetails/Model/Model.test.tsx
src/panels/ShareModelPanel/ShareModel.tsx
src/store/juju/selectors.ts
src/store/juju/utils/models.ts
src/utils/getUserName.test.ts
src/utils/getUserName.ts

- Added logs table to model logs view
https://warthogs.atlassian.net/browse/WD-5214

WD-5214 - feat: Add logs table to model logs view

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
src/components/PrimaryNav/PrimaryNavLink/index.ts
src/components/Routes/Routes.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
src/pages/Logs/Logs.test.tsx
src/pages/Logs/Logs.tsx
src/pages/Logs/index.ts
src/scss/index.scss
src/urls.ts

- Added top level audit logs view, nav link and route.
https://warthogs.atlassian.net/browse/WD-5210

WD-5210 - feat: Add top level audit logs view, nav link and route

---

src/juju/api.test.ts
src/juju/api.ts
src/juju/jimm-facade.test.ts
src/juju/jimm-facade.ts
src/juju/types.ts
src/pages/Logs/audit-logs-fake-data.ts
src/store/juju/actions.test.ts
src/store/juju/slice.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/factories/juju/jimm.ts

- Add support for fetching audit logs via the JIMM facade.
https://warthogs.atlassian.net/browse/WD-5217

Add audit logs jimm api

---

src/components/AutocompleteInput/AutocompleteInput.test.tsx
src/components/AutocompleteInput/AutocompleteInput.tsx
src/components/AutocompleteInput/index.ts
src/store/juju/selectors.ts

- Add a component that uses `datalist` to provide suggestions to an input.

Add AutocompleteInput component

---

src/store/juju/selectors.test.ts
src/store/juju/selectors.ts

- Fetch unique values from the audit events.

Add audit event selectors

---

src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.test.tsx
src/panels/ActionsPanel/CharmActionsPanel.test.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.test.tsx
src/panels/CharmsAndActionsPanel/CharmsAndActionsPanel.tsx
src/panels/CharmsPanel/CharmsPanel.test.tsx
src/panels/CharmsPanel/CharmsPanel.tsx

- Moved Panel component from CharmsAndActionsPanel to CharmsPanel and CharmActionsPanel.

refactor: Move Panel inside CharmsPanel and CharmActionsPanel

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.test.tsx
src/components/PrimaryNav/PrimaryNavLink/PrimaryNavLink.tsx
src/components/PrimaryNav/PrimaryNavLink/index.ts
src/components/Routes/Routes.tsx
src/pages/AdvancedSearch/AdvancedSearch.test.tsx
src/pages/AdvancedSearch/AdvancedSearch.tsx
src/pages/AdvancedSearch/index.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/urls.ts

Redo the PR https://github.com/canonical/juju-dashboard/pull/1570 to merge into the cross-model-queries repo.

Cross model queries page

---

.github/workflows/actions.yml

- Enable CI for the cross-model-queries branch.

Enable CI for the cross-model-queries branch.

---

src/pages/AdvancedSearch/AdvancedSearch.test.tsx
src/pages/AdvancedSearch/AdvancedSearch.tsx
src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
src/pages/AdvancedSearch/SearchForm/index.ts

- Add cross model search form
- Connect to staging.
- Type something into the search input and submit.
- You should see the query in the URL.
- Open the redux dev tools and you should see the dispatch to fetch the queries, and a response from the API.
https://warthogs.atlassian.net/browse/WD-5813

WD-5813 - Cross model search form

---

src/testing/factories/juju/jimm-types.ts
src/testing/factories/juju/jimm.ts

- Extended Cross Model Query Factory to include the ability to conditionally add ApplicationEndpoints, Applications, Machines and/or Model.
https://warthogs.atlassian.net/browse/WD-5860

WD-5860 - feat: Extend Cross Model Query Factory

---

src/juju/api.test.ts
src/juju/api.ts

Handle error strings when fetching the status.

Handle error strings when fetching the status.

---

package.json
src/juju/api.test.ts
src/juju/api.ts
yarn.lock

Merge main into the feature branch.

Merge main

---

src/pages/AdvancedSearch/SearchForm/SearchForm.test.tsx
src/pages/AdvancedSearch/SearchForm/SearchForm.tsx
src/store/juju/reducers.test.ts
src/store/juju/slice.ts

- Added copy JSON button
https://warthogs.atlassian.net/browse/WD-5819

WD-5819 - feat: Add copy JSON button

---

package.json
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx
yarn.lock

- 
- Perform a search.
- Check that you see the tree view when it loads (the styling will be changed in https://warthogs.atlassian.net/browse/WD-5821).
https://warthogs.atlassian.net/browse/WD-5820

WD-5820 - Add tree view

---

src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx

- Displayed relative date next to actual date.
https://warthogs.atlassian.net/browse/WD-5824

WD-5824 - feat: Display relative date next to actual date

---

src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.test.tsx
src/pages/AdvancedSearch/ResultsBlock/ResultsBlock.tsx

- Display a message if no results found.
https://warthogs.atlassian.net/browse/WD-5992

WD-5992 - feat: Display a message if no results found

---

src/juju/api.ts
src/juju/jimm/JIMMV3.test.ts
src/juju/jimm/JIMMV3.ts
src/juju/jimm/index.ts
src/juju/types.ts

- Set up versioned JIMM facades.
- Add facade tests.
- Connect to production JIMM.
- Check that you can load the dashboard and your models appear.

Versioned JIMM facades

---

src/juju/api.ts
src/juju/jimm/JIMMV3.test.ts
src/juju/jimm/JIMMV3.ts
src/juju/jimm/JIMMV4.test.ts
src/juju/jimm/JIMMV4.ts
src/juju/jimm/index.ts
src/juju/types.ts
src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
src/pages/AdvancedSearch/ErrorsBlock/ErrorsBlock.tsx
src/store/juju/slice.ts
src/store/juju/types.ts
src/store/middleware/model-poller.ts

- Move JIMM v4 functions to their own class.
- Check that the search still returns results.
https://warthogs.atlassian.net/browse/WD-6093

Add JIMM v4 class

---

src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/Routes/Routes.tsx
src/pages/AdvancedSearch/AdvancedSearch.test.tsx
src/store/general/actions.test.ts
src/store/general/reducers.test.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/general/slice.ts
src/store/general/types.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
src/testing/factories/general.ts

- Use the JIMM facade version to enable cross model search.
- Connect your dashboard to staging.
- Load the dashboard and check that the Advanced search link is in the sidenav.
- Connect your dashboard to JAAS.
- Check that the Advanced search link is NOT in the sidenav.
https://warthogs.atlassian.net/browse/WD-6219

WD-6219 - Enable cross model search with JIMM v4

---

.github/workflows/actions.yml
renovate.json

- Add renovate validation.
- Fix packageRules.
- Fixes: #833.
- https://warthogs.atlassian.net/browse/WD-6341

WD-6341 - Fix packageRules in renovate config

---

src/pages/EntityDetails/EntityDetails.test.tsx
src/pages/EntityDetails/EntityDetails.tsx
src/pages/ModelDetails/ModelDetails.test.tsx
src/pages/ModelDetails/ModelDetails.tsx

- Handle model connection timeout error and other types of errors in `ModelDetails`.
- https://warthogs.atlassian.net/browse/WD-6424
- Fixes: #1621

WD-6424 - feat: Handle model connection timeout

---

.github/workflows/actions.yml
renovate.json

- Use the apps renovate config.
- Remove actions config for the audit-logs branch.

Use the apps renovate config

---

src/components/ModelTableList/_model-table-list.scss
src/pages/ControllersIndex/ControllerOverview/_controller-overview.scss
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/ControllersIndex/_controllers.scss
src/pages/EntityDetails/_entity-details.scss
src/scss/custom/_tables.scss

- Remove min widths from tables.
- Remove horizontal scrolling from controller tables.
- Go to the controllers page.
- Check that the controllers table looks good at all screen sizes
https://warthogs.atlassian.net/browse/WD-7498

WD-7498 - Remove horizontal scrolling from controllers

---

src/pages/ControllersIndex/ControllersIndex.test.tsx
src/pages/ControllersIndex/ControllersIndex.tsx

- Removed "Access" column in controllers table.
- Verify that the "Access" column is missing from controllers table and that the rest of the columns have the expected content.
- https://warthogs.atlassian.net/browse/WD-7606

WD-7606 - feat: Remove "Access" column in controllers table

---

src/pages/EntityDetails/App/App.test.tsx
src/pages/EntityDetails/App/App.tsx
src/pages/EntityDetails/Machine/Machine.tsx
src/pages/EntityDetails/Unit/Unit.tsx
src/pages/EntityDetails/_entity-details.scss
src/tables/tableRows.tsx

- Make unit tables responsive.
- Go to a model.
- In the 'Applications' tab click on an app.
- Check that the units table appears OK at all screen sizes.
https://warthogs.atlassian.net/browse/WD-7503

WD-7503 - Make unit tables responsive

---

src/pages/EntityDetails/_entity-details.scss
src/scss/custom/_status_icons.scss
src/tables/tableRows.tsx

- Make local apps table responsive.
- Go to the applications tab in a model.
- Check that the local apps table appears OK at all screen sizes.
- Use the input to filter the applications.
- The table should now have checkboxes. Check that it looks good at all screen sizes.
https://warthogs.atlassian.net/browse/WD-7504

WD-7504 - Make local apps table responsive

---

src/pages/EntityDetails/_entity-details.scss

- https://warthogs.atlassian.net/browse/WD-7502
- Set up some models with [cross model integrations](https://github.com/canonical/juju-dashboard/blob/main/HACKING.md#setting-up-cross-model-integrations).
- Go to the applications tabs for the models that provide and consume the integrations.
- Check that the offers and remote apps tables appear OK at all screen sizes.
https://warthogs.atlassian.net/browse/WD-7502

WD-7502 - Make cross model tables responsive

---

src/components/ErrorBoundary/ErrorBoundary.tsx
src/index.tsx
src/store/middleware/model-poller.ts

- Enabled Sentry only if `analyticsEnabled` is `true`.
- https://warthogs.atlassian.net/browse/WD-7767

WD-7767 - feat: Enable Sentry only if analyticsEnabled is true

---

Dockerfile
public/config.demo.js
public/config.js
public/index.html

- Updated Juju Dashboard webteam demos to use JIMM demo controller.
- https://warthogs.atlassian.net/browse/WD-7720

WD-7720 - feat: Update Juju Dashboard webteam demos to use JIMM demo controller

---

package.json
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/store/juju/slice.ts
src/store/juju/thunks.ts
yarn.lock

- Update Jujulib to 5.0.0
- Handle new optional types from Jujulib.
https://warthogs.atlassian.net/browse/WD-8593

WD-8593 - handle optional juju types

---

src/components/AppLink/AppLink.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx

- Link to applications in the Secrets table.
- Add a secret to an application (e.g. `juju exec --unit mysql/0 -- secret-add foo=bar`).
- In the owner column it should have a link.
- Click the link and it should take you to the application.
https://warthogs.atlassian.net/browse/WD-8522

WD-8522 - Link to applications

---

src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx

- Add a button to copy secret IDs from the secrets table.
- Go to the secrets tab for a model.
- Hover the ID for a secret.
- Click the copy button that appears.
- Check that the ID was copied.
https://warthogs.atlassian.net/browse/WD-8396

WD-8396 - Copy secret IDs

---

src/components/WebCLI/Output.tsx
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/WebCLI.tsx
src/hooks/useInlineErrors.test.ts
src/hooks/useInlineErrors.ts

- Display connection and authentication errors in WebCLI
- https://warthogs.atlassian.net/browse/WD-8625

WD-8625 - feat: Display errors in WebCLI

---

src/hooks/useInlineErrors.test.ts
src/hooks/useInlineErrors.ts
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx

- Displayed get config and submit to juju errors in Config Panel.
https://warthogs.atlassian.net/browse/WD-8729

WD-8729 - feat: Display errors in Config Panel

---

src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/UserMenu/UserMenu.test.tsx
src/components/UserMenu/UserMenu.tsx
src/index.tsx
src/juju/api.test.ts
src/juju/api.ts
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx

- Display logout error in `UserMenu`.
- https://warthogs.atlassian.net/browse/WD-8825

WD-8825 - feat: Display error in UserMenu

---

src/components/secrets/SecretLabel/SecretLabel.test.tsx
src/components/secrets/SecretLabel/SecretLabel.tsx
src/components/secrets/SecretLabel/index.ts
src/juju/api.ts
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/SecretsPicker/SecretsPicker.tsx
src/panels/types.ts
src/store/juju/selectors.ts

- Display a confirmation to grant app access to secrets.
- Open the config panel for an app.
- Choose a secret for a text field.
- Save the form.
- After the confirmation you should be shown a confirmation for whether to grant access.
- Click Yes and the app should get granted.
https://warthogs.atlassian.net/browse/WD-8407

WD-8407 - config grant access

---

src/juju/apiHooks.test.tsx
src/juju/apiHooks.ts
src/utils/index.ts
src/utils/toErrorString.test.ts
src/utils/toErrorString.ts

- Combine common api hook handlers.
- Go to the secrets tab and check the secrets load.
- Check that you can perform write actions on the secrets.
- https://warthogs.atlassian.net/browse/WD-9028

WD-9028 - Dedupe API hooks

---

src/juju/api-hooks/application.test.tsx
src/juju/api-hooks/application.ts
src/juju/api-hooks/index.ts
src/juju/api.test.ts
src/juju/api.ts
src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx

- Move application API calls to hooks.
- Open the config panel.
- Make a change and save.
- Open the panel again and check that the value you changed was saved.
- https://warthogs.atlassian.net/browse/WD-9101

WD-9101 - application API hooks

---

src/juju/api-hooks/actions.test.tsx
src/juju/api-hooks/actions.ts
src/juju/api-hooks/index.ts
src/juju/api.test.ts
src/juju/api.ts
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx
src/panels/ActionsPanel/ActionsPanel.test.tsx
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel.test.tsx
src/panels/ActionsPanel/CharmActionsPanel.tsx

- Turn action calls into hooks.
- Go to the action log tab for a model and check that the logs load.
- Open the action panels and check that you can submit actions.
https://warthogs.atlassian.net/browse/WD-9100

WD-9100 - action API hooks

---

src/pages/AdvancedSearch/SearchForm/_search-form.scss
src/scss/_breakpoints.scss

- Handle sub-pixel media queries.
- Check the dashboard is still responsive.
- https://warthogs.atlassian.net/browse/WD-9168

WD-9168 - Handle sub-pixel media queries

---

package.json
src/components/secrets/SecretForm/SecretForm.test.tsx
src/components/secrets/SecretForm/SecretForm.tsx
src/juju/api.test.ts
src/juju/api.ts
src/juju/jimm/JIMMV4.ts
src/pages/ModelDetails/ModelDetails.tsx
src/panels/GrantSecretPanel/GrantSecretPanel.test.tsx
src/panels/GrantSecretPanel/GrantSecretPanel.tsx
src/panels/RemoveSecretPanel/RemoveSecretPanel.test.tsx
src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
src/store/juju/actions.test.ts
src/store/juju/reducers.test.ts
src/store/juju/slice.ts
src/store/middleware/check-auth.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
yarn.lock

- Update error handling after `jujulib` update to v6.
- https://warthogs.atlassian.net/browse/WD-9417

WD-9417 - feat: update error handling after jujulib update to v6

---

src/components/ChipGroup/_chip-group.scss
src/components/ModelTableList/ModelSummary/ModelSummary.tsx
src/components/WebCLI/_webcli.scss
src/juju/api.test.ts
src/juju/api.ts
src/pages/EntityDetails/_entity-details.scss
src/pages/ModelsIndex/_models.scss
src/scss/_utils.scss
src/scss/_vanilla-overrides.scss
src/scss/_variables.scss

- remove overrides that have been fixed in Vanilla
- Pull code
- Check nothing looks broken (particularly the tabs in model details).
https://warthogs.atlassian.net/browse/WD-11355

WD-11355 - fix: remove overrides that have been fixed in Vanilla

---

.github/workflows/tics-coverage.yml

- Add action to upload coverage report.
https://warthogs.atlassian.net/browse/WD-11352

WD-11352 - ci: add TICS reporting

---

src/components/LogIn/IdentityProviderForm/IdentityProviderForm.test.tsx
src/components/LogIn/IdentityProviderForm/IdentityProviderForm.tsx
src/components/LogIn/IdentityProviderForm/index.ts
src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/LogIn/UserPassForm/UserPassForm.test.tsx
src/components/LogIn/UserPassForm/UserPassForm.tsx
src/components/LogIn/UserPassForm/index.ts
src/components/LogIn/index.ts
src/components/LogIn/types.ts

- Removed nested components in `components/Login`.
- https://warthogs.atlassian.net/browse/WD-11588

WD-11588 - refactor: Remove nested components in components/Login

---

src/components/ModelTableList/StatusGroup/StatusGroup.test.tsx
src/components/ModelTableList/StatusGroup/StatusGroup.tsx
src/components/ModelTableList/StatusGroup/WarningMessage/WarningMessage.test.tsx
src/components/ModelTableList/StatusGroup/WarningMessage/WarningMessage.tsx
src/components/ModelTableList/StatusGroup/WarningMessage/index.ts

- Remove nested components in `StatusGroup`.
- https://warthogs.atlassian.net/browse/WD-11589

WD-11589 - refactor: remove nested components in StatusGroup

---

HACKING.md

- Add instructions for setting up the latest JIMM
- Follow the new docs instructions to set up JIMM. Note: when you get linked to the JIMM docs you should refer to the changes in this PR: https://github.com/canonical/jimm/pull/1224.
https://warthogs.atlassian.net/browse/WD-11677

WD-11677 - docs: add JIMM setup

---

src/pages/AdvancedSearch/CodeSnippetBlock/CodeSnippetBlock.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Label/Label.test.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Label/Label.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Label/index.ts
src/pages/AdvancedSearch/CodeSnippetBlock/Label/utils.ts
src/pages/AdvancedSearch/CodeSnippetBlock/Value/Value.test.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Value/Value.tsx
src/pages/AdvancedSearch/CodeSnippetBlock/Value/index.ts

- Remove nested components in `pages/CodeSnippetBlock
- https://warthogs.atlassian.net/browse/WD-11590

WD-11590 - refactor: remove nested components in CodeSnippetBlock

---

HACKING.md

- add instructions for setting up Juju with Candid
- Follow the instructions in the doc and check that you can log in to the dashboard.
https://warthogs.atlassian.net/browse/WD-12072

WD-12072 - docs: candid docs

---

src/pages/ControllersIndex/ControllersIndex.tsx

- Removed nested components in `pages/ControllersIndex`.
- https://warthogs.atlassian.net/browse/WD-11591

WD-11591 - refactor: remove nested components in ControllersIndex

---

src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/AppOffersTable.test.tsx
src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/AppOffersTable.tsx
src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/index.ts
src/pages/EntityDetails/Model/ApplicationsTab/AppOffersTable/types.ts
src/pages/EntityDetails/Model/ApplicationsTab/ApplicationsTab.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ContentRevealTitle/ContentRevealTitle.test.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ContentRevealTitle/ContentRevealTitle.tsx
src/pages/EntityDetails/Model/ApplicationsTab/ContentRevealTitle/index.ts
src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/RemoteAppsTable.test.tsx
src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/RemoteAppsTable.tsx
src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/index.ts
src/pages/EntityDetails/Model/ApplicationsTab/RemoteAppsTable/types.ts

- Removed nested components in `pages/EnitityDetails/Model/ApplicationsTab`.
- TODO: add tests.
- https://warthogs.atlassian.net/browse/WD-11592

WD-11592 - refactor: remove nested components in ApplicationsTab

---

src/panels/ActionsPanel/ActionsPanel.test.tsx
src/panels/ActionsPanel/ActionsPanel.tsx
src/panels/ActionsPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
src/panels/ActionsPanel/ConfirmationDialog/ConfirmationDialog.tsx
src/panels/ActionsPanel/ConfirmationDialog/index.ts
src/panels/ActionsPanel/ConfirmationDialog/types.ts
src/panels/ActionsPanel/types.ts

- Removed nested components in `ActionsPanel`.
- https://warthogs.atlassian.net/browse/WD-11664

WD-11664 - refactor: remove nested components in ActionsPanel

---

src/panels/ConfigPanel/ConfigPanel.test.tsx
src/panels/ConfigPanel/ConfigPanel.tsx
src/panels/ConfigPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
src/panels/ConfigPanel/ConfirmationDialog/ConfirmationDialog.tsx
src/panels/ConfigPanel/ConfirmationDialog/index.ts
src/panels/ConfigPanel/ConfirmationDialog/types.ts
src/panels/ConfigPanel/types.ts

- Removed nested components in `panels/ConfigPanel`.
- https://warthogs.atlassian.net/browse/WD-11666

WD-11666 - refactor: remove nested components in ConfigPanel

---

src/pages/EntityDetails/Model/Logs/ActionLogs/ActionPayloadModal/ActionPayloadModal.test.tsx
src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.test.tsx
src/panels/ActionsPanel/CharmActionsPanel/CharmActionsPanel.tsx
src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/ConfirmationDialog.test.tsx
src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/ConfirmationDialog.tsx
src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/index.ts
src/panels/ActionsPanel/CharmActionsPanel/ConfirmationDialog/types.ts
src/panels/ActionsPanel/CharmActionsPanel/index.ts

- Removed nested components in `CharmActionsPanel`.
- https://warthogs.atlassian.net/browse/WD-11665

WD-11665 - refactor: remove nested components in CharmActionsPanel

---

package.json

- Update dashboard version to `0.13.0` for upcoming release.
- https://warthogs.atlassian.net/browse/WD-13598

WD-13598 - build: update dashboard version to 0.13.0

---

HACKING.md

- Update `HACKING.md` to contain the correct updated file needed to be changed in JIMM.
- https://warthogs.atlassian.net/browse/WD-14825

WD-14825 - docs: update JIMM controller docs

---

src/juju/jimm/api.ts
src/juju/jimm/listeners.test.ts
src/juju/jimm/listeners.ts
src/juju/jimm/thunks.test.ts
src/juju/jimm/thunks.ts

- Prepare dashboard for dashboard charm release.
- Fix `/auth/login`, `/auth/whoami`, `/auth/logout` and websocket endpoints.
- Follow the instructions from [this PR](https://github.com/canonical/juju-dashboard-charm/pull/33).
- https://warthogs.atlassian.net/browse/WD-14879

WD-14879 - feat: before 0.13.0 release changes

---

HACKING.md

Update the instructions for how to run the latest JIMM env.
https://warthogs.atlassian.net/browse/WD-16018

WD-16018 - doc: update instructions for running JIMM

---

package.json
yarn.lock

- Fix access to application details in dashboard k8s and machine charm running with juju controller.
- Make sure the dashboard k8s and machine charm works with a juju controller.
- https://warthogs.atlassian.net/browse/WD-16328

WD-16328 - feat: fix access to application details in dashboard charm

---

package.json

- Update dashboard version to `0.13.2`.

feat: update dashboard version to 0.13.2

---

src/components/PrimaryNav/PrimaryNav.tsx
src/components/PrimaryNav/types.ts
src/components/SecondaryNavigation/SecondaryNavigation.test.tsx
src/components/SecondaryNavigation/SecondaryNavigation.tsx
src/components/SecondaryNavigation/_secondary-navigation.scss
src/components/SecondaryNavigation/index.ts
src/components/SecondaryNavigation/types.ts
src/layout/BaseLayout/BaseLayout.test.tsx
src/layout/BaseLayout/BaseLayout.tsx
src/layout/BaseLayout/_base-layout.scss
src/pages/Permissions/Permissions.tsx
src/pages/Permissions/types.ts

Add secondary navigation component.
https://warthogs.atlassian.net/browse/WD-16060

WD-16060 - feat: add secondary navigation component

---

package.json
src/components/PrimaryNav/PrimaryNav.test.tsx
src/components/PrimaryNav/PrimaryNav.tsx
src/components/Routes/Routes.test.tsx
src/components/Routes/Routes.tsx
src/layout/BaseLayout/BaseLayout.tsx
src/pages/AdvancedSearch/AdvancedSearch.tsx
src/pages/AdvancedSearch/index.ts
src/pages/AdvancedSearch/types.ts
src/pages/ControllersIndex/ControllersIndex.tsx
src/pages/ControllersIndex/index.ts
src/pages/ControllersIndex/types.ts
src/pages/EntityDetails/EntityDetails.tsx
src/pages/EntityDetails/index.ts
src/pages/EntityDetails/types.ts
src/pages/Logs/Logs.tsx
src/pages/Logs/index.ts
src/pages/Logs/types.ts
src/pages/ModelsIndex/ModelsIndex.tsx
src/pages/ModelsIndex/index.ts
src/pages/ModelsIndex/types.ts
src/pages/Permissions/Permissions.tsx
src/pages/Permissions/index.ts
src/pages/Permissions/types.ts
src/store/general/selectors.test.ts
src/store/general/selectors.ts
src/store/general/types.ts
src/store/middleware/model-poller.test.ts
src/store/middleware/model-poller.ts
yarn.lock

Don't display ReBAC Admin if the user is not a JIMM admin.
https://warthogs.atlassian.net/browse/WD-16027

WD-16027 - feat: only display ReBAC Admin to JIMM admins

---

src/juju/jimm/api.test.ts

Added unit tests for jimmEndpoint to check that the endpoints are generated correctly.
- All tests should run
https://warthogs.atlassian.net/browse/WD-15560

test(jimmEndpoint): Add unit tests

---

src/components/secrets/RevisionField/RevisionField.test.tsx
src/components/secrets/RevisionField/RevisionField.tsx
src/components/secrets/SecretForm/SecretForm.tsx
src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.test.tsx
src/pages/EntityDetails/Model/Secrets/SecretContent/SecretContent.tsx
src/pages/EntityDetails/Model/Secrets/SecretsTable/SecretsTable.tsx
src/panels/RemoveSecretPanel/Fields/Fields.test.tsx
src/panels/RemoveSecretPanel/Fields/Fields.tsx
src/panels/RemoveSecretPanel/RemoveSecretPanel.tsx
src/panels/SecretFormPanel/SecretFormPanel.tsx
src/store/juju/selectors.test.ts
src/store/juju/selectors.ts
src/store/juju/slice.ts
src/utils/getLatestRevision.test.ts
src/utils/getLatestRevision.ts
src/utils/index.ts

Fixes the bug related to latest-revision.
- Update the value of a secret
- Remove the last added value
- The revision value should be changed to the next most latest revision
https://warthogs.atlassian.net/browse/WD-8783

fix: Compute latest revision from revisions array

---

HACKING.md
docs/multipass-microk8s.md

Updated the instructions for testing the dashboard with microk8s

chore(docs): updated microk8s instructions

---

package.json

Update dashboard to version `0.14.0` for upcoming release.
https://warthogs.atlassian.net/browse/WD-18920

build: update dashboard version to 0.14.0

---

package.json
yarn.lock

Update dashboard to version 0.14.1 for upcoming release. Bumps rebac-admin to fix breaking build.

build: update dashboard version to 0.14.1

---

src/auth/OIDCAuth.test.ts
src/auth/OIDCAuth.ts
src/auth/index.ts
src/auth/mixins/index.ts
src/auth/mixins/polling.test.ts
src/auth/mixins/polling.ts

Implement `OIDCAuth` subclass.
- WD-20705

feat: implement `OIDCAuth` subclass

---

src/auth/LocalAuth.test.ts
src/auth/LocalAuth.ts
src/auth/index.ts

Implement `LocalAuth` subclass.
- WD-20707

feat: implement `LocalAuth` subclass

---

src/auth/CandidAuth.test.ts
src/auth/CandidAuth.ts
src/auth/index.ts

Implement `CandidAuth` subclass.
- WD-20706

feat: implement `CandidAuth` subclass

---

src/auth/Auth.test.ts
src/auth/Auth.ts
src/auth/CandidAuth.ts
src/auth/LocalAuth.ts
src/auth/OIDCAuth.ts
src/auth/index.ts
src/auth/mixins/polling.test.ts
src/auth/types.ts
src/auth/utils.ts
src/components/LogIn/LogIn.test.tsx
src/components/LogIn/LogIn.tsx
src/components/Routes/Routes.test.tsx
src/index.tsx
src/juju/api.test.ts
src/juju/jimm/api.test.ts
src/juju/jimm/listeners.test.ts
src/juju/jimm/thunks.test.ts
src/store/app/thunks.test.ts
src/store/general/types.ts
src/testing/factories/general.ts
src/testing/utils.tsx
src/types.ts

- remove references to `AuthMethod`
- change references of `WindowConfig` to `Config`
- alter handful of tests to behave without `config.authMethod`
- Pull code
- Make sure everything behaves
WD-20710
> [!note]
> Builds on #1916, so there's an extra commit included

feat: remove `AuthMethod`

---

.github/actions/run-playwright/action.yml
.github/actions/setup-juju/action.yml
.github/actions/setup-machine-charm/action.yml
.github/workflows/e2e-juju-machine-charm-local-auth.yml
.github/workflows/end-to-end.yml
.gitignore
e2e/base/init.spec.ts
package.json
playwright.config.ts
yarn.lock

Add workflow for testing the dashboard, machine charm and local auth.
See the test output from the successful run:
https://github.com/canonical/juju-dashboard/actions/runs/14256619909/job/39960347932?pr=1917
The test result is uploaded as an artefact:
https://github.com/canonical/juju-dashboard/actions/runs/14256619909?pr=1917
https://warthogs.atlassian.net/browse/WD-20937

chore(test): Add machine charm/local auth e2e workflow

---

.github/actions/run-playwright/action.yml
.github/actions/setup-candid/action.yaml
.github/workflows/e2e-juju-machine-charm-candid-auth.yml
.github/workflows/end-to-end.yml

- Create E2E workflow with Candid auth
- Update playwright test to include `test-identifier` parameter for unique artifact locations
https://github.com/canonical/juju-dashboard/actions/runs/14259527038
https://github.com/canonical/juju-dashboard/actions/runs/14259527038/job/39968063437

feat: add Juju LXD Candid workflow

---

.github/actions/setup-k8s-charm/action.yml
.github/actions/setup-machine-charm/action.yml
.github/workflows/e2e-juju-k8s-charm-local-auth.yml
.github/workflows/e2e-juju-machine-charm-candid-auth.yml
.github/workflows/e2e-juju-machine-charm-local-auth.yml
e2e/base/auth-validation.spec.ts
e2e/helpers/auth-helpers.ts

- Introduced an end-to-end test suite to verify that a user can't bypass authentication
- Tests 
- the user cannot access pages without logging in
- the user cannot login with invalid credentials
- the user has to login again if cookie/local storage has invalid value
- All tests should pass
https://warthogs.atlassian.net/browse/WD-20950

feat(e2e): implement 'auth validation' test suite

---

e2e/base/models.spec.ts
e2e/juju/web-cli.spec.ts

- Added test suite for Juju Web CLI
- All tests should pass
https://warthogs.atlassian.net/browse/WD-20953

feat(e2e): Add test suite for Juju Web CLI

---

e2e/base/auth-validation.spec.ts
e2e/base/controllers.spec.ts
e2e/base/models.spec.ts
e2e/helpers/auth-helpers.ts
e2e/juju/web-cli.spec.ts
package.json
yarn.lock

- Added test case for verifying that a user cannot view a model without access
- All tests should pass
https://warthogs.atlassian.net/browse/WD-20951

feat(e2e): Add test case for model access

---

.github/workflows/e2e-jimm-k8s-charm-oidc-auth.yml
e2e/helpers/auth-helpers.ts
e2e/jimm/rebac.spec.ts

- add an e2e test for accessing ReBAC Admin
https://warthogs.atlassian.net/browse/WD-20956

chore(test): add an e2e test for accessing ReBAC Admin

---

.github/actions/run-playwright/action.yml
.github/actions/setup-k8s-charm/action.yml
.github/actions/setup-machine-charm/action.yml
.github/workflows/e2e-jimm-k8s-charm-oidc-auth.yml

- Remove charm build files.
- Use a GitHub Action that cleans up disk space.
- Remove additional caches.
This clears close to 30GB of disk space.
https://warthogs.atlassian.net/browse/WD-21844

Free disk space for jimm workflow

---

e2e/base/actions.spec.ts
e2e/fixtures/setup.ts
e2e/helpers/actions/addModel.ts
e2e/helpers/actions/deployApplication.ts
e2e/helpers/actions/index.ts
e2e/helpers/auth/Users.ts
e2e/helpers/objects/application.ts
e2e/helpers/objects/index.ts
e2e/utils/generateRandomName.ts
e2e/utils/index.ts

- Introduced Actions test suite to verify that a user can run charm actions and view action logs
https://warthogs.atlassian.net/browse/WD-20944

feat(e2e): Implement Actions test suite

---

e2e/jimm/cross-model-queries.spec.ts
src/pages/AdvancedSearch/SearchForm/SearchForm.tsx

- Test that models can be searched via the cross model queries page.
Passing run:
https://github.com/canonical/juju-dashboard/actions/runs/14961884364/job/42027257195?pr=1955
https://warthogs.atlassian.net/browse/WD-20954

chore(CI): Add e2e test for cross model queries

---

.github/actions/send-notification/action.yml
.github/workflows/end-to-end.yml

- Changed the channel that the e2e alerts happen in to use `juju-dashboard`.
https://warthogs.atlassian.net/browse/WD-22016

chore(ci): update the e2e alerts to notify in the juju-dashboard channel

---

SECURITY.md

- Add a security policy notice.

chore: add security policy notice

---

e2e/fixtures/setup.ts
e2e/helpers/auth/AuthImplementation.ts
e2e/helpers/auth/Users.ts
e2e/helpers/auth/backends/Keycloak.ts
e2e/helpers/auth/backends/OIDC.ts
e2e/helpers/auth/backends/utils.ts
e2e/helpers/juju-cli.ts
e2e/utils/getEnv.ts

Add Keycloak authentication in the e2e tests.
See that it passes here: https://github.com/canonical/juju-dashboard/actions/runs/16339380254/job/46158007315?pr=2000#step:14:402
https://warthogs.atlassian.net/browse/WD-23522

chore(ci): add Keycloak authentication

---

.gitignore
charms/generate-charmhub-token.sh

Helper script to generate charmhub token with correct permissions for publishing in CI.

feat: script to generate charmhub token for CI

---

.github/workflows/test-charms.yml
.github/workflows/test-custom-actions.yml

- Fixes https://github.com/canonical/juju-dashboard/security/code-scanning/34
- Fixes https://github.com/canonical/juju-dashboard/security/code-scanning/30
- Fixes https://github.com/canonical/juju-dashboard/security/code-scanning/29
- Fixes https://github.com/canonical/juju-dashboard/security/code-scanning/28

fix: add workflow permissions to actions

---

.github/actions/setup-k8s-charm/action.yml
charms/k8s-charm/build.sh
src/components/WebCLI/WebCLI.test.tsx
src/components/WebCLI/connection.ts

Fixes https://github.com/canonical/juju-dashboard/security/code-scanning/33

fix: remove `redirect-to` support in WebCLI connection handling

---

CONTRIBUTING.md
HACKING.md
RELEASING.md

- Removed deprecated internal links from docs
- Updated QA information
- Added latest steps to setup a local JIMM controller and JAAS Dashboard
https://warthogs.atlassian.net/browse/WD-24148

chore: Update docs with latest setup, build and QA information

---

.github/workflows/release.yml

- fix release workflow run filtering

fix(ci): correctly filter workflow run

---

eslint.config.mjs
src/auth/Auth.ts
src/store/app/thunks.ts
src/store/juju/thunks.ts
src/testing/setup.ts

- Added the [require-await](https://typescript-eslint.io/rules/require-await/) rule.
- Disabled the rule for tests (lots of mocked things return a value instead of a promise).
- Fixed issues.

chore(lint): add require-await rule

---

eslint.config.mjs
src/components/DonutChart/DonutChart.tsx
src/components/WebCLI/connection.ts
src/hooks/useQueryParams.ts
src/juju/api.test.ts
src/juju/api.ts
src/store/juju/selectors.ts
src/store/middleware/check-auth.test.ts
src/store/middleware/model-poller.test.ts

- Added [no-unsafe-argument](https://typescript-eslint.io/rules/no-unsafe-argument/) rule.
- Fixed issues.
- Pull code

chore(lint): add no-unsafe-argument rule

---

.github/actions/setup-jimm/action.yml

- retry postgres-openfga relation

chore(ci): retry postgres-openfga relation

---

.github/actions/setup-jimm/action.yml

- Upgraded the postgresql charm to the edge version to try and resolve the PrematureDataAccessError issue. I've run it quite a few times and it has passed each time.

Upgrade to edge postgres charm

---

e2e/base/auth-validation.spec.ts
e2e/fixtures/setup.ts
e2e/helpers/action.ts
e2e/helpers/actions/addModel.ts
e2e/helpers/actions/deployApplication.ts
e2e/helpers/actions/utils/give-access.ts
e2e/helpers/auth/AuthImplementation.ts
e2e/helpers/auth/Users.ts
e2e/helpers/auth/backends/Candid.ts
e2e/helpers/auth/backends/Keycloak.ts
e2e/helpers/auth/backends/Local.ts
e2e/helpers/auth/backends/OIDC.ts
e2e/helpers/auth/backends/utils.ts
e2e/helpers/juju-cli.ts
e2e/jimm/rebac.spec.ts
e2e/juju/web-cli.spec.ts
e2e/utils/addFeatureFlags.ts
e2e/utils/exec.ts
e2e/utils/findLine.ts
e2e/utils/generateRandomName.ts
e2e/utils/getEnv.ts
eslint.config.mjs

- Apply the eslint rules to the e2e directory.
https://warthogs.atlassian.net/browse/WD-27203

fix lint rules for e2e files

---

.github/actions/create-cut-pr/index.js
.github/actions/create-release-pr/index.js
.github/actions/extract-changelog/index.js
actions/src/create-cut-pr/index.ts
actions/src/create-cut-pr/main.test.ts
actions/src/create-cut-pr/main.ts
actions/src/create-release-pr/index.ts
actions/src/create-release-pr/main.test.ts
actions/src/create-release-pr/main.ts
actions/src/extract-changelog/index.ts
actions/src/extract-changelog/main.test.ts
actions/src/extract-changelog/main.ts
actions/src/lib/branch.ts
actions/src/lib/git.ts
actions/src/lib/github/pull-request.ts
actions/src/lib/github/repository.ts
actions/src/lib/github/types.ts
actions/src/lib/index.ts
actions/src/lib/package.ts
actions/src/lib/test-utils.ts
actions/src/lib/version.ts
eslint.config.mjs

- Apply lint rules to the actions folder and fix issues.
- Rebuild actions.

Fix lint rules for actions

---

src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.test.tsx
src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx

- Group actions in action log by the application they ran in (fixes #2124)
- Pull code
- Create a model with two applications running in it:
- `juju create-model some-application`
- `juju deploy postgresql pg1`
- `juju deploy postgresql pg2`
- In the dashboard navigate to the model, and search `pg`
- Select both applications, press 'Run action', and run the `get-primary` action (or any other action)
- Navigate to the model action logs, and verify the entries are separate

fix(action-log): group actions by the application they ran in
